#!/usr/bin/env bash
#
# Mixed workload jar test — exercises the MixedLoad engine step directly
# without the CLI, using a generated JavaScript scenario file.
#
# The script creates a three-phase scenario:
#   1. Seed phase: writes SEED_COUNT objects (PreconditionLoad)
#   2. Mixed benchmark: runs for TIME_LIMIT with weighted GET/PUT/DELETE/STAT
#   3. Cleanup: deletes seed + PUT-created objects (optional, MIXED_CLEANUP=true)
#
# Prerequisites:
#   - SPT distribution built (./gradlew :bundle:build)
#   - An S3-compatible endpoint reachable at S3_ENDPOINTS
#
# Usage:
#   ./tools/jartest.mixed.sh
#
#   # Override defaults via environment:
#   MIXED_GET=60 MIXED_PUT=25 MIXED_DELETE=10 MIXED_STAT=5 \
#     MIXED_TIME_LIMIT=5m ./tools/jartest.mixed.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENGINE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GIT_ROOT="$(cd "$ENGINE_ROOT/.." && pwd)"
RUN_SCRIPT="$ENGINE_ROOT/bundle/build/dist/run.sh"

# ---------------------------------------------------------------------------
# Environment: snapshot caller overrides, source .env, then restore overrides
# ---------------------------------------------------------------------------
declare -A _caller_env
for _v in S3_ENDPOINTS S3_ACCESS_KEY S3_SECRET_KEY S3_BUCKET S3_AUTH_VERSION \
          MIXED_CONCURRENCY MIXED_OBJECT_SIZE MIXED_TIME_LIMIT \
          MIXED_SEED_COUNT MIXED_GET MIXED_PUT MIXED_DELETE MIXED_STAT \
          MIXED_CLEANUP; do
  [[ -n "${!_v+set}" ]] && _caller_env[$_v]="${!_v}"
done

if [[ -f "$GIT_ROOT/.env" ]]; then
  # shellcheck disable=SC1091
  source "$GIT_ROOT/.env"
elif [[ -f "$ENGINE_ROOT/.env" ]]; then
  # shellcheck disable=SC1091
  source "$ENGINE_ROOT/.env"
fi

for _v in "${!_caller_env[@]}"; do
  export "$_v=${_caller_env[$_v]}"
done
unset _caller_env _v

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
: "${S3_ENDPOINTS:=http://127.0.0.1:9000}"
: "${S3_ACCESS_KEY:=AWS_ACCESS_KEY_ID_EXAMPLE}"
: "${S3_SECRET_KEY:=AWS_SECRET_ACCESS_KEY_EXAMPLE}"
: "${S3_BUCKET:=testmixed}"
: "${S3_AUTH_VERSION:=4}"

: "${MIXED_CONCURRENCY:=4}"
: "${MIXED_OBJECT_SIZE:=1MB}"
: "${MIXED_TIME_LIMIT:=30s}"
: "${MIXED_SEED_COUNT:=2500}"

# Distribution weights (must sum to 100)
: "${MIXED_GET:=45}"
: "${MIXED_PUT:=30}"
: "${MIXED_DELETE:=15}"
: "${MIXED_STAT:=10}"

: "${MIXED_CLEANUP:=false}"

# ---------------------------------------------------------------------------
# Derived paths
# ---------------------------------------------------------------------------
NODE_ADDRS="${S3_ENDPOINTS//http:\/\/}"
NODE_ADDRS="${NODE_ADDRS//https:\/\/}"

if [[ ! -x "$RUN_SCRIPT" ]]; then
  echo "Run script not found at $RUN_SCRIPT; building distribution..." >&2
  (cd "$ENGINE_ROOT" && ./gradlew -q :bundle:build)
fi

# ---------------------------------------------------------------------------
# Validate distribution
# ---------------------------------------------------------------------------
TOTAL=$(( MIXED_GET + MIXED_PUT + MIXED_DELETE + MIXED_STAT ))
if (( TOTAL != 100 )); then
  echo "ERROR: distribution weights must sum to 100, got $TOTAL" >&2
  echo "  GET=$MIXED_GET PUT=$MIXED_PUT DELETE=$MIXED_DELETE STAT=$MIXED_STAT" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Results directory
# ---------------------------------------------------------------------------
RESULTS_DIR="${SCRIPT_DIR}/results/mixedtest-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$RESULTS_DIR"

# ---------------------------------------------------------------------------
# Generate JavaScript scenario
# ---------------------------------------------------------------------------
TS="$(date +%Y%m%d-%H%M%S)"
STEP_SEED="mixed-${TS}-1-seed"
STEP_MIXED="mixed-${TS}-2-mixed"
STEP_CLEANUP_SEED="mixed-${TS}-3-cleanup-seed"
STEP_CLEANUP_PUT="mixed-${TS}-4-cleanup-put"

SCENARIO_FILE="${RESULTS_DIR}/mixed-scenario.js"

cat > "$SCENARIO_FILE" <<SCENARIO_EOF
// Generated by jartest.mixed.sh
// Mixed workload: GET ${MIXED_GET}% / PUT ${MIXED_PUT}% / DELETE ${MIXED_DELETE}% / STAT ${MIXED_STAT}%
// Concurrency: ${MIXED_CONCURRENCY}, Size: ${MIXED_OBJECT_SIZE}, Duration: ${MIXED_TIME_LIMIT}

var concurrency = ${MIXED_CONCURRENCY};
var itemSize = "${MIXED_OBJECT_SIZE}";
var duration = "${MIXED_TIME_LIMIT}";
var outputPath = "/${S3_BUCKET}";
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
var seedCount = ${MIXED_SEED_COUNT};
var itemsFile = sptLogDir + "/log/${STEP_SEED}/items.csv";
var putRemainingFile = sptLogDir + "/log/${STEP_MIXED}/put-remaining.csv";
var pauseTime = 10;

function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

var sharedConfig = {
    "storage": {
        "driver": {
            "type": "s3",
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    }
};

// Phase 1: Seed
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting seed phase - " + seedCount + " objects");
PreconditionLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": seedCount
                }
            },
            "step": {
                "id": "${STEP_SEED}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Seed phase completed");

// Phase 2: Mixed benchmark
pause(pauseTime, "Starting mixed workload - duration: " + duration);
print("[" + new Date().toISOString() + "] Mixed benchmark started");
MixedLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
            "step": {
                "limit": {
                    "time": duration
                },
                "id": "${STEP_MIXED}"
            },
            "op": {
                "weight": {
                    "get": ${MIXED_GET},
                    "put": ${MIXED_PUT},
                    "delete": ${MIXED_DELETE},
                    "stat": ${MIXED_STAT}
                }
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Mixed benchmark completed");
SCENARIO_EOF

# Append cleanup phases if requested
if [[ "$MIXED_CLEANUP" == "true" ]]; then
  cat >> "$SCENARIO_FILE" <<CLEANUP_EOF

// Phase 3: Cleanup seed objects
pause(pauseTime, "Pausing before cleanup...");
print("[" + new Date().toISOString() + "] Cleaning up seed objects");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "${STEP_CLEANUP_SEED}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Seed cleanup completed");

// Phase 4: Cleanup PUT-created objects
print("[" + new Date().toISOString() + "] Cleaning up PUT-created objects");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": putRemainingFile
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "${STEP_CLEANUP_PUT}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] PUT cleanup completed");
CLEANUP_EOF
fi

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
echo "== mixedtest: seed=${MIXED_SEED_COUNT}, GET=${MIXED_GET}% PUT=${MIXED_PUT}% DELETE=${MIXED_DELETE}% STAT=${MIXED_STAT}% =="
echo "== Duration: ${MIXED_TIME_LIMIT}, Size: ${MIXED_OBJECT_SIZE}, Concurrency: ${MIXED_CONCURRENCY} =="
echo "== Cleanup: ${MIXED_CLEANUP} =="
echo "== Scenario: ${SCENARIO_FILE} =="
echo "== Results: ${RESULTS_DIR} =="

"$RUN_SCRIPT" \
  --storage-net-node-addrs="${NODE_ADDRS}" \
  --storage-auth-version="${S3_AUTH_VERSION}" \
  --storage-auth-uid="${S3_ACCESS_KEY}" \
  --storage-auth-secret="${S3_SECRET_KEY}" \
  -f "${SCENARIO_FILE}" \
  "$@" 2>&1 | tee "${RESULTS_DIR}/output.log"

echo "== Results saved to: ${RESULTS_DIR} =="
