package com.dell.spt.base.config;

import com.github.akurilov.confuse.Config;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test coverage for TestConfigBuilder test infrastructure.
 * 
 * This tests our test configuration builder utility to ensure it works correctly
 * and provides proper examples of usage patterns. These tests should be kept
 * permanently as they validate our test infrastructure.
 * 
 * Tests the key insight: BasicConfig with 3-parameter constructor enables
 * hyphenated path translation via confuse library.
 */
@DisplayName("TestConfigBuilder Tests")
class TestTestConfigBuilder {

	@Test
	@DisplayName("Basic config creation should work without exceptions")
	void testBasicConfigCreation() {
		assertDoesNotThrow(() -> {
			Config config = TestConfigBuilder.config();
			assertNotNull(config, "Config should not be null");
		});
	}

	@Test
	@DisplayName("Hyphenated path resolution should work - load-step-id")
	void testHyphenatedPathResolution() {
		Config config = TestConfigBuilder.config();

		// This is the critical test - hyphenated paths should resolve
		assertDoesNotThrow(() -> {
			String stepId = config.stringVal("load-step-id");
			assertEquals("test-step-001", stepId, "load-step-id should resolve to test value");
		});
	}

	@Test
	@DisplayName("Multiple hyphenated paths should work")
	void testMultipleHyphenatedPaths() {
		Config config = TestConfigBuilder.config();

		assertAll("All hyphenated paths should resolve",
						() -> {
							String stepId = config.stringVal("load-step-id");
							assertEquals("test-step-001", stepId);
						},
						() -> {
							boolean autoGenerated = config.boolVal("load-step-idAutoGenerated");
							assertFalse(autoGenerated);
						},
						() -> {
							int batchSize = config.intVal("load-batch-size");
							assertEquals(100, batchSize);
						},
						() -> {
							String opType = config.stringVal("load-op-type");
							assertEquals("create", opType);
						},
						() -> {
							String driverType = config.stringVal("storage-driver-type");
							assertEquals("dummy-mock", driverType);
						},
						() -> {
							long countLimit = config.longVal("load-op-limit-count");
							assertEquals(0L, countLimit);
						});
	}

	@Test
	@DisplayName("Setting values should work")
	void testSettingValues() {
		Config config = TestConfigBuilder.config();
		config.val("load-step-id", "custom-step-id");
		config.val("load-op-type", "read");
		config.val("storage-driver-limit-concurrency", 50);
		config.val("load-batch-size", 200);

		assertAll("Setting values should work",
						() -> assertEquals("custom-step-id", config.stringVal("load-step-id")),
						() -> assertEquals("read", config.stringVal("load-op-type")),
						() -> assertEquals(50, config.intVal("storage-driver-limit-concurrency")),
						() -> assertEquals(200, config.intVal("load-batch-size")));
	}

	@Test
	@DisplayName("Setting specific values should work")
	void testSettingSpecificValues() {
		Config configWithStepId = TestConfigBuilder.config();
		configWithStepId.val("load-step-id", "factory-step");
		assertEquals("factory-step", configWithStepId.stringVal("load-step-id"));

		Config configWithOpType = TestConfigBuilder.config();
		configWithOpType.val("load-op-type", "delete");
		assertEquals("delete", configWithOpType.stringVal("load-op-type"));
	}

	@Test
	@DisplayName("Complex nested paths should work")
	void testComplexNestedPaths() {
		Config config = TestConfigBuilder.config();

		assertAll("Complex nested paths should resolve",
						() -> {
							String authFile = config.stringVal("storage-auth-file");
							assertEquals("", authFile);
						},
						() -> {
							String outputFile = config.stringVal("item-output-file");
							assertEquals("", outputFile);
						},
						() -> {
							long failCount = config.longVal("load-op-limit-fail-count");
							assertEquals(100000L, failCount);
						},
						() -> {
							String comment = config.stringVal("run-comment");
							assertEquals("", comment);
						});
	}
}
