package com.dell.spt.base.load.step.service;

import static com.dell.spt.base.Constants.KEY_CLASS_NAME;
import static com.dell.spt.base.Constants.KEY_STEP_ID;
import static org.apache.logging.log4j.CloseableThreadContext.Instance;
import static org.apache.logging.log4j.CloseableThreadContext.put;

import com.dell.spt.base.env.Extension;
import com.dell.spt.base.load.step.DurationAwaitStatus;
import com.dell.spt.base.load.step.LoadStepFactory;
import com.dell.spt.base.load.step.LoadStep;
import com.dell.spt.base.item.op.deletion.DeleteObjectLifecycleSnapshot;
import com.dell.spt.base.logging.Loggers;
import com.dell.spt.base.metrics.MetricsManager;
import com.dell.spt.base.metrics.snapshot.AllMetricsSnapshot;
import com.dell.spt.base.svc.ServiceBase;
import com.github.akurilov.confuse.Config;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.TimeUnit;

public final class LoadStepServiceImpl extends ServiceBase implements LoadStepService {

	private final LoadStep localLoadStep;
	private CompletableFuture<Void> durationDrainTask;

	public LoadStepServiceImpl(
					final int port,
					final List<Extension> extensions,
					final String stepType,
					final Config baseConfig,
					final List<Config> ctxConfigs,
					final MetricsManager metricsManager) {
		super(port);
		baseConfig.val(
						"load-step-idAutoGenerated",
						false); // don't override the step-id value on the remote node again
		localLoadStep = LoadStepFactory.createLocalLoadStep(
						baseConfig, extensions, ctxConfigs, metricsManager, stepType);
		final String stepId = baseConfig.stringVal("load-step-id");
		try (final Instance logCtx = put(KEY_STEP_ID, stepId).put(KEY_CLASS_NAME, getClass().getSimpleName())) {
			Loggers.MSG.info("New step service for type \"{}\"", stepType);
			super.doStart();
		}
	}

	@Override
	protected final void doStart() {
		try (final Instance logCtx = put(KEY_CLASS_NAME, getClass().getSimpleName()).put(KEY_STEP_ID, safeLoadStepId())) {
			localLoadStep.start();
			Loggers.MSG.info("Step service for \"{}\" is started", safeLoadStepId());
		} catch (final RemoteException e) {
			Loggers.ERR.warn("Step service start failure for {}", safeLoadStepId(), e);
			throw new IllegalStateException("Failed to start load step service " + safeLoadStepId(), e);
		}
	}

	@Override
	protected void doShutdown() {
		try (final Instance logCtx = put(KEY_CLASS_NAME, getClass().getSimpleName()).put(KEY_STEP_ID, safeLoadStepId())) {
			localLoadStep.shutdown();
			Loggers.MSG.debug("Step service for \"{}\" is shutdown", safeLoadStepId());
		} catch (final RemoteException e) {
			Loggers.ERR.warn("Step service shutdown failure for {}", safeLoadStepId(), e);
			throw new IllegalStateException("Failed to shutdown load step service " + safeLoadStepId(), e);
		}
	}

	@Override
	protected void doStop() {
		try (final Instance logCtx = put(KEY_CLASS_NAME, getClass().getSimpleName()).put(KEY_STEP_ID, safeLoadStepId())) {
			localLoadStep.stop();
			Loggers.MSG.info("Step service for \"{}\" is stopped", safeLoadStepId());
		} catch (final RemoteException e) {
			Loggers.ERR.warn("Step service stop failure for {}", safeLoadStepId(), e);
			throw new IllegalStateException("Failed to stop load step service " + safeLoadStepId(), e);
		}
	}

	@Override
	protected final void doClose() throws IOException {
		try (final Instance logCtx = put(KEY_CLASS_NAME, getClass().getSimpleName()).put(KEY_STEP_ID, localLoadStep.loadStepId())) {
			localLoadStep.close();
			super.doStop();
			Loggers.MSG.info("Step service for \"{}\" is closed", localLoadStep.loadStepId());
		}
	}

	@Override
	public String name() {
		return SVC_NAME_PREFIX + hashCode();
	}

	@Override
	public final String loadStepId() throws RemoteException {
		return localLoadStep.loadStepId();
	}

	@Override
	public long runId()
					throws RemoteException {
		return localLoadStep.runId();
	}

	@Override
	public final String getTypeName() throws RemoteException {
		return localLoadStep.getTypeName();
	}

	@Override
	public final List<? extends AllMetricsSnapshot> metricsSnapshots() throws RemoteException {
		return localLoadStep.metricsSnapshots();
	}

	@Override
	public final DeleteObjectLifecycleSnapshot deleteObjectLifecycle() throws RemoteException {
		return localLoadStep.deleteObjectLifecycle();
	}

	@Override
	public final void releaseObjectFailureBudgetAdmission() throws RemoteException {
		localLoadStep.releaseObjectFailureBudgetAdmission();
	}

	@Override
	public final void prepareDurationInterval(final long durationNanos) throws RemoteException {
		localLoadStep.prepareDurationInterval(durationNanos);
	}

	@Override
	public final void startDurationInterval(final long durationNanos) throws RemoteException {
		localLoadStep.startDurationInterval(durationNanos);
	}

	@Override
	public final void closeOperationAdmissionForStepStop() throws RemoteException {
		localLoadStep.closeOperationAdmissionForStepStop();
	}

	@Override
	public final void enforceDispatchedOperationsDeadlineForStepStop(final long remainingNanos)
					throws RemoteException {
		localLoadStep.enforceDispatchedOperationsDeadlineForStepStop(remainingNanos);
	}

	@Override
	public final void recoverQueuedOperationsForStepStop() throws RemoteException {
		localLoadStep.recoverQueuedOperationsForStepStop();
	}

	@Override
	public final void drainDispatchedOperationsForStepStop(final long remainingNanos)
					throws RemoteException {
		localLoadStep.drainDispatchedOperationsForStepStop(remainingNanos);
	}

	@Override
	public final synchronized void startDispatchedOperationsDrainForStepStop(
					final long remainingNanos) {
		if (durationDrainTask != null) {
			if (!durationDrainTask.isDone()) {
				return;
			}
			try {
				durationDrainTask.join();
				return;
			} catch (final CompletionException ignored) {
				// An explicit controller cleanup retry may safely begin a fresh local attempt.
			}
		}
		final CompletableFuture<Void> nextTask = new CompletableFuture<>();
		durationDrainTask = nextTask;
		final Thread drainThread = Thread.ofPlatform()
						.daemon()
						.name("spt-delete-service-drain-" + safeLoadStepId())
						.unstarted(() -> {
							try {
								localLoadStep.drainDispatchedOperationsForStepStop(remainingNanos);
								nextTask.complete(null);
							} catch (final Throwable failure) {
								nextTask.completeExceptionally(failure);
							}
						});
		drainThread.start();
	}

	@Override
	public final synchronized boolean isDispatchedOperationsDrainCompleteForStepStop()
					throws RemoteException {
		if (durationDrainTask == null || !durationDrainTask.isDone()) {
			return false;
		}
		try {
			durationDrainTask.join();
			return true;
		} catch (final CompletionException failure) {
			final Throwable cause = failure.getCause();
			throw new RemoteException(
							"standalone DELETE dispatched-operation drain failed",
							cause instanceof Exception exception ? exception : new Exception(cause));
		}
	}

	@Override
	public final void validateTerminalStateForStepStop() throws RemoteException {
		localLoadStep.validateTerminalStateForStepStop();
	}

	@Override
	public final void verifyDeleteInventoryForStepStop() throws RemoteException {
		localLoadStep.verifyDeleteInventoryForStepStop();
	}

	@Override
	public final void startDeleteInventoryPreValidation() throws RemoteException {
		localLoadStep.startDeleteInventoryPreValidation();
	}

	@Override
	public final boolean isDeleteInventoryPreValidationComplete() throws RemoteException {
		return localLoadStep.isDeleteInventoryPreValidationComplete();
	}

	@Override
	public final void skipDeleteInventoryPostVerificationAfterStrictPreValidationFailure()
					throws RemoteException {
		localLoadStep.skipDeleteInventoryPostVerificationAfterStrictPreValidationFailure();
	}

	@Override
	public final boolean isDeleteInventoryVerificationCompleteForStepStop() throws RemoteException {
		return localLoadStep.isDeleteInventoryVerificationCompleteForStepStop();
	}

	@Override
	public final DurationAwaitStatus durationAwaitStatus() throws RemoteException {
		return localLoadStep.durationAwaitStatus();
	}

	@Override
	public final boolean await(final long timeout, final TimeUnit timeUnit)
					throws IllegalStateException, InterruptedException {
		try (final Instance logCtx = put(KEY_CLASS_NAME, getClass().getSimpleName()).put(KEY_STEP_ID, safeLoadStepId())) {
			return localLoadStep.await(timeout, timeUnit);
		} catch (final RemoteException e) {
			Loggers.ERR.warn("Await interrupted by remote failure for {}", safeLoadStepId(), e);
			return false;
		}
	}

	private String safeLoadStepId() {
		try {
			return localLoadStep.loadStepId();
		} catch (final RemoteException e) {
			return "unknown-step";
		}
	}
}
