package com.dell.spt.load.step.mixed;

import com.dell.spt.base.env.Extension;
import com.github.akurilov.confuse.Config;
import com.github.akurilov.confuse.impl.BasicConfig;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Focused unit tests for {@link MixedLoadStepClient}.
 *
 * <p>Tests construction, {@link MixedLoadStepClient#getTypeName()}, and the immutable copy
 * semantics of {@link MixedLoadStepClient#config(Map)} and
 * {@link MixedLoadStepClient#append(Map)}.
 */
class MixedLoadStepClientTest {

	private static final String PS = "-";

	@SuppressWarnings("unchecked")
	private static Map<String, Object> minimalSchema() {
		final Map<String, Object> schema = new HashMap<>();

		// load section
		final Map<String, Object> load = new HashMap<>();
		final Map<String, Object> step = new HashMap<>();
		step.put("id", String.class);
		step.put("idAutoGenerated", Boolean.class);
		final Map<String, Object> stepLimit = new HashMap<>();
		stepLimit.put("time", String.class);
		stepLimit.put("size", String.class);
		step.put("limit", stepLimit);
		final Map<String, Object> stepNode = new HashMap<>();
		stepNode.put("addrs", List.class);
		stepNode.put("port", Integer.class);
		step.put("node", stepNode);
		load.put("step", step);

		final Map<String, Object> op = new HashMap<>();
		final Map<String, Object> opLimit = new HashMap<>();
		opLimit.put("count", Long.class);
		opLimit.put("rate", Double.class);
		final Map<String, Object> opLimitFail = new HashMap<>();
		opLimitFail.put("count", Long.class);
		opLimit.put("fail", opLimitFail);
		op.put("limit", opLimit);
		op.put("type", String.class);
		op.put("weight", Integer.class); // WeightedLoad scalar key; MixedLoad uses weights below.
		final Map<String, Object> weights = new HashMap<>();
		weights.put("get", Integer.class);
		weights.put("put", Integer.class);
		weights.put("delete", Integer.class);
		weights.put("stat", Integer.class);
		op.put("weights", weights);
		load.put("op", op);

		final Map<String, Object> batch = new HashMap<>();
		batch.put("size", Integer.class);
		load.put("batch", batch);

		schema.put("load", load);

		// storage section
		final Map<String, Object> storage = new HashMap<>();
		final Map<String, Object> driver = new HashMap<>();
		final Map<String, Object> driverLimit = new HashMap<>();
		driverLimit.put("concurrency", Integer.class);
		driver.put("limit", driverLimit);
		driver.put("type", String.class);
		storage.put("driver", driver);
		final Map<String, Object> auth = new HashMap<>();
		auth.put("file", String.class);
		storage.put("auth", auth);
		final Map<String, Object> net = new HashMap<>();
		final Map<String, Object> netNode = new HashMap<>();
		netNode.put("slice", Boolean.class);
		netNode.put("addrs", List.class);
		net.put("node", netNode);
		storage.put("net", net);
		storage.put("integrity", Map.of(
						"mode", String.class,
						"algorithm", String.class,
						"input", Map.of("provenance", String.class, "expectedProducerId", String.class)));
		schema.put("storage", storage);

		// output section
		final Map<String, Object> output = new HashMap<>();
		output.put("color", Boolean.class);
		final Map<String, Object> metrics = new HashMap<>();
		final Map<String, Object> avg = new HashMap<>();
		avg.put("persist", Boolean.class);
		avg.put("period", String.class);
		metrics.put("average", avg);
		final Map<String, Object> summary = new HashMap<>();
		summary.put("persist", Boolean.class);
		metrics.put("summary", summary);
		final Map<String, Object> timing = new HashMap<>();
		timing.put("persist", Boolean.class);
		metrics.put("timing", timing);
		metrics.put("threshold", Double.class);
		metrics.put("quantiles", List.class);
		output.put("metrics", metrics);
		schema.put("output", output);

		// item section
		final Map<String, Object> item = new HashMap<>();
		final Map<String, Object> data = new HashMap<>();
		data.put("size", String.class);
		final Map<String, Object> dataInput = new HashMap<>();
		dataInput.put("file", String.class);
		dataInput.put("seed", String.class);
		final Map<String, Object> layer = new HashMap<>();
		layer.put("cache", Integer.class);
		layer.put("heap", Boolean.class);
		layer.put("size", String.class);
		dataInput.put("layer", layer);
		data.put("input", dataInput);
		data.put("verify", Boolean.class);
		item.put("data", data);
		final Map<String, Object> itemInput = new HashMap<>();
		itemInput.put("file", String.class);
		itemInput.put("path", String.class);
		item.put("input", itemInput);
		final Map<String, Object> itemOutput = new HashMap<>();
		itemOutput.put("file", String.class);
		itemOutput.put("path", String.class);
		item.put("output", itemOutput);
		schema.put("item", item);

		// run + aliasing
		final Map<String, Object> run = new HashMap<>();
		run.put("comment", String.class);
		run.put("id", Long.class);
		run.put("version", String.class);
		schema.put("run", run);
		schema.put("aliasing", List.class);

		return schema;
	}

	private static Map<String, Object> baseValues() {
		final Map<String, Object> values = new HashMap<>();

		final Map<String, Object> load = new HashMap<>();
		final Map<String, Object> step = new HashMap<>();
		step.put("id", "base-step");
		step.put("idAutoGenerated", false);
		final Map<String, Object> stepLimit = new HashMap<>();
		stepLimit.put("time", "0s");
		stepLimit.put("size", "0B");
		step.put("limit", stepLimit);
		final Map<String, Object> node = new HashMap<>();
		node.put("addrs", List.of());
		node.put("port", 9020);
		step.put("node", node);
		load.put("step", step);

		final Map<String, Object> op = new HashMap<>();
		final Map<String, Object> opLimit = new HashMap<>();
		opLimit.put("count", 0L);
		opLimit.put("rate", 0.0);
		final Map<String, Object> opLimitFail = new HashMap<>();
		opLimitFail.put("count", 0L);
		opLimit.put("fail", opLimitFail);
		op.put("limit", opLimit);
		op.put("type", "create");
		op.put("weight", 1); // WeightedLoad scalar key; MixedLoad uses weights below.
		final Map<String, Object> weights = new HashMap<>();
		weights.put("get", 60);
		weights.put("put", 25);
		weights.put("delete", 15);
		weights.put("stat", 0);
		op.put("weights", weights);
		load.put("op", op);

		final Map<String, Object> batch = new HashMap<>();
		batch.put("size", 1);
		load.put("batch", batch);

		values.put("load", load);

		final Map<String, Object> storage = new HashMap<>();
		final Map<String, Object> driver = new HashMap<>();
		final Map<String, Object> driverLimit = new HashMap<>();
		driverLimit.put("concurrency", 10);
		driver.put("limit", driverLimit);
		driver.put("type", "dummy-mock");
		storage.put("driver", driver);
		final Map<String, Object> auth = new HashMap<>();
		auth.put("file", "");
		storage.put("auth", auth);
		final Map<String, Object> net = new HashMap<>();
		final Map<String, Object> netNode = new HashMap<>();
		netNode.put("slice", false);
		netNode.put("addrs", List.of());
		net.put("node", netNode);
		storage.put("net", net);
		storage.put("integrity", Map.of(
						"mode", "none",
						"algorithm", "sha256",
						"input", Map.of("provenance", "none", "expectedProducerId", "")));
		values.put("storage", storage);

		final Map<String, Object> output = new HashMap<>();
		output.put("color", true);
		final Map<String, Object> metrics = new HashMap<>();
		final Map<String, Object> avg = new HashMap<>();
		avg.put("persist", false);
		avg.put("period", "1s");
		metrics.put("average", avg);
		final Map<String, Object> summary = new HashMap<>();
		summary.put("persist", false);
		metrics.put("summary", summary);
		final Map<String, Object> timingMetrics = new HashMap<>();
		timingMetrics.put("persist", false);
		metrics.put("timing", timingMetrics);
		metrics.put("threshold", 0.0);
		metrics.put("quantiles", List.of(0.25, 0.5, 0.75));
		output.put("metrics", metrics);
		values.put("output", output);

		final Map<String, Object> item = new HashMap<>();
		final Map<String, Object> data = new HashMap<>();
		data.put("size", "1MB");
		final Map<String, Object> dataInput = new HashMap<>();
		dataInput.put("file", "");
		dataInput.put("seed", "seed");
		final Map<String, Object> layer = new HashMap<>();
		layer.put("cache", 16);
		layer.put("heap", false);
		layer.put("size", "4MB");
		dataInput.put("layer", layer);
		data.put("input", dataInput);
		data.put("verify", false);
		item.put("data", data);
		final Map<String, Object> itemInput = new HashMap<>();
		itemInput.put("file", "");
		itemInput.put("path", "");
		item.put("input", itemInput);
		final Map<String, Object> itemOutput = new HashMap<>();
		itemOutput.put("file", "");
		itemOutput.put("path", "");
		item.put("output", itemOutput);
		values.put("item", item);

		final Map<String, Object> run = new HashMap<>();
		run.put("comment", "");
		run.put("id", 0L);
		run.put("version", "test");
		values.put("run", run);
		values.put("aliasing", List.of());

		return values;
	}

	private static Config newBaseConfig() {
		return new BasicConfig(PS, minimalSchema(), baseValues());
	}

	@Test
	@DisplayName("getTypeName returns MixedLoad")
	void testGetTypeName() {
		final Config cfg = newBaseConfig();
		final MixedLoadStepClient client = new MixedLoadStepClient(
						cfg, Collections.<Extension> emptyList(), Collections.emptyList(), null);
		assertEquals(MixedLoadStepExtension.TYPE, client.getTypeName());
	}

	@Test
	@DisplayName("config(Map) returns a new MixedLoadStepClient with updated step ID")
	void testCopyViaConfig() {
		final Config cfg = newBaseConfig();
		final MixedLoadStepClient client = new MixedLoadStepClient(
						cfg, Collections.<Extension> emptyList(), null, null);

		final MixedLoadStepClient copy = client.config(Map.of("load-step-id", "mixed-copy"));

		assertNotSame(client, copy);
		assertEquals("mixed-copy", copy.loadStepId());
		assertEquals("base-step", client.loadStepId());
		assertEquals(MixedLoadStepExtension.TYPE, copy.getTypeName());
	}

	@Test
	@DisplayName("append(Map) returns a new client without modifying original")
	void testAppendReturnsNewClient() {
		final Config cfg = newBaseConfig();
		final MixedLoadStepClient client = new MixedLoadStepClient(
						cfg, Collections.<Extension> emptyList(), null, null);

		final MixedLoadStepClient withCtx = client.append(Map.of("load-op-type", "read"));
		assertNotSame(client, withCtx);
		assertEquals("base-step", client.loadStepId());
		assertEquals("base-step", withCtx.loadStepId());
		assertEquals(MixedLoadStepExtension.TYPE, withCtx.getTypeName());
	}

	@Test
	@DisplayName("config(Map) accepts mixed weights when weighted scalar weight is present")
	void testConfigAcceptsMixedWeightsWithWeightedScalarPresent() {
		final Config cfg = newBaseConfig();
		final MixedLoadStepClient client = new MixedLoadStepClient(
						cfg, Collections.<Extension> emptyList(), null, null);

		final MixedLoadStepClient copy = assertDoesNotThrow(
						() -> client.config(
										Map.of(
														"load",
														Map.of(
																		"op",
																		Map.of(
																						"weights",
																						Map.of(
																										"get", 45,
																										"put", 15,
																										"delete", 10,
																										"stat", 30))))));

		assertDoesNotThrow(copy::init);
	}

	/** Minimal {@link com.dell.spt.base.item.Item} stub for queue tests. */
	@SuppressWarnings("serial")
	private static final class StubItem implements com.dell.spt.base.item.Item {
		private String name;

		StubItem(final String name) {
			this.name = name;
		}

		@Override
		public String name() {
			return name;
		}

		@Override
		public void name(final String n) {
			this.name = n;
		}

		@Override
		public void reset() {}

		@Override
		public String toString(final String itemPath) {
			return name;
		}

		@Override
		public void writeExternal(final java.io.ObjectOutput out) {}

		@Override
		public void readExternal(final java.io.ObjectInput in) {}
	}

	@Test
	@DisplayName("QueueItemInput.skip() returns number of items drained")
	void testQueueItemInputSkip() {
		final java.util.concurrent.LinkedBlockingQueue<StubItem> queue = new java.util.concurrent.LinkedBlockingQueue<>();
		queue.add(new StubItem("a"));
		queue.add(new StubItem("b"));
		queue.add(new StubItem("c"));
		final QueueItemInput<StubItem> input = new QueueItemInput<>(queue);
		assertEquals(2, input.skip(2));
		assertEquals(1, queue.size());
	}

	@Test
	@DisplayName("QueueItemInput.reset() is a no-op and does not throw")
	void testQueueItemInputReset() {
		final QueueItemInput<StubItem> input = new QueueItemInput<>(new java.util.concurrent.LinkedBlockingQueue<>());
		assertDoesNotThrow(input::reset);
	}

	@Test
	@DisplayName("QueueItemInput.close() is a no-op and does not throw")
	void testQueueItemInputClose() {
		final QueueItemInput<StubItem> input = new QueueItemInput<>(new java.util.concurrent.LinkedBlockingQueue<>());
		assertDoesNotThrow(input::close);
	}

	@Test
	@DisplayName("QueueItemInput.get(List, int) returns available items without blocking when queue is non-empty")
	void testQueueItemInputBatchGet() throws Exception {
		final java.util.concurrent.LinkedBlockingQueue<StubItem> queue = new java.util.concurrent.LinkedBlockingQueue<>();
		final StubItem x = new StubItem("x");
		final StubItem y = new StubItem("y");
		queue.add(x);
		queue.add(y);
		final QueueItemInput<StubItem> input = new QueueItemInput<>(queue);

		final List<StubItem> buf = new java.util.ArrayList<>();
		final int count = input.get(buf, 10);
		assertEquals(2, count);
		assertTrue(buf.contains(x));
		assertTrue(buf.contains(y));
	}
}
