package com.dell.spt.base.load.step.linear;

import com.dell.spt.base.env.Extension;
import com.dell.spt.base.item.op.OpType;
import com.dell.spt.base.load.step.client.LoadStepClientBase;
import com.dell.spt.base.logging.LogUtil;
import com.dell.spt.base.metrics.MetricsManager;
import com.dell.spt.base.util.BinarySizeFormat;
import com.github.akurilov.commons.reflection.TypeUtil;
import com.github.akurilov.commons.system.SizeInBytes;
import com.github.akurilov.confuse.Config;

import java.util.List;
import java.util.Locale;

public class LinearLoadStepClient
				extends LoadStepClientBase<LinearLoadStepClient> {

	public LinearLoadStepClient(
					final Config baseConfig, final List<Extension> extensions, final List<Config> contextConfigs,
					final MetricsManager metricsManager) {
		super(baseConfig, extensions, contextConfigs, metricsManager);
	}

	@Override
	protected LinearLoadStepClient copyInstance(final Config config, final List<Config> ctxConfigs) {
		return new LinearLoadStepClient(config, extensions, ctxConfigs, metricsMgr);
	}

	@Override
	protected void init()
					throws IllegalStateException {

		final String autoStepId = "linear_" + LogUtil.getDateTimeStamp();
		if (config.boolVal("load-step-idAutoGenerated")) {
			config.val("load-step-id", autoStepId);
		}
		final OpType opType = OpType.valueOf(config.stringVal("load-op-type").toUpperCase(Locale.ROOT));
		final int concurrencyLimit = config.intVal("storage-driver-limit-concurrency");
		final Config outputConfig = config.configVal("output");
		final Config metricsConfig = outputConfig.configVal("metrics");
		final SizeInBytes itemDataSize;
		final Object itemDataSizeRaw = config.val("item-data-size");
		if (itemDataSizeRaw instanceof String) {
			itemDataSize = BinarySizeFormat.parseSize((String) itemDataSizeRaw);
		} else {
			itemDataSize = new SizeInBytes(TypeUtil.typeConvert(itemDataSizeRaw, long.class));
		}
		final int originIndex = 0;
		final boolean colorFlag = outputConfig.boolVal("color");

		initMetrics(originIndex, opType, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
	}

	@Override
	public String getTypeName() {
		return LinearLoadStepExtension.TYPE;
	}
}
