package com.dell.spt.base.load.step.linear;

import com.dell.spt.base.config.IllegalConfigurationException;
import com.dell.spt.base.data.DataInput;
import com.dell.spt.base.env.Extension;
import com.dell.spt.base.item.Item;
import com.dell.spt.base.item.ItemFactory;
import com.dell.spt.base.item.ItemType;
import com.dell.spt.base.item.op.deletion.StandaloneDeleteSelection;
import com.dell.spt.base.integrity.IntegrityConfig;
import com.dell.spt.base.integrity.IntegrityTerminalException;
import com.dell.spt.base.item.io.IntegrityOperationManifestOutput;
import com.dell.spt.base.item.io.ItemInfoFileOutput;
import com.dell.spt.base.item.io.ItemTimingMetricsFileOutput;
import com.dell.spt.base.item.op.OpType;
import com.dell.spt.base.load.generator.LoadGenerator;
import com.dell.spt.base.load.generator.LoadGeneratorBuilder;
import com.dell.spt.base.load.generator.LoadGeneratorBuilderImpl;
import com.dell.spt.base.load.step.local.LoadStepLocalBase;
import com.dell.spt.base.load.step.local.context.LoadStepContext;
import com.dell.spt.base.load.step.local.context.LoadStepContextImpl;
import com.dell.spt.base.logging.LogUtil;
import com.dell.spt.base.logging.Loggers;
import com.dell.spt.base.metrics.MetricsManager;
import com.dell.spt.base.storage.driver.StorageDriver;
import com.dell.spt.base.util.BinarySizeFormat;
import com.github.akurilov.commons.concurrent.throttle.RateThrottle;
import com.github.akurilov.commons.io.Output;
import com.github.akurilov.commons.reflection.TypeUtil;
import com.github.akurilov.commons.system.SizeInBytes;
import com.github.akurilov.confuse.Config;
import org.apache.logging.log4j.Level;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Locale;

import static com.github.akurilov.commons.lang.Exceptions.throwUnchecked;

public class LinearLoadStepLocal
				extends LoadStepLocalBase {

	public LinearLoadStepLocal(
					final Config baseConfig, final List<Extension> extensions, final List<Config> contexts,
					final MetricsManager metricsManager) {
		super(baseConfig, extensions, contexts, metricsManager);
	}

	@Override
	public String getTypeName() {
		return LinearLoadStepExtension.TYPE;
	}

	@Override
	protected void init() {

		final String autoStepId = "linear_" + LogUtil.getDateTimeStamp();
		if (config.boolVal("load-step-idAutoGenerated")) {
			config.val("load-step-id", autoStepId);
		}

		final Config loadConfig = config.configVal("load");
		final Config opConfig = loadConfig.configVal("op");
		final Config stepConfig = loadConfig.configVal("step");
		final OpType opType = OpType.valueOf(opConfig.stringVal("type").toUpperCase(Locale.ROOT));
		final Config storageConfig = config.configVal("storage");
		final int concurrencyLimit = storageConfig.intVal("driver-limit-concurrency");
		final Config outputConfig = config.configVal("output");
		final Config metricsConfig = outputConfig.configVal("metrics");
		final SizeInBytes itemDataSize;
		final Object itemDataSizeRaw = config.val("item-data-size");
		if (itemDataSizeRaw instanceof String) {
			itemDataSize = BinarySizeFormat.parseSize((String) itemDataSizeRaw);
		} else {
			itemDataSize = new SizeInBytes(TypeUtil.typeConvert(itemDataSizeRaw, long.class));
		}
		final int originIndex = 0;
		final boolean outputColorFlag = outputConfig.boolVal("color");
		initMetrics(originIndex, opType, concurrencyLimit, metricsConfig, itemDataSize, outputColorFlag);

		final Config itemConfig = config.configVal("item");
		StandaloneDeleteSelection.ensureFrozen(loadConfig, itemConfig);
		final Config dataConfig = itemConfig.configVal("data");
		final Config dataInputConfig = dataConfig.configVal("input");
		final Config dataLayerConfig = dataInputConfig.configVal("layer");

		final String testStepId = stepConfig.stringVal("id");

		try {

			final Object dataLayerSizeRaw = dataLayerConfig.val("size");
			final SizeInBytes dataLayerSize;
			if (dataLayerSizeRaw instanceof String) {
				dataLayerSize = BinarySizeFormat.parseSize((String) dataLayerSizeRaw);
			} else {
				dataLayerSize = new SizeInBytes(TypeUtil.typeConvert(dataLayerSizeRaw, int.class));
			}

			final DataInput dataInput = DataInput.instance(
							dataInputConfig.stringVal("file"), dataInputConfig.stringVal("seed"), dataLayerSize,
							dataLayerConfig.intVal("cache"), dataLayerConfig.boolVal("heap"),
							dataInputConfig.doubleVal("compressibility"), dataConfig.boolVal("dedupable"));
			final boolean effectiveVerifyFlag = effectiveVerifyFlag(
							dataConfig.boolVal("verify"), dataConfig.boolVal("dedupable"), testStepId);

			final int batchSize = loadConfig.intVal("batch-size");

			try {

				final StorageDriver driver = StorageDriver.instance(
								extensions, storageConfig, dataInput, effectiveVerifyFlag, batchSize, testStepId);

				final ItemType itemType = ItemType.valueOf(itemConfig.stringVal("type").toUpperCase(Locale.ROOT));
				final ItemFactory<? extends Item> itemFactory = ItemType.getItemFactory(itemType);
				final double rateLimit = opConfig.doubleVal("limit-rate");

				try {
					final LoadGeneratorBuilder generatorBuilder = new LoadGeneratorBuilderImpl<>()
									.itemConfig(itemConfig)
									.loadConfig(loadConfig)
									.itemType(itemType)
									.itemFactory((ItemFactory) itemFactory)
									.loadOperationsOutput(driver)
									.authConfig(storageConfig.configVal("auth"))
									.originIndex(0);
					if (rateLimit > 0) {
						generatorBuilder.addThrottle(new RateThrottle(rateLimit));
					}
					final LoadGenerator generator = generatorBuilder.build();
					final var shardMetrics = generatorBuilder.listShardMetricsRecorder();
					final boolean metadataMode = IntegrityConfig.fromStorage(storageConfig).enabled();
					final String immutableListRootPrefix = metadataMode && OpType.LIST.equals(opType)
									? itemConfig.configVal("naming").stringVal("prefix")
									: null;
					final LoadStepContext stepCtx = new LoadStepContextImpl<>(
									testStepId,
									generator,
									driver,
									metricsContexts.get(0),
									loadConfig,
									outputConfig.boolVal("metrics-trace-persist"),
									shardMetrics,
									immutableListRootPrefix);
					stepContexts.add(stepCtx);

					final String itemOutputFile = itemConfig.stringVal("output-file");
					if (itemOutputFile != null && itemOutputFile.length() > 0) {
						final Path itemOutputPath = Paths.get(itemOutputFile);
						if (Files.exists(itemOutputPath)) {
							Loggers.ERR.warn("Items output file \"{}\" already exists", itemOutputPath);
						}
						try {
							final Output itemOutput;
							if (metadataMode) {
								final String bucketPath = OpType.CREATE.equals(opType)
												? itemConfig.configVal("output").stringVal("path")
												: itemConfig.configVal("input").stringVal("path");
								final String requestedListPrefix = OpType.LIST.equals(opType)
												? itemConfig.configVal("naming").stringVal("prefix")
												: null;
								itemOutput = new IntegrityOperationManifestOutput<>(
												itemOutputPath, bucketPath, opType, requestedListPrefix);
							} else {
								itemOutput = new ItemInfoFileOutput<>(itemOutputPath);
							}
							stepCtx.operationsResultsOutput(itemOutput);
						} catch (final IOException e) {
							if (metadataMode) {
								throw new IntegrityTerminalException(
												IntegrityTerminalException.Category.PUBLICATION,
												testStepId,
												"failed to initialize canonical integrity manifest source",
												e);
							}
							LogUtil.exception(
											Level.ERROR, e,
											"Failed to initialize the item output, the processed items info won't be persisted");
						}
					}

					if (outputConfig.boolVal("metrics-timing-persist")) {
						final Path itemTimingMetricsOutputPath = Paths.get(System.getProperty("java.io.tmpdir"),
										"spt", "timingMetrics_" + config.stringVal("load-step-id"));
						try {
							final Output<? extends Item> itemOutput = new ItemTimingMetricsFileOutput<>(itemTimingMetricsOutputPath);
							stepCtx.operationsMetricsOutput(itemOutput);
						} catch (final IOException e) {
							LogUtil.exception(
											Level.ERROR, e,
											"Failed to initialize the item metrics output, the processed items info won't be persisted");
						}
					}

				} catch (final IllegalConfigurationException e) {
					throw new IllegalStateException("Failed to initialize the load generator", e);
				}
			} catch (final IllegalConfigurationException e) {
				throw new IllegalStateException("Failed to initialize the storage driver", e);
			} catch (final InterruptedException e) {
				throwUnchecked(e);
			}
		} catch (final IOException e) {
			throw new IllegalStateException("Failed to initialize the data input", e);
		}
	}
}
