package com.dell.spt.load.step.pipeline;

import com.dell.spt.base.env.Extension;
import com.github.akurilov.confuse.Config;
import com.github.akurilov.confuse.impl.BasicConfig;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Focused tests for PipelineLoadStepClient keeping dependencies minimal.
 * Covers getTypeName, copy via config/append and init paths including
 * auto-generated IDs and context handling.
 */
class PipelineLoadStepClientTest {

	private static final String PS = "-"; // confuse path separator

	// Minimal schema to resolve the paths accessed by PipelineLoadStepClient and its base
	private static Map<String, Object> minimalSchema() {
		Map<String, Object> schema = new HashMap<>();

		// load
		Map<String, Object> load = new HashMap<>();
		Map<String, Object> step = new HashMap<>();
		step.put("id", String.class);
		step.put("idAutoGenerated", Boolean.class);
		Map<String, Object> stepLimit = new HashMap<>();
		stepLimit.put("time", String.class);
		stepLimit.put("size", String.class);
		step.put("limit", stepLimit);
		Map<String, Object> node = new HashMap<>();
		node.put("addrs", List.class);
		node.put("port", Integer.class);
		step.put("node", node);
		load.put("step", step);

		Map<String, Object> op = new HashMap<>();
		Map<String, Object> opLimit = new HashMap<>();
		opLimit.put("count", Long.class);
		opLimit.put("rate", Double.class);
		Map<String, Object> opLimitFail = new HashMap<>();
		opLimitFail.put("count", Long.class);
		opLimit.put("fail", opLimitFail);
		op.put("limit", opLimit);
		op.put("type", String.class);
		load.put("op", op);

		Map<String, Object> batch = new HashMap<>();
		batch.put("size", Integer.class);
		load.put("batch", batch);

		schema.put("load", load);

		// storage
		Map<String, Object> storage = new HashMap<>();
		Map<String, Object> driver = new HashMap<>();
		Map<String, Object> driverLimit = new HashMap<>();
		driverLimit.put("concurrency", Integer.class);
		driver.put("limit", driverLimit);
		driver.put("type", String.class);
		storage.put("driver", driver);

		Map<String, Object> auth = new HashMap<>();
		auth.put("file", String.class);
		storage.put("auth", auth);

		Map<String, Object> net = new HashMap<>();
		Map<String, Object> netNode = new HashMap<>();
		netNode.put("slice", Boolean.class);
		netNode.put("addrs", List.class);
		net.put("node", netNode);
		storage.put("net", net);
		storage.put("integrity", Map.of(
						"mode", String.class,
						"algorithm", String.class,
						"input", Map.of("provenance", String.class, "expectedProducerId", String.class)));

		schema.put("storage", storage);

		// output
		Map<String, Object> output = new HashMap<>();
		output.put("color", Boolean.class);
		Map<String, Object> metrics = new HashMap<>();
		Map<String, Object> avg = new HashMap<>();
		avg.put("persist", Boolean.class);
		avg.put("period", String.class);
		metrics.put("average", avg);
		Map<String, Object> sum = new HashMap<>();
		sum.put("persist", Boolean.class);
		metrics.put("summary", sum);
		Map<String, Object> timing = new HashMap<>();
		timing.put("persist", Boolean.class);
		metrics.put("timing", timing);
		metrics.put("threshold", Double.class);
		metrics.put("quantiles", List.class);
		output.put("metrics", metrics);
		schema.put("output", output);

		// item
		Map<String, Object> item = new HashMap<>();
		Map<String, Object> data = new HashMap<>();
		data.put("size", String.class);
		Map<String, Object> dataInput = new HashMap<>();
		dataInput.put("file", String.class);
		dataInput.put("seed", String.class);
		Map<String, Object> layer = new HashMap<>();
		layer.put("cache", Integer.class);
		layer.put("heap", Boolean.class);
		layer.put("size", String.class);
		dataInput.put("layer", layer);
		data.put("input", dataInput);
		data.put("verify", Boolean.class);
		item.put("data", data);
		Map<String, Object> itemInput = new HashMap<>();
		itemInput.put("file", String.class);
		itemInput.put("path", String.class);
		item.put("input", itemInput);
		Map<String, Object> itemOutput = new HashMap<>();
		itemOutput.put("file", String.class);
		itemOutput.put("path", String.class);
		item.put("output", itemOutput);
		schema.put("item", item);

		// run + aliasing
		Map<String, Object> run = new HashMap<>();
		run.put("comment", String.class);
		run.put("id", Long.class);
		run.put("version", String.class);
		schema.put("run", run);
		schema.put("aliasing", List.class);

		return schema;
	}

	private static Map<String, Object> baseValues() {
		Map<String, Object> values = new HashMap<>();

		Map<String, Object> load = new HashMap<>();
		Map<String, Object> step = new HashMap<>();
		step.put("id", "base-step");
		step.put("idAutoGenerated", false);
		Map<String, Object> limit = new HashMap<>();
		limit.put("time", "0s");
		limit.put("size", "0B");
		step.put("limit", limit);
		Map<String, Object> node = new HashMap<>();
		node.put("addrs", List.of());
		node.put("port", 9020);
		step.put("node", node);
		load.put("step", step);

		Map<String, Object> op = new HashMap<>();
		Map<String, Object> opLimit = new HashMap<>();
		opLimit.put("count", 0L);
		opLimit.put("rate", 0.0);
		Map<String, Object> opFail = new HashMap<>();
		opFail.put("count", 0L);
		opLimit.put("fail", opFail);
		op.put("limit", opLimit);
		op.put("type", "create");
		load.put("op", op);

		Map<String, Object> batch = new HashMap<>();
		batch.put("size", 1);
		load.put("batch", batch);

		values.put("load", load);

		Map<String, Object> storage = new HashMap<>();
		Map<String, Object> driver = new HashMap<>();
		Map<String, Object> driverLimit = new HashMap<>();
		driverLimit.put("concurrency", 1);
		driver.put("limit", driverLimit);
		driver.put("type", "dummy-mock");
		storage.put("driver", driver);
		Map<String, Object> auth = new HashMap<>();
		auth.put("file", "");
		storage.put("auth", auth);
		Map<String, Object> net = new HashMap<>();
		Map<String, Object> netNode = new HashMap<>();
		netNode.put("slice", false);
		netNode.put("addrs", List.of());
		net.put("node", netNode);
		storage.put("net", net);
		storage.put("integrity", Map.of(
						"mode", "none",
						"algorithm", "sha256",
						"input", Map.of("provenance", "none", "expectedProducerId", "")));
		values.put("storage", storage);

		Map<String, Object> output = new HashMap<>();
		output.put("color", true);
		Map<String, Object> metrics = new HashMap<>();
		Map<String, Object> avg = new HashMap<>();
		avg.put("persist", false);
		avg.put("period", "1s");
		metrics.put("average", avg);
		Map<String, Object> sum = new HashMap<>();
		sum.put("persist", false);
		metrics.put("summary", sum);
		Map<String, Object> timing = new HashMap<>();
		timing.put("persist", false);
		metrics.put("timing", timing);
		metrics.put("threshold", 0.0);
		metrics.put("quantiles", List.of(0.25, 0.5, 0.75));
		output.put("metrics", metrics);
		values.put("output", output);

		Map<String, Object> item = new HashMap<>();
		Map<String, Object> data = new HashMap<>();
		data.put("size", "1MB");
		Map<String, Object> dataInput = new HashMap<>();
		dataInput.put("file", "");
		dataInput.put("seed", "seed");
		Map<String, Object> layer = new HashMap<>();
		layer.put("cache", 16);
		layer.put("heap", false);
		layer.put("size", "4MB");
		dataInput.put("layer", layer);
		data.put("input", dataInput);
		data.put("verify", false);
		item.put("data", data);
		Map<String, Object> itemInput = new HashMap<>();
		itemInput.put("file", "");
		itemInput.put("path", "");
		item.put("input", itemInput);
		Map<String, Object> itemOutput = new HashMap<>();
		itemOutput.put("file", "");
		itemOutput.put("path", "");
		item.put("output", itemOutput);
		values.put("item", item);

		Map<String, Object> run = new HashMap<>();
		run.put("comment", "");
		run.put("id", 0L);
		run.put("version", "test");
		values.put("run", run);

		values.put("aliasing", List.of());

		return values;
	}

	private static Config newBaseConfig() {
		return new BasicConfig(PS, minimalSchema(), baseValues());
	}

	private static Config ctxOverride(Map<String, Object> overrides) {
		return new BasicConfig(PS, minimalSchema(), overrides);
	}

	@Test
	@DisplayName("getTypeName returns PipelineLoad")
	void testGetTypeName() throws Exception {
		Config cfg = newBaseConfig();
		PipelineLoadStepClient client = new PipelineLoadStepClient(cfg, Collections.<Extension> emptyList(), Collections.emptyList(), null);
		assertEquals(PipelineLoadStepExtension.TYPE, client.getTypeName());
	}

	@Test
	@DisplayName("config(Map) returns new Pipeline client with updated config")
	void testCopyViaConfig() throws Exception {
		Config cfg = newBaseConfig();
		PipelineLoadStepClient client = new PipelineLoadStepClient(cfg, Collections.<Extension> emptyList(), null, null);

		PipelineLoadStepClient copy = client.config(Map.of("load-step-id", "pipeline-copy"));

		assertNotSame(client, copy);
		assertEquals("pipeline-copy", copy.loadStepId());
		assertEquals("base-step", client.loadStepId());
		assertEquals(PipelineLoadStepExtension.TYPE, copy.getTypeName());
	}

	@Test
	@DisplayName("append(Map) returns new client and preserves base values")
	void testAppendReturnsNewClient() throws Exception {
		Config cfg = newBaseConfig();
		PipelineLoadStepClient client = new PipelineLoadStepClient(cfg, Collections.<Extension> emptyList(), null, null);

		PipelineLoadStepClient withCtx = client.append(Map.of("load-op-type", "read"));
		assertNotSame(client, withCtx);
		assertEquals("base-step", client.loadStepId());
		assertEquals("base-step", withCtx.loadStepId());
		assertEquals(PipelineLoadStepExtension.TYPE, withCtx.getTypeName());
	}

	// @Test
	// @DisplayName("init sets auto step ID when idAutoGenerated")
	// void testInitAutoId() {
	//     Config cfg = newBaseConfig();
	//     cfg.val("load-step-idAutoGenerated", true);
	//     cfg.val("load-step-id", "");

	//     PipelineLoadStepClient client = new PipelineLoadStepClient(cfg, Collections.<Extension>emptyList(), Collections.emptyList(), null);
	//     assertDoesNotThrow(client::init);
	//     String newId = cfg.stringVal("load-step-id");
	//     assertNotNull(newId);
	//     assertTrue(newId.startsWith("pipeline_"));
	// }

	@Test
	@DisplayName("init uses base item-data-size and does not override step id from contexts")
	void testInitWithContextsAndItemDataSizeVariants() {
		// Base config: numeric item-data-size via item.data.size path (accessed as item-data-size)
		Config baseNumeric = newBaseConfig();
		baseNumeric.val("item-data-size", 2048L);

		// Contexts provide their own step IDs; Pipeline client should NOT replace base step ID
		Map<String, Object> ctx0 = new HashMap<>();
		Map<String, Object> load0 = new HashMap<>();
		Map<String, Object> step0 = new HashMap<>();
		step0.put("id", "ctx-0");
		load0.put("step", step0);
		ctx0.put("load", load0);

		Map<String, Object> ctx1 = new HashMap<>();
		Map<String, Object> load1 = new HashMap<>();
		Map<String, Object> step1 = new HashMap<>();
		step1.put("id", "ctx-1");
		load1.put("step", step1);
		ctx1.put("load", load1);

		List<Config> ctxConfigs = List.of(ctxOverride(ctx0), ctxOverride(ctx1));

		PipelineLoadStepClient clientNumeric = new PipelineLoadStepClient(baseNumeric, Collections.<Extension> emptyList(), ctxConfigs, null);

		assertDoesNotThrow(clientNumeric::init);
		assertEquals("base-step", baseNumeric.stringVal("load-step-id"));

		// Base config: string item-data-size
		Config baseString = newBaseConfig();
		baseString.val("item-data-size", "3MB");
		PipelineLoadStepClient clientString = new PipelineLoadStepClient(baseString, Collections.<Extension> emptyList(), ctxConfigs, null);

		assertDoesNotThrow(clientString::init);
		assertEquals("base-step", baseString.stringVal("load-step-id"));
	}
}
