package scenario

import (
	"fmt"
	"strings"
)

// GenerateWriteVerifyScenario composes CREATE, one finite verification READ, and optional verified-only cleanup.
func GenerateWriteVerifyScenario(params Params) (string, error) {
	if params.RunID <= 0 {
		return "", fmt.Errorf("write-verify requires a positive run id")
	}
	ts := resolveTimestamp(params)
	createID := formatStepID(1, ts, stepOpCreate)
	readID := formatStepID(2, ts, "verify")
	deleteID := formatStepID(3, ts, stepOpDelete)
	bucketPath := "/" + strings.TrimPrefix(params.Bucket, "/")
	count := params.ObjectCount
	if count <= 0 && strings.TrimSpace(params.Duration) == "" {
		count = 1000
	}
	createLimit := fmt.Sprintf("\"limit\": {\"count\": %d}", count)
	stepLimit := ""
	if count <= 0 {
		createLimit = "\"limit\": {\"count\": 0}"
		stepLimit = fmt.Sprintf(", \"limit\": {\"time\": %s}", quoteJS(params.Duration))
	}
	partRange := ""
	if params.PartSize != "" {
		partRange = fmt.Sprintf(",\n        \"ranges\": {\"threshold\": %s}", quoteJS(params.PartSize))
	}
	cleanup := ""
	if params.Cleanup {
		cleanup = fmt.Sprintf(`
DeleteLoad.config({
  "storage": {"integrity": {"mode": "metadata", "algorithm": "sha256", "input": {"provenance": "engine_step", "expectedProducerId": %s}}},
  "item": {"type": "data", "input": {"file": verifiedFile}},
  "load": {"op": {"type": "delete"}, "step": {"id": %s}},
  "output": {"metrics": {"summary": {"persist": true}}}
}).run();
`, quoteJS(readID), quoteJS(deleteID))
	}
	return fmt.Sprintf(`// Generated by spt
// Persisted-data write-then-read verification workload
var homeDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
var createStep = %s;
var readStep = %s;
var writtenFile = homeDir + "/log/" + createStep + "/written.csv";
var verifiedFile = homeDir + "/log/" + readStep + "/verified.csv";

CreateLoad.config({
  "storage": {
    "driver": {"type": %s, "limit": {"concurrency": %d}},
    "integrity": {"mode": "metadata", "algorithm": "sha256", "input": {"provenance": "none", "expectedProducerId": ""}}
  },
  "item": {
    "type": "data",
    "data": {"size": %s%s},
    "output": {"path": %s, "file": writtenFile}
  },
  "load": {"op": {"type": "create", %s}, "step": {"id": %s%s}},
  "output": {"metrics": {"summary": {"persist": true}}}
}).run();

ReadLoad.config({
  "storage": {
    "driver": {"type": %s, "limit": {"concurrency": %d}},
    "integrity": {"mode": "metadata", "algorithm": "sha256", "input": {"provenance": "engine_step", "expectedProducerId": createStep}}
  },
  "item": {"type": "data", "input": {"file": writtenFile}, "output": {"file": verifiedFile}},
  "load": {"op": {"type": "read", "limit": {"fail": {"count": 0}}, "wait": {"finish": true}}, "step": {"id": %s}},
  "output": {"metrics": {"summary": {"persist": true}}}
}).run();
%s`,
		quoteJS(createID), quoteJS(readID), quoteJS(resolveStorageDriverType(params.S3Driver)), params.Threads,
		quoteJS(params.ObjectSize), partRange, quoteJS(bucketPath), createLimit, quoteJS(createID), stepLimit,
		quoteJS(resolveStorageDriverType(params.S3Driver)), params.Threads, quoteJS(readID), cleanup), nil
}

// GenerateReadVerifyScenario composes LIST discovery (or trusted staged input) and one finite verification READ.
func GenerateReadVerifyScenario(params Params) (string, error) {
	if params.RunID <= 0 {
		return "", fmt.Errorf("read-verify requires a positive run id")
	}
	ts := resolveTimestamp(params)
	driver := quoteJS(resolveStorageDriverType(params.S3Driver))
	bucketPath := "/" + strings.TrimPrefix(params.Bucket, "/")
	readNumber := 2
	producerID := formatStepID(1, ts, listStepSuffix)
	inputFileExpr := "verifyInputFile"
	prelude := ""
	provenance := "engine_step"
	if params.ItemsFile != "" {
		readNumber = 1
		producerID = "spt-cli-items-stager-v1"
		inputFileExpr = quoteJS(params.ItemsFile)
		provenance = "cli_stager"
	} else {
		listID := producerID
		prefix := ""
		if params.Prefix != "" {
			prefix = fmt.Sprintf(", \"prefix\": %s", quoteJS(params.Prefix))
		}
		prelude = fmt.Sprintf(`var listStep = %s;
var verifyInputFile = homeDir + "/log/" + listStep + "/verify-input.csv";
Load.config({
  "storage": {
    "driver": {"type": %s, "limit": {"concurrency": %d}},
    "integrity": {
      "mode": "metadata", "algorithm": "sha256",
      "input": {"provenance": "none", "expectedProducerId": ""},
      "selection": {"maxCount": %d}
    }
  },
  "item": {
    "type": "path",
    "input": {"path": %s},
    "naming": {"type": "random", "radix": 36%s},
    "output": {"file": verifyInputFile}
  },
  "load": {
    "batch": {"size": 1000},
    "op": {"type": "list", "list": {"delimiter": "", "fetch_metadata": true, "include_versions": false, "max_keys": 1000}, "limit": {"rate": 0}, "wait": {"finish": true}},
    "step": {"id": %s}
  },
  "output": {"metrics": {"summary": {"persist": true}}}
}).run();
`, quoteJS(listID), driver, params.Threads, params.ObjectCount, quoteJS(bucketPath), prefix, quoteJS(listID))
	}
	readID := formatStepID(readNumber, ts, "verify")
	return fmt.Sprintf(`// Generated by spt
// Independent persisted-data verification workload
var homeDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
%s
var readStep = %s;
var verifiedFile = homeDir + "/log/" + readStep + "/verified.csv";
ReadLoad.config({
  "storage": {
    "driver": {"type": %s, "limit": {"concurrency": %d}},
    "integrity": {"mode": "metadata", "algorithm": "sha256", "input": {"provenance": %s, "expectedProducerId": %s}}
  },
  "item": {"type": "data", "input": {"file": %s}, "output": {"file": verifiedFile}},
  "load": {"op": {"type": "read", "limit": {"fail": {"count": 0}}, "wait": {"finish": true}}, "step": {"id": %s}},
  "output": {"metrics": {"summary": {"persist": true}}}
}).run();
`, prelude, quoteJS(readID), driver, params.Threads, quoteJS(provenance), quoteJS(producerID), inputFileExpr, quoteJS(readID)), nil
}

func quoteJS(value string) string {
	return fmt.Sprintf("\"%s\"", escapeJSONString(value))
}
