package scenario

import (
	"bytes"
	"fmt"
	"text/template"
)

type integrityTemplateData struct {
	Provenance         string
	ExpectedProducerID string
	MaxCount           *int
}

type integrityStorageTemplateData struct {
	Driver      string
	Concurrency int
	Integrity   integrityTemplateData
}

type writeVerifyScenarioData struct {
	CreateStep       string
	ReadStep         string
	DeleteStep       string
	CreateStorage    integrityStorageTemplateData
	ReadStorage      integrityStorageTemplateData
	DeleteStorage    integrityStorageTemplateData
	BucketPath       string
	ObjectSize       string
	PartSize         string
	NamingPrefix     string
	CreateLimitCount int
	CreateDuration   string
	Cleanup          bool
}

type readVerifyScenarioData struct {
	Discovery   bool
	ListStep    string
	ReadStep    string
	ListStorage integrityStorageTemplateData
	ReadStorage integrityStorageTemplateData
	BucketPath  string
	Prefix      string
	ItemsFile   string
}

var integrityScenarioTemplates = template.Must(
	template.New("integrity-scenarios").
		Option("missingkey=error").
		Funcs(template.FuncMap{
			"jsq":                quoteJS,
			"integrityMode":      func() string { return integrityModeMetadata },
			"integrityAlgorithm": func() string { return ChecksumSHA256 },
		}).
		Parse(`{{define "integrity"}}
"integrity": {
      "mode": {{jsq integrityMode}}, "algorithm": {{jsq integrityAlgorithm}},
      "input": {"provenance": {{jsq .Provenance}}, "expectedProducerId": {{jsq .ExpectedProducerID}}}{{if .MaxCount}},
      "selection": {"maxCount": {{.MaxCount}}}{{end}}
    }{{end}}
{{define "storage"}}
"storage": {
    "driver": {"type": {{jsq .Driver}}, "limit": {"concurrency": {{.Concurrency}}}},
    {{template "integrity" .Integrity}}
  }{{end}}
{{define "summary"}}
"output": {"metrics": {"summary": {"persist": true}}}{{end}}
{{define "write-verify"}}// Generated by spt
// Persisted-data write-then-read verification workload
var homeDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
var createStep = {{jsq .CreateStep}};
var readStep = {{jsq .ReadStep}};
var writtenFile = homeDir + "/log/" + createStep + "/written.csv";
var verifiedFile = homeDir + "/log/" + readStep + "/verified.csv";

CreateLoad.config({
  {{template "storage" .CreateStorage}},
  "item": {
    "type": "data",
    "data": {"size": {{jsq .ObjectSize}}{{if .PartSize}},
        "ranges": {"threshold": {{jsq .PartSize}}}{{end}}}{{if .NamingPrefix}},
    "naming": {"prefix": {{jsq .NamingPrefix}}}{{end}},
    "output": {"path": {{jsq .BucketPath}}, "file": writtenFile}
  },
  "load": {
    "op": {"type": "create", "limit": {"count": {{.CreateLimitCount}}}},
    "step": {"id": {{jsq .CreateStep}}{{if .CreateDuration}}, "limit": {"time": {{jsq .CreateDuration}}}{{end}}}
  },
  {{template "summary"}}
}).run();

ReadLoad.config({
  {{template "storage" .ReadStorage}},
  "item": {"type": "data", "input": {"file": writtenFile}, "output": {"file": verifiedFile}},
  "load": {"op": {"type": "read", "limit": {"fail": {"count": 0}}, "wait": {"finish": true}}, "step": {"id": {{jsq .ReadStep}}}},
  {{template "summary"}}
}).run();
{{if .Cleanup}}
DeleteLoad.config({
  {{template "storage" .DeleteStorage}},
  "item": {"type": "data", "input": {"file": verifiedFile}},
  "load": {"op": {"type": "delete"}, "step": {"id": {{jsq .DeleteStep}}}},
  {{template "summary"}}
}).run();
{{end}}{{end}}
{{define "read-verify"}}// Generated by spt
// Independent persisted-data verification workload
var homeDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
{{if .Discovery}}var listStep = {{jsq .ListStep}};
var verifyInputFile = homeDir + "/log/" + listStep + "/verify-input.csv";
Load.config({
  {{template "storage" .ListStorage}},
  "item": {
    "type": "path",
    "input": {"path": {{jsq .BucketPath}}},
    "naming": {"type": "random", "radix": 36{{if .Prefix}}, "prefix": {{jsq .Prefix}}{{end}}},
    "output": {"file": verifyInputFile}
  },
  "load": {
    "batch": {"size": 1000},
    "op": {"type": "list", "list": {"delimiter": "", "fetch_metadata": true, "include_versions": false, "max_keys": 1000}, "limit": {"rate": 0}, "wait": {"finish": true}},
    "step": {"id": {{jsq .ListStep}}}
  },
  {{template "summary"}}
}).run();
{{end}}
var readStep = {{jsq .ReadStep}};
var verifiedFile = homeDir + "/log/" + readStep + "/verified.csv";
ReadLoad.config({
  {{template "storage" .ReadStorage}},
  "item": {"type": "data", "input": {"file": {{if .Discovery}}verifyInputFile{{else}}{{jsq .ItemsFile}}{{end}}}, "output": {"file": verifiedFile}},
  "load": {"op": {"type": "read", "limit": {"fail": {"count": 0}}, "wait": {"finish": true}}, "step": {"id": {{jsq .ReadStep}}}},
  {{template "summary"}}
}).run();
{{end}}`),
)

func executeIntegrityScenario(templateName string, data any) (string, error) {
	var output bytes.Buffer
	if err := integrityScenarioTemplates.ExecuteTemplate(&output, templateName, data); err != nil {
		return "", fmt.Errorf("render %s scenario: %w", templateName, err)
	}
	return output.String(), nil
}
