package scenario

import (
	"bytes"
	"fmt"
	"text/template"
)

type integrityTemplateData struct {
	Provenance              string
	ExpectedProducerID      string
	RequireExactOutputCount bool
	MaxCount                *int
	RequireNonEmpty         bool
}

type integrityStorageTemplateData struct {
	Driver      string
	Concurrency int
	Integrity   integrityTemplateData
}

type writeVerifyScenarioData struct {
	CreateStep       string
	ReadStep         string
	DeleteStep       string
	CreateStorage    integrityStorageTemplateData
	ReadStorage      integrityStorageTemplateData
	DeleteStorage    integrityStorageTemplateData
	BucketPath       string
	ObjectSize       string
	PartSize         string
	NamingPrefix     string
	CreateLimitCount int
	CreateDuration   string
	Cleanup          bool
	Deferred         bool
}

type readVerifyScenarioData struct {
	Discovery       bool
	ListStep        string
	ReadStep        string
	ListStorage     integrityStorageTemplateData
	ReadStorage     integrityStorageTemplateData
	BucketPath      string
	Prefix          string
	ItemsFile       string
	IncludeVersions bool
}

type deleteManifestScenarioData struct {
	DeleteStep     string
	DeleteStorage  integrityStorageTemplateData
	ItemsFile      string
	BatchSize      int
	SelectionOrder string
	Duration       string
	FailureBudget  deleteFailureBudgetTemplateData
	Verification   deleteVerificationTemplateData
}

type deleteSeededScenarioData struct {
	SeedStep       string
	DeleteStep     string
	SeedStorage    integrityStorageTemplateData
	DeleteStorage  integrityStorageTemplateData
	BucketPath     string
	ObjectSize     string
	Namespace      string
	SeedCount      int
	BatchSize      int
	SelectionOrder string
	Duration       string
	FailureBudget  deleteFailureBudgetTemplateData
	Verification   deleteVerificationTemplateData
}

type deleteExistingScenarioData struct {
	ListStep       string
	DeleteStep     string
	ListStorage    integrityStorageTemplateData
	DeleteStorage  integrityStorageTemplateData
	BucketPath     string
	Prefix         string
	ListBatchSize  int
	BatchSize      int
	SelectionOrder string
	Duration       string
	FailureBudget  deleteFailureBudgetTemplateData
	Verification   deleteVerificationTemplateData
}

type deleteFailureBudgetTemplateData struct {
	Mode              string
	MaxFailedObjects  int64
	MaxFailurePercent float64
	GraceSeconds      int64
}

type deleteVerificationTemplateData struct {
	PreValidation             bool
	PostVerification          bool
	VerificationTimeoutMillis int64
}

var integrityScenarioTemplates = template.Must(
	template.New("integrity-scenarios").
		Option("missingkey=error").
		Funcs(template.FuncMap{
			"jsq":                quoteJS,
			"integrityMode":      func() string { return integrityModeMetadata },
			"integrityAlgorithm": func() string { return ChecksumSHA256 },
		}).
		Parse(`{{define "integrity"}}
"integrity": {
      "mode": {{jsq integrityMode}}, "algorithm": {{jsq integrityAlgorithm}},
      "input": {"provenance": {{jsq .Provenance}}, "expectedProducerId": {{jsq .ExpectedProducerID}}}{{if .RequireExactOutputCount}},
      "output": {"requireExactCount": true}{{end}}{{if .MaxCount}},
      "selection": {"maxCount": {{.MaxCount}}{{if .RequireNonEmpty}}, "requireNonEmpty": true{{end}}}{{end}}
    }{{end}}
{{define "storage"}}
"storage": {
    "driver": {"type": {{jsq .Driver}}, "limit": {"concurrency": {{.Concurrency}}}},
    {{template "integrity" .Integrity}}
  }{{end}}
{{define "summary"}}
"output": {"metrics": {"summary": {"persist": true}}}{{end}}
{{define "failure-budget"}}"failureBudget": {"mode": {{jsq .Mode}}, "maxFailedObjects": {{.MaxFailedObjects}}, "maxFailurePercent": {{.MaxFailurePercent}}, "graceSeconds": {{.GraceSeconds}}}{{end}}
{{define "delete-verification"}}{{if or .PreValidation .PostVerification}}, "preValidation": {{.PreValidation}}, "postVerification": {{.PostVerification}}, "verificationTimeoutMillis": {{.VerificationTimeoutMillis}}{{end}}{{end}}
{{define "write-verify"}}// Generated by spt
// Persisted-data write verification workload
var homeDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
var createStep = {{jsq .CreateStep}};
var writtenFile = homeDir + "/log/" + createStep + "/written.csv";
{{if not .Deferred}}var readStep = {{jsq .ReadStep}};
var verifiedFile = homeDir + "/log/" + readStep + "/verified.csv";
{{end}}
CreateLoad.config({
  {{template "storage" .CreateStorage}},
  "item": {
    "type": "data",
    "data": {"size": {{jsq .ObjectSize}}{{if .PartSize}},
        "ranges": {"threshold": {{jsq .PartSize}}}{{end}}}{{if .NamingPrefix}},
    "naming": {"prefix": {{jsq .NamingPrefix}}}{{end}},
    "output": {"path": {{jsq .BucketPath}}, "file": writtenFile}
  },
  "load": {
    "op": {"type": "create", "limit": {"count": {{.CreateLimitCount}}}},
    "step": {"id": {{jsq .CreateStep}}{{if .CreateDuration}}, "limit": {"time": {{jsq .CreateDuration}}}{{end}}}
  },
  {{template "summary"}}
}).run();
{{if not .Deferred}}
ReadLoad.config({
  {{template "storage" .ReadStorage}},
  "item": {"type": "data", "input": {"file": writtenFile}, "output": {"file": verifiedFile}},
  "load": {"op": {"type": "read", "limit": {"fail": {"count": 0}}, "wait": {"finish": true}}, "step": {"id": {{jsq .ReadStep}}}},
  {{template "summary"}}
}).run();
{{if .Cleanup}}
DeleteLoad.config({
  {{template "storage" .DeleteStorage}},
  "item": {"type": "data", "input": {"file": verifiedFile}},
  "load": {"op": {"type": "delete"}, "step": {"id": {{jsq .DeleteStep}}}},
  {{template "summary"}}
}).run();
{{end}}
{{end}}{{end}}
{{define "read-verify"}}// Generated by spt
// Independent persisted-data verification workload
var homeDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
{{if .Discovery}}var listStep = {{jsq .ListStep}};
var verifyInputFile = homeDir + "/log/" + listStep + "/verify-input.csv";
Load.config({
  {{template "storage" .ListStorage}},
  "item": {
    "type": "path",
    "input": {"path": {{jsq .BucketPath}}},
    "naming": {"type": "random", "radix": 36{{if .Prefix}}, "prefix": {{jsq .Prefix}}{{end}}},
    "output": {"file": verifyInputFile}
  },
  "load": {
    "batch": {"size": 1000},
    "op": {"type": "list", "list": {"delimiter": "", "fetch_metadata": true, "include_versions": {{.IncludeVersions}}, "max_keys": 1000}, "limit": {"rate": 0}, "wait": {"finish": true}},
    "step": {"id": {{jsq .ListStep}}}
  },
  {{template "summary"}}
}).run();
{{end}}
var readStep = {{jsq .ReadStep}};
var verifiedFile = homeDir + "/log/" + readStep + "/verified.csv";
ReadLoad.config({
  {{template "storage" .ReadStorage}},
  "item": {"type": "data", "input": {"file": {{if .Discovery}}verifyInputFile{{else}}{{jsq .ItemsFile}}{{end}}}, "output": {"file": verifiedFile}},
  "load": {"op": {"type": "read", "limit": {"fail": {"count": 0}}, "wait": {"finish": true}}, "step": {"id": {{jsq .ReadStep}}}},
  {{template "summary"}}
}).run();
{{end}}
{{define "delete-manifest"}}// Generated by spt
// Standalone DELETE explicit-manifest workload
// selection_order={{.SelectionOrder}}; canonical order can affect cross-tool comparisons
var setupStartedNanos = com.dell.spt.base.load.step.DurationTime.monotonicEpochNanos();
var deleteSelection = com.dell.spt.base.item.op.deletion.StandaloneDeleteSelection.fromManifest({{jsq .ItemsFile}});
DeleteLoad.config({
  {{template "storage" .DeleteStorage}},
  "item": {"type": "data", "input": {"file": {{jsq .ItemsFile}}}},
  "load": {
    "batch": {"size": {{.BatchSize}}},
    "op": {
      "type": "delete",
      "delete": {"standalone": true, "batchSize": {{.BatchSize}}, "duration": {{if .Duration}}true{{else}}false{{end}}, "selectionOrder": {{jsq .SelectionOrder}}, "selected": deleteSelection.selected(), "selectedCurrentKey": deleteSelection.selectedCurrentKey(), "selectedExactVersion": deleteSelection.selectedExactVersion(), "selectedBuckets": deleteSelection.selectedBuckets(), "workflowStartedEpochNanos": setupStartedNanos{{template "delete-verification" .Verification}}},
      {{template "failure-budget" .FailureBudget}},
      "recycle": {"mode": false},
      "retry": false,
      "wait": {"finish": true}
    },
    "step": {"id": {{jsq .DeleteStep}}{{if .Duration}}, "limit": {"time": {{jsq .Duration}}}{{end}}}
  },
  {{template "summary"}}
}).run();
{{end}}
{{define "delete-seeded"}}// Generated by spt
// Standalone DELETE seeded finite-count workload
// selection_order={{.SelectionOrder}}; canonical order can affect cross-tool comparisons
var homeDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
var seedStep = {{jsq .SeedStep}};
var writtenFile = homeDir + "/log/" + seedStep + "/written.csv";
var setupStartedNanos = com.dell.spt.base.load.step.DurationTime.monotonicEpochNanos();
var seedStartedNanos = java.lang.System.nanoTime();
CreateLoad.config({
  {{template "storage" .SeedStorage}},
  "item": {
    "type": "data",
    "data": {"size": {{jsq .ObjectSize}}},
    "naming": {"prefix": {{jsq .Namespace}}},
    "output": {"path": {{jsq .BucketPath}}, "file": writtenFile}
  },
  "load": {
    "op": {"type": "create", "limit": {"count": {{.SeedCount}}}},
    "step": {"id": {{jsq .SeedStep}}}
  },
  {{template "summary"}}
}).run();
var seedDurationMillis = java.util.concurrent.TimeUnit.NANOSECONDS.toMillis(java.lang.System.nanoTime() - seedStartedNanos);
var deleteSelection = com.dell.spt.base.item.op.deletion.StandaloneDeleteSelection.fromManifest(writtenFile);
DeleteLoad.config({
  {{template "storage" .DeleteStorage}},
  "item": {"type": "data", "input": {"file": writtenFile}},
  "load": {
    "batch": {"size": {{.BatchSize}}},
    "op": {
      "type": "delete",
      "delete": {"standalone": true, "batchSize": {{.BatchSize}}, "duration": {{if .Duration}}true{{else}}false{{end}}, "selectionOrder": {{jsq .SelectionOrder}}, "selected": deleteSelection.selected(), "selectedCurrentKey": deleteSelection.selectedCurrentKey(), "selectedExactVersion": deleteSelection.selectedExactVersion(), "selectedBuckets": deleteSelection.selectedBuckets(), "seedMillis": seedDurationMillis, "workflowStartedEpochNanos": setupStartedNanos{{template "delete-verification" .Verification}}},
      {{template "failure-budget" .FailureBudget}},
      "recycle": {"mode": false},
      "retry": false,
      "wait": {"finish": true}
    },
    "step": {"id": {{jsq .DeleteStep}}{{if .Duration}}, "limit": {"time": {{jsq .Duration}}}{{end}}}
  },
  {{template "summary"}}
}).run();
{{end}}
{{define "delete-existing"}}// Generated by spt
// Guarded standalone DELETE existing-prefix finite-count workload
// Discovery is setup and excluded from DELETE request timing.
// selection_order={{.SelectionOrder}}; canonical order can affect cross-tool comparisons
var homeDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
var listStep = {{jsq .ListStep}};
var verifyInputFile = homeDir + "/log/" + listStep + "/verify-input.csv";
var setupStartedNanos = com.dell.spt.base.load.step.DurationTime.monotonicEpochNanos();
var discoveryStartedNanos = java.lang.System.nanoTime();
Load.config({
  {{template "storage" .ListStorage}},
  "item": {
    "type": "path",
    "input": {"file": "", "path": {{jsq .BucketPath}}},
    "naming": {"type": "random", "radix": 36, "prefix": {{jsq .Prefix}}},
    "output": {"file": verifyInputFile}
  },
  "load": {
    "batch": {"size": {{.ListBatchSize}}},
    "op": {"type": "list", "list": {"delimiter": "", "fetch_metadata": true, "include_versions": false, "max_keys": {{.ListBatchSize}}}, "limit": {"count": 0, "rate": 0}, "wait": {"finish": true}},
    "step": {"id": {{jsq .ListStep}}, "limit": {"size": 0, "time": 0}}
  },
  {{template "summary"}}
}).run();
var discoveryDurationMillis = java.util.concurrent.TimeUnit.NANOSECONDS.toMillis(java.lang.System.nanoTime() - discoveryStartedNanos);
var deleteSelection = com.dell.spt.base.item.op.deletion.StandaloneDeleteSelection.fromManifest(verifyInputFile);
DeleteLoad.config({
  {{template "storage" .DeleteStorage}},
  "item": {"type": "data", "input": {"file": verifyInputFile}},
  "load": {
    "batch": {"size": {{.BatchSize}}},
    "op": {
      "type": "delete",
      "delete": {"standalone": true, "batchSize": {{.BatchSize}}, "duration": {{if .Duration}}true{{else}}false{{end}}, "selectionOrder": {{jsq .SelectionOrder}}, "selected": deleteSelection.selected(), "selectedCurrentKey": deleteSelection.selectedCurrentKey(), "selectedExactVersion": deleteSelection.selectedExactVersion(), "selectedBuckets": deleteSelection.selectedBuckets(), "discoveryMillis": discoveryDurationMillis, "workflowStartedEpochNanos": setupStartedNanos{{template "delete-verification" .Verification}}},
      {{template "failure-budget" .FailureBudget}},
      "recycle": {"mode": false},
      "retry": false,
      "wait": {"finish": true}
    },
    "step": {"id": {{jsq .DeleteStep}}{{if .Duration}}, "limit": {"time": {{jsq .Duration}}}{{end}}}
  },
  {{template "summary"}}
}).run();
{{end}}`),
)

func executeIntegrityScenario(templateName string, data any) (string, error) {
	var output bytes.Buffer
	if err := integrityScenarioTemplates.ExecuteTemplate(&output, templateName, data); err != nil {
		return "", fmt.Errorf("render %s scenario: %w", templateName, err)
	}
	return output.String(), nil
}
