package scenario

import (
	"bytes"
	"fmt"
	"text/template"
)

// mixedWorkloadTemplate generates a mixed-workload scenario with seed, benchmark, and optional cleanup.
const mixedWorkloadTemplate = `// Generated by spt
// Mixed workload: concurrent GET/PUT/DELETE with weighted distribution
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Duration: {{.Duration}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var duration = {{.Duration}};
var outputPath = {{.OutputPath}};
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
{{- if .HasSeedPhase}}
var seedCount = {{.SeedCount}};
var itemsFile = sptLogDir + "/log/" + "{{.StepIDSeed}}" + "/items.csv";
{{- else}}
var itemsFile = {{.ReadItemsFile}};
{{- end}}
var putRemainingFile = sptLogDir + "/log/" + "{{.StepIDMixed}}" + "/put-remaining.csv";
var pauseTime = 10; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    }
};
{{if .HasSeedPhase}}
// Phase 1: Seed (PreconditionLoad - metrics suppressed)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting seed phase - " + seedCount + " objects");
PreconditionLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": seedCount
                }
            },
            "step": {
                "id": "{{.StepIDSeed}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Seed phase completed");
{{end}}
// Phase {{.MixedPhaseNumber}}: Mixed benchmark (MixedLoad - metrics collected)
pause(pauseTime, "Starting mixed workload - duration: " + duration);
print("[" + new Date().toISOString() + "] Mixed benchmark started");
MixedLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
            "step": {
                "limit": {
                    "time": duration
                },
                "id": "{{.StepIDMixed}}"
            },
            "op": {
                "weight": {
                    {{- if .HasGetDistrib}}
                    "get": {{.GetDistrib}},
                    {{- end}}
                    {{- if .HasPutDistrib}}
                    "put": {{.PutDistrib}},
                    {{- end}}
                    {{- if .HasDeleteDistrib}}
                    "delete": {{.DeleteDistrib}},
                    {{- end}}
                    {{- if .HasStatDistrib}}
                    "stat": {{.StatDistrib}}
                    {{- end}}
                }
            }
        }
    }){{if .HasDeleteItemsFile}}
    .config({
        "load": {
            "op": {
                "delete": {
                    "input": {
                        "file": {{.DeleteItemsFile}}
                    }
                }
            }
        }
    }){{end}}
    .run();
print("[" + new Date().toISOString() + "] Mixed benchmark completed");
{{if .Cleanup}}
// Phase {{.CleanupSeedPhaseNumber}}: Cleanup seed objects
pause(pauseTime, "Pausing before cleanup...");
print("[" + new Date().toISOString() + "] Cleaning up seed objects");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDSeedCleanup}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Seed cleanup completed");

// Phase {{.CleanupPutPhaseNumber}}: Cleanup PUT-created remaining objects
print("[" + new Date().toISOString() + "] Cleaning up PUT-created objects");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": putRemainingFile
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDPutCleanup}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] PUT cleanup completed");
{{end}}
`

// GenerateMixedScenario creates a mixed-workload benchmark scenario.
// The scenario runs a seed phase (unless ReadItemsFile is provided), a mixed
// benchmark phase (MixedLoad), and optional cleanup phases.
func GenerateMixedScenario(params Params) (string, error) {
	bucketPath := "/" + params.Bucket

	ts := resolveTimestamp(params)
	driverType := resolveStorageDriverType(params.S3Driver)

	seedCount := params.SeedCount
	if seedCount <= 0 {
		seedCount = MixedDefaultSeedCount
	}

	hasSeedPhase := params.ReadItemsFile == ""

	// Number steps starting from 1, skipping seed step if not present
	var (
		seedStepNum        = 1
		mixedStepNum       int
		cleanupSeedStepNum int
		cleanupPutStepNum  int
	)
	if hasSeedPhase {
		mixedStepNum = 2
		cleanupSeedStepNum = 3
		cleanupPutStepNum = 4
	} else {
		mixedStepNum = 1
		cleanupSeedStepNum = 2
		cleanupPutStepNum = 3
	}

	stepIDSeed := formatStepID(seedStepNum, ts, stepOpSeed)
	stepIDMixed := formatStepID(mixedStepNum, ts, stepOpMixed)
	stepIDSeedCleanup := formatStepID(cleanupSeedStepNum, ts, "cleanup-seed")
	stepIDPutCleanup := formatStepID(cleanupPutStepNum, ts, "cleanup-put")

	data := map[string]interface{}{
		templateKeyConcurrency:       params.Threads,
		templateKeyItemSize:          fmt.Sprintf(`"%s"`, escapeJSONString(params.ObjectSize)),
		templateKeyDuration:          fmt.Sprintf(`"%s"`, escapeJSONString(params.Duration)),
		templateKeyOutputPath:        fmt.Sprintf(`"%s"`, escapeJSONString(bucketPath)),
		templateKeyStorageDriverType: fmt.Sprintf(`"%s"`, driverType),
		templateKeySeedCount:         seedCount,

		// Distribution weights (only include non-zero ops)
		templateKeyGetDistrib:       params.GetDistrib,
		templateKeyPutDistrib:       params.PutDistrib,
		templateKeyDeleteDistrib:    params.DeleteDistrib,
		templateKeyStatDistrib:      params.StatDistrib,
		templateKeyHasGetDistrib:    params.GetDistrib > 0,
		templateKeyHasPutDistrib:    params.PutDistrib > 0,
		templateKeyHasDeleteDistrib: params.DeleteDistrib > 0,
		templateKeyHasStatDistrib:   params.StatDistrib > 0,

		// External item files
		templateKeyHasReadItems:    params.ReadItemsFile != "",
		templateKeyHasDeleteItems:  params.DeleteItemsFile != "",
		templateKeyReadItemsFile:   fmt.Sprintf(`"%s"`, escapeJSONString(params.ReadItemsFile)),
		templateKeyDeleteItemsFile: fmt.Sprintf(`"%s"`, escapeJSONString(params.DeleteItemsFile)),

		// Step IDs
		templateKeyStepIDSeed:   stepIDSeed,
		templateKeyStepIDMixed:  stepIDMixed,
		templateKeyStepIDSeedClean: stepIDSeedCleanup,
		templateKeyStepIDPutClean:  stepIDPutCleanup,

		// Structural flags
		"HasSeedPhase":           hasSeedPhase,
		"Cleanup":                params.Cleanup,
		"MixedPhaseNumber":       mixedStepNum,
		"CleanupSeedPhaseNumber": cleanupSeedStepNum,
		"CleanupPutPhaseNumber":  cleanupPutStepNum,
	}

	tmpl, err := template.New("mixedScenario").Parse(mixedWorkloadTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse mixed scenario template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute mixed scenario template: %w", err)
	}

	return buf.String(), nil
}
