package scenario

// Template for S3 list workload benchmarking object enumeration throughput.
const listWorkloadTemplate = `// Generated by spt
// S3 list workload for benchmarking object enumeration throughput
var concurrency = {{.Concurrency}};
var bucketPath = {{.BucketPath}};

var config = {
  "storage": {
    "driver": {
      "type": {{.StorageDriverType}},
      "limit": {
        "concurrency": concurrency
      }
    }
  },
  "item": {
    "type": {{.ItemType}},
    "input": {
      "path": bucketPath
    },
    "naming": {
      "radix": {{.NamingRadix}}{{if .HasPrefix}},
      "prefix": {{.Prefix}}{{end}},
      "type": {{.NamingType}}
    }
  },
  "load": {
    "batch": {
      "size": {{.BatchSize}}
    },
    "op": {
      "type": {{.LoadOpType}},
      "list": {
        "delimiter": {{.ListDelimiter}},
        "fetch_metadata": {{.FetchMetadata}},
        "include_versions": {{.IncludeVersions}},
        "max_keys": {{.MaxKeys}}
      },
      "limit": {
{{- if .HasOpLimitCount }}
        "count": {{.OpLimitCount}},
{{- end }}
        "rate": {{.OpLimitRate}}
      },
      "wait": {
        "finish": true
      }
    },
    "step": {
      "id": "{{.StepID}}"{{if .HasDuration}},
      "limit": {
        "time": {{.Duration}}
      }{{end}}
    }
  },
  "output": {
    "metrics": {
      "summary": {
        "persist": true
      },
      "average": {
        "period": {{.MetricsAveragePeriod}}
      }
    }
  }
};

var step = Load.config(config).start();
step.await();
step.close();
`

// Template for write workload with cleanup (delete after create)
const writeWithCleanupTemplate = `// Generated by spt
// Write workload with automatic cleanup
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Count: {{.ItemCount}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var itemCount = {{.ItemCount}};
var outputPath = {{.OutputPath}};
var itemsFile = "/tmp/spt-items-{{.Timestamp}}.csv";
var pauseTime = 10; // seconds between operations

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

function cleanup(filepath) {
    new java.lang.ProcessBuilder("/bin/sh", "-c", "rm -f " + filepath)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    }
};

// Pre-test stabilization
pause(pauseTime, "Allowing system to stabilize before test...");

// Create phase
print("[" + new Date().toISOString() + "] Starting create phase - " + itemCount + " objects");
CreateLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile  // Save created items for deletion
            }
        },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": itemCount
                }
            },
            "step": {
                "id": "{{.StepIDCreate}}"
            }
        }
    })
    .run();

print("[" + new Date().toISOString() + "] Create phase completed");

// Inter-phase pause
pause(pauseTime, "Pausing between create and delete phases...");

// Delete phase
print("[" + new Date().toISOString() + "] Starting delete phase");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile  // Read items to delete
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDDelete}}"
            }
        }
    })
    .run();

print("[" + new Date().toISOString() + "] Delete phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");

// Cleanup temporary file
cleanup(itemsFile);
print("[" + new Date().toISOString() + "] Test completed and cleaned up");
`

// Template for write workload with cleanup using duration limit
const writeWithCleanupDurationTemplate = `// Generated by spt
// Write workload with automatic cleanup (duration-based)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Duration: {{.Duration}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var duration = {{.Duration}};
var outputPath = {{.OutputPath}};
var itemsFile = "/tmp/spt-items-{{.Timestamp}}.csv";
var pauseTime = 10; // seconds between operations

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

function cleanup(filepath) {
    new java.lang.ProcessBuilder("/bin/sh", "-c", "rm -f " + filepath)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    }
};

// Pre-test stabilization
pause(pauseTime, "Allowing system to stabilize before test...");

// Create phase
print("[" + new Date().toISOString() + "] Starting create phase - duration: " + duration);
CreateLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile  // Save created items for deletion
            }
        },
        "load": {
            "op": {
                "type": "create"
            },
            "step": {
                "limit": {
                    "time": duration
                },
                "id": "{{.StepIDCreate}}"
            }
        }
    })
    .run();

print("[" + new Date().toISOString() + "] Create phase completed");

// Inter-phase pause
pause(pauseTime, "Pausing between create and delete phases...");

// Delete phase
print("[" + new Date().toISOString() + "] Starting delete phase");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile  // Read items to delete
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDDelete}}"
            }
        }
    })
    .run();

print("[" + new Date().toISOString() + "] Delete phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");

// Cleanup temporary file
cleanup(itemsFile);
print("[" + new Date().toISOString() + "] Test completed and cleaned up");
`

// Template for write-only workload (no cleanup)
const writeOnlyTemplate = `// Generated by spt
// Write-only workload
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Count: {{.ItemCount}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var itemCount = {{.ItemCount}};
var outputPath = {{.OutputPath}};

var config = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": itemCount
                }
            },
            "step": {
                "id": "{{.StepID}}"
            }
        }
};

print("[" + new Date().toISOString() + "] Starting write test - " + itemCount + " objects");
Load
    .config(config)
    .run();
print("[" + new Date().toISOString() + "] Write test completed");
`

// Template for write-only workload with duration limit
const writeOnlyDurationTemplate = `// Generated by spt
// Write-only workload (duration-based)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Duration: {{.Duration}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var duration = {{.Duration}};
var outputPath = {{.OutputPath}};

var config = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    },
    "load": {
        "op": {
            "type": "create"
        },
        "step": {
            "limit": {
                "time": duration
            },
            "id": "{{.StepID}}"
        }
    }
};

print("[" + new Date().toISOString() + "] Starting write test - duration: " + duration);
Load
    .config(config)
    .run();
print("[" + new Date().toISOString() + "] Write test completed");
`

// Template for write-only workload with default count
const writeOnlyDefaultTemplate = `// Generated by spt
// Write-only workload (default count)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var itemCount = 1000; // default
var outputPath = {{.OutputPath}};

var config = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    },
    "load": {
        "op": {
            "type": "create"
        },
        "step": {
            "limit": {
                "count": itemCount
            },
            "id": "{{.StepID}}"
        }
    }
};

print("[" + new Date().toISOString() + "] Starting write test - " + itemCount + " objects (default)");
Load
    .config(config)
    .run();
print("[" + new Date().toISOString() + "] Write test completed");
`
