package scenario

// Template for S3 list workload benchmarking object enumeration throughput.
const listWorkloadTemplate = `// Generated by spt
// S3 list workload for benchmarking object enumeration throughput
var concurrency = {{.Concurrency}};
var bucketPath = {{.BucketPath}};

var config = {
  "storage": {
    "driver": {
      "type": {{.StorageDriverType}},
      "limit": {
        "concurrency": concurrency
      }
    }
  },
  "item": {
    "type": {{.ItemType}},
    "input": {
      "path": bucketPath
    },
    "naming": {
      "radix": {{.NamingRadix}}{{if .HasPrefix}},
      "prefix": {{.Prefix}}{{end}},
      "type": {{.NamingType}}
    }
  },
  "load": {
    "batch": {
      "size": {{.BatchSize}}
    },
    "op": {
      "type": {{.LoadOpType}},
      "list": {
        "delimiter": {{.ListDelimiter}},
        "fetch_metadata": {{.FetchMetadata}},
        "include_versions": {{.IncludeVersions}},
        "max_keys": {{.MaxKeys}}
      },
      "limit": {
{{- if .HasOpLimitCount }}
        "count": {{.OpLimitCount}},
{{- end }}
        "rate": {{.OpLimitRate}}
      },
      "wait": {
        "finish": true
      }
    },
    "step": {
      "id": "{{.StepID}}"{{if .HasDuration}},
      "limit": {
        "time": {{.Duration}}
      }{{end}}
    }
  },
  "output": {
    "metrics": {
      "summary": {
        "persist": true
      },
      "average": {
        "period": {{.MetricsAveragePeriod}}
      }
    }
  }
};

var step = Load.config(config).start();
step.await();
step.close();
`

// Template for write workload with cleanup (delete after create)
const writeWithCleanupTemplate = `// Generated by spt
// Write workload with automatic cleanup
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Count: {{.ItemCount}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var itemCount = {{.ItemCount}};
var outputPath = {{.OutputPath}};
var itemsFile = "/tmp/spt-items-{{.Timestamp}}.csv";
var pauseTime = 10; // seconds between operations

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

function cleanup(filepath) {
    new java.lang.ProcessBuilder("/bin/sh", "-c", "rm -f " + filepath)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    }
};

// Pre-test stabilization
pause(pauseTime, "Allowing system to stabilize before test...");

// Create phase
print("[" + new Date().toISOString() + "] Starting create phase - " + itemCount + " objects");
CreateLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile  // Save created items for deletion
            }
        },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": itemCount
                }
            },
            "step": {
                "id": "{{.StepIDCreate}}"
            }
        }
    })
    .run();

print("[" + new Date().toISOString() + "] Create phase completed");

// Inter-phase pause
pause(pauseTime, "Pausing between create and delete phases...");

// Delete phase
print("[" + new Date().toISOString() + "] Starting delete phase");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile  // Read items to delete
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDDelete}}"
            }
        }
    })
    .run();

print("[" + new Date().toISOString() + "] Delete phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");

// Cleanup temporary file
cleanup(itemsFile);
print("[" + new Date().toISOString() + "] Test completed and cleaned up");
`

// Template for write workload with cleanup using duration limit
const writeWithCleanupDurationTemplate = `// Generated by spt
// Write workload with automatic cleanup (duration-based)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Duration: {{.Duration}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var duration = {{.Duration}};
var outputPath = {{.OutputPath}};
var itemsFile = "/tmp/spt-items-{{.Timestamp}}.csv";
var pauseTime = 10; // seconds between operations

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

function cleanup(filepath) {
    new java.lang.ProcessBuilder("/bin/sh", "-c", "rm -f " + filepath)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    }
};

// Pre-test stabilization
pause(pauseTime, "Allowing system to stabilize before test...");

// Create phase
print("[" + new Date().toISOString() + "] Starting create phase - duration: " + duration);
CreateLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile  // Save created items for deletion
            }
        },
        "load": {
            "op": {
                "type": "create"
            },
            "step": {
                "limit": {
                    "time": duration
                },
                "id": "{{.StepIDCreate}}"
            }
        }
    })
    .run();

print("[" + new Date().toISOString() + "] Create phase completed");

// Inter-phase pause
pause(pauseTime, "Pausing between create and delete phases...");

// Delete phase
print("[" + new Date().toISOString() + "] Starting delete phase");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile  // Read items to delete
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDDelete}}"
            }
        }
    })
    .run();

print("[" + new Date().toISOString() + "] Delete phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");

// Cleanup temporary file
cleanup(itemsFile);
print("[" + new Date().toISOString() + "] Test completed and cleaned up");
`

// Template for write-only workload (no cleanup)
const writeOnlyTemplate = `// Generated by spt
// Write-only workload
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Count: {{.ItemCount}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var itemCount = {{.ItemCount}};
var outputPath = {{.OutputPath}};
{{- if .SaveItems}}
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
var itemsFile = sptLogDir + "/log/" + "{{.StepID}}" + "/items.csv";
{{- end}}

var config = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": itemCount
                }
            },
            "step": {
                "id": "{{.StepID}}"
            }
        }
};

{{- if .SaveItems}}
config["item"]["output"]["file"] = itemsFile;
{{- end}}

print("[" + new Date().toISOString() + "] Starting write test - " + itemCount + " objects");
Load
    .config(config)
    .run();
print("[" + new Date().toISOString() + "] Write test completed");
`

// Template for write-only workload with duration limit
const writeOnlyDurationTemplate = `// Generated by spt
// Write-only workload (duration-based)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Duration: {{.Duration}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var duration = {{.Duration}};
var outputPath = {{.OutputPath}};
{{- if .SaveItems}}
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
var itemsFile = sptLogDir + "/log/" + "{{.StepID}}" + "/items.csv";
{{- end}}

var config = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    },
    "load": {
        "op": {
            "type": "create"
        },
        "step": {
            "limit": {
                "time": duration
            },
            "id": "{{.StepID}}"
        }
    }
};

{{- if .SaveItems}}
config["item"]["output"]["file"] = itemsFile;
{{- end}}

print("[" + new Date().toISOString() + "] Starting write test - duration: " + duration);
Load
    .config(config)
    .run();
print("[" + new Date().toISOString() + "] Write test completed");
`

// Template for write-only workload with default count
const writeOnlyDefaultTemplate = `// Generated by spt
// Write-only workload (default count)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var itemCount = 1000; // default
var outputPath = {{.OutputPath}};
{{- if .SaveItems}}
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
var itemsFile = sptLogDir + "/log/" + "{{.StepID}}" + "/items.csv";
{{- end}}

var config = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    },
    "load": {
        "op": {
            "type": "create"
        },
        "step": {
            "limit": {
                "count": itemCount
            },
            "id": "{{.StepID}}"
        }
    }
};

{{- if .SaveItems}}
config["item"]["output"]["file"] = itemsFile;
{{- end}}

print("[" + new Date().toISOString() + "] Starting write test - " + itemCount + " objects (default)");
Load
    .config(config)
    .run();
print("[" + new Date().toISOString() + "] Write test completed");
`

// ---------------------------------------------------------------------------
// READ workload templates
// ---------------------------------------------------------------------------

// Template for read workload with cleanup, duration-limited read phase.
// Phases: PreconditionLoad (seed) → ReadLoad (benchmark, recycle) → DeleteLoad (cleanup)
const readWithCleanupDurationTemplate = `// Generated by spt
// Read workload with cleanup (duration-based)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Seed: {{.SeedCount}}, Duration: {{.Duration}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var seedCount = {{.SeedCount}};
var duration = {{.Duration}};
var outputPath = {{.OutputPath}};
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
var itemsFile = sptLogDir + "/log/" + "{{.StepIDSeed}}" + "/items.csv";
var pauseTime = {{.ReadPhasePauseSeconds}}; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

function cleanup(filepath) {
    new java.lang.ProcessBuilder("/bin/sh", "-c", "rm -f " + filepath)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    }
};

// Phase 1: Seed (PreconditionLoad - metrics suppressed)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting seed phase - " + seedCount + " objects");
PreconditionLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": seedCount
                }
            },
            "step": {
                "id": "{{.StepIDSeed}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Seed phase completed");

// Phase 2: Read benchmark (ReadLoad - metrics collected)
pause(pauseTime, "Pausing before read phase...");
print("[" + new Date().toISOString() + "] Starting read phase - duration: " + duration);
ReadLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
{{if .ReadShuffle}}            "batch": {
                "size": {{.ReadShuffleBatchSize}}
            },
{{end}}            "op": {
                "type": "read",{{if .ReadShuffle}}
                "shuffle": true,{{end}}
                "recycle": {
                    "mode": true
                }
            },
            "step": {
                "limit": {
                    "time": duration
                },
                "id": "{{.StepIDRead}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Read phase completed");

// Phase 3: Cleanup (DeleteLoad)
pause(pauseTime, "Pausing before cleanup phase...");
print("[" + new Date().toISOString() + "] Starting cleanup phase");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDDelete}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Cleanup phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");
print("[" + new Date().toISOString() + "] Test completed and cleaned up");
`

// Template for read workload with cleanup, count-limited read phase.
const readWithCleanupCountTemplate = `// Generated by spt
// Read workload with cleanup (count-based)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Seed: {{.SeedCount}}, Read Count: {{.ItemCount}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var seedCount = {{.SeedCount}};
var readCount = {{.ItemCount}};
var outputPath = {{.OutputPath}};
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
var itemsFile = sptLogDir + "/log/" + "{{.StepIDSeed}}" + "/items.csv";
var pauseTime = {{.ReadPhasePauseSeconds}}; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

function cleanup(filepath) {
    new java.lang.ProcessBuilder("/bin/sh", "-c", "rm -f " + filepath)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    }
};

// Phase 1: Seed (PreconditionLoad - metrics suppressed)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting seed phase - " + seedCount + " objects");
PreconditionLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": seedCount
                }
            },
            "step": {
                "id": "{{.StepIDSeed}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Seed phase completed");

// Phase 2: Read benchmark (ReadLoad - metrics collected)
pause(pauseTime, "Pausing before read phase...");
print("[" + new Date().toISOString() + "] Starting read phase - " + readCount + " reads");
ReadLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
{{if .ReadShuffle}}            "batch": {
                "size": {{.ReadShuffleBatchSize}}
            },
{{end}}            "op": {
                "type": "read",{{if .ReadShuffle}}
                "shuffle": true,{{end}}
                "recycle": {
                    "mode": true
                },
                "limit": {
                    "count": readCount
                }
            },
            "step": {
                "id": "{{.StepIDRead}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Read phase completed");

// Phase 3: Cleanup (DeleteLoad)
pause(pauseTime, "Pausing before cleanup phase...");
print("[" + new Date().toISOString() + "] Starting cleanup phase");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDDelete}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Cleanup phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");
print("[" + new Date().toISOString() + "] Test completed and cleaned up");
`

// Template for read workload without cleanup, duration-limited read phase.
const readNoCleanupDurationTemplate = `// Generated by spt
// Read workload without cleanup (duration-based)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Seed: {{.SeedCount}}, Duration: {{.Duration}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var seedCount = {{.SeedCount}};
var duration = {{.Duration}};
var outputPath = {{.OutputPath}};
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
var itemsFile = sptLogDir + "/log/" + "{{.StepIDSeed}}" + "/items.csv";
var pauseTime = {{.ReadPhasePauseSeconds}}; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    }
};

// Phase 1: Seed (PreconditionLoad - metrics suppressed)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting seed phase - " + seedCount + " objects");
PreconditionLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": seedCount
                }
            },
            "step": {
                "id": "{{.StepIDSeed}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Seed phase completed");

// Phase 2: Read benchmark (ReadLoad - metrics collected)
pause(pauseTime, "Pausing before read phase...");
print("[" + new Date().toISOString() + "] Starting read phase - duration: " + duration);
ReadLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
{{if .ReadShuffle}}            "batch": {
                "size": {{.ReadShuffleBatchSize}}
            },
{{end}}            "op": {
                "type": "read",{{if .ReadShuffle}}
                "shuffle": true,{{end}}
                "recycle": {
                    "mode": true
                }
            },
            "step": {
                "limit": {
                    "time": duration
                },
                "id": "{{.StepIDRead}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Read phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");
print("[" + new Date().toISOString() + "] Test completed (seed objects preserved)");
`

// Template for read workload without cleanup, count-limited read phase.
const readNoCleanupCountTemplate = `// Generated by spt
// Read workload without cleanup (count-based)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Seed: {{.SeedCount}}, Read Count: {{.ItemCount}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var seedCount = {{.SeedCount}};
var readCount = {{.ItemCount}};
var outputPath = {{.OutputPath}};
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
var itemsFile = sptLogDir + "/log/" + "{{.StepIDSeed}}" + "/items.csv";
var pauseTime = {{.ReadPhasePauseSeconds}}; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    }
};

// Phase 1: Seed (PreconditionLoad - metrics suppressed)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting seed phase - " + seedCount + " objects");
PreconditionLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": seedCount
                }
            },
            "step": {
                "id": "{{.StepIDSeed}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Seed phase completed");

// Phase 2: Read benchmark (ReadLoad - metrics collected)
pause(pauseTime, "Pausing before read phase...");
print("[" + new Date().toISOString() + "] Starting read phase - " + readCount + " reads");
ReadLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
{{if .ReadShuffle}}            "batch": {
                "size": {{.ReadShuffleBatchSize}}
            },
{{end}}            "op": {
                "type": "read",{{if .ReadShuffle}}
                "shuffle": true,{{end}}
                "recycle": {
                    "mode": true
                },
                "limit": {
                    "count": readCount
                }
            },
            "step": {
                "id": "{{.StepIDRead}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Read phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");
print("[" + new Date().toISOString() + "] Test completed (seed objects preserved)");
`

// Template for read workload with defaults (seed 2500, read 60s, cleanup).
const readDefaultTemplate = `// Generated by spt
// Read workload with defaults
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Seed: 2500, Duration: 60s

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var seedCount = 2500; // default
var duration = "60s"; // default
var outputPath = {{.OutputPath}};
var sptLogDir = org.apache.logging.log4j.ThreadContext.get("home_dir");
if (!sptLogDir) { sptLogDir = java.lang.System.getProperty("user.dir"); }
var itemsFile = sptLogDir + "/log/" + "{{.StepIDSeed}}" + "/items.csv";
var pauseTime = {{.ReadPhasePauseSeconds}}; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

function cleanup(filepath) {
    new java.lang.ProcessBuilder("/bin/sh", "-c", "rm -f " + filepath)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize{{if .HasPartSize}},
            "ranges": {
                "threshold": {{.PartSize}}
            }{{end}}
        },
        "output": {
            "path": outputPath
        }
    }
};

// Phase 1: Seed (PreconditionLoad - metrics suppressed)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting seed phase - " + seedCount + " objects");
PreconditionLoad
    .config(sharedConfig)
    .config({
        "item": {
            "output": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "create",
                "limit": {
                    "count": seedCount
                }
            },
            "step": {
                "id": "{{.StepIDSeed}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Seed phase completed");

// Phase 2: Read benchmark (ReadLoad - metrics collected)
pause(pauseTime, "Pausing before read phase...");
print("[" + new Date().toISOString() + "] Starting read phase - duration: " + duration);
ReadLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
{{if .ReadShuffle}}            "batch": {
                "size": {{.ReadShuffleBatchSize}}
            },
{{end}}            "op": {
                "type": "read",{{if .ReadShuffle}}
                "shuffle": true,{{end}}
                "recycle": {
                    "mode": true
                }
            },
            "step": {
                "limit": {
                    "time": duration
                },
                "id": "{{.StepIDRead}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Read phase completed");

// Phase 3: Cleanup (DeleteLoad)
pause(pauseTime, "Pausing before cleanup phase...");
print("[" + new Date().toISOString() + "] Starting cleanup phase");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDDelete}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Cleanup phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");
print("[" + new Date().toISOString() + "] Test completed and cleaned up");
`

// ---------------------------------------------------------------------------
// READ-FROM-FILE workload templates (skip seed, use provided items.csv)
// ---------------------------------------------------------------------------

// Template for read-from-file workload with duration limit.
// Skips the seed phase entirely - reads from a pre-existing items.csv.
const readFromFileDurationTemplate = `// Generated by spt
// Read-from-file workload (duration-based, no seed phase)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Duration: {{.Duration}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var duration = {{.Duration}};
var outputPath = {{.OutputPath}};
var itemsFile = {{.ItemsFile}};
var pauseTime = {{.ReadPhasePauseSeconds}}; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    }
};

// Read benchmark (no seed phase - using pre-existing items.csv)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting read phase - duration: " + duration);
print("[" + new Date().toISOString() + "] Using items file: " + itemsFile);
ReadLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
{{if .ReadShuffle}}            "batch": {
                "size": {{.ReadShuffleBatchSize}}
            },
{{end}}            "op": {
                "type": "read",{{if .ReadShuffle}}
                "shuffle": true,{{end}}
                "recycle": {
                    "mode": true
                }
            },
            "step": {
                "limit": {
                    "time": duration
                },
                "id": "{{.StepIDRead}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Read phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");
print("[" + new Date().toISOString() + "] Test completed");
`

// Template for read-from-file workload with count limit.
const readFromFileCountTemplate = `// Generated by spt
// Read-from-file workload (count-based, no seed phase)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Read Count: {{.ItemCount}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var readCount = {{.ItemCount}};
var outputPath = {{.OutputPath}};
var itemsFile = {{.ItemsFile}};
var pauseTime = {{.ReadPhasePauseSeconds}}; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    }
};

// Read benchmark (no seed phase - using pre-existing items.csv)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting read phase - " + readCount + " reads");
print("[" + new Date().toISOString() + "] Using items file: " + itemsFile);
ReadLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
{{if .ReadShuffle}}            "batch": {
                "size": {{.ReadShuffleBatchSize}}
            },
{{end}}            "op": {
                "type": "read",{{if .ReadShuffle}}
                "shuffle": true,{{end}}
                "recycle": {
                    "mode": true
                },
                "limit": {
                    "count": readCount
                }
            },
            "step": {
                "id": "{{.StepIDRead}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Read phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");
print("[" + new Date().toISOString() + "] Test completed");
`

// Template for read-from-file workload with duration and cleanup.
const readFromFileDurationCleanupTemplate = `// Generated by spt
// Read-from-file workload (duration-based with cleanup, no seed phase)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Duration: {{.Duration}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var duration = {{.Duration}};
var outputPath = {{.OutputPath}};
var itemsFile = {{.ItemsFile}};
var pauseTime = {{.ReadPhasePauseSeconds}}; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    }
};

// Read benchmark (no seed phase - using pre-existing items.csv)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting read phase - duration: " + duration);
print("[" + new Date().toISOString() + "] Using items file: " + itemsFile);
ReadLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
{{if .ReadShuffle}}            "batch": {
                "size": {{.ReadShuffleBatchSize}}
            },
{{end}}            "op": {
                "type": "read",{{if .ReadShuffle}}
                "shuffle": true,{{end}}
                "recycle": {
                    "mode": true
                }
            },
            "step": {
                "limit": {
                    "time": duration
                },
                "id": "{{.StepIDRead}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Read phase completed");

// Cleanup phase
pause(pauseTime, "Pausing before cleanup phase...");
print("[" + new Date().toISOString() + "] Starting cleanup phase");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDDelete}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Cleanup phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");
print("[" + new Date().toISOString() + "] Test completed and cleaned up");
`

// Template for read-from-file workload with count and cleanup.
const readFromFileCountCleanupTemplate = `// Generated by spt
// Read-from-file workload (count-based with cleanup, no seed phase)
// Concurrency: {{.Concurrency}}, Size: {{.ItemSize}}, Read Count: {{.ItemCount}}

// Configuration
var concurrency = {{.Concurrency}};
var itemSize = {{.ItemSize}};
var readCount = {{.ItemCount}};
var outputPath = {{.OutputPath}};
var itemsFile = {{.ItemsFile}};
var pauseTime = {{.ReadPhasePauseSeconds}}; // seconds between phases

// Helper functions
function pause(seconds, message) {
    if (message) {
        print("[" + new Date().toISOString() + "] " + message);
    }
    new java.lang.ProcessBuilder("/bin/sh", "-c", "sleep " + seconds)
        .inheritIO()
        .start()
        .waitFor();
}

// Shared configuration
var sharedConfig = {
    "storage": {
        "driver": {
            "type": {{.StorageDriverType}},
            "limit": {
                "concurrency": concurrency
            }
        }
    },
    "item": {
        "data": {
            "size": itemSize
        },
        "output": {
            "path": outputPath
        }
    }
};

// Read benchmark (no seed phase - using pre-existing items.csv)
pause(pauseTime, "Allowing system to stabilize before test...");
print("[" + new Date().toISOString() + "] Starting read phase - " + readCount + " reads");
print("[" + new Date().toISOString() + "] Using items file: " + itemsFile);
ReadLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
{{if .ReadShuffle}}            "batch": {
                "size": {{.ReadShuffleBatchSize}}
            },
{{end}}            "op": {
                "type": "read",{{if .ReadShuffle}}
                "shuffle": true,{{end}}
                "recycle": {
                    "mode": true
                },
                "limit": {
                    "count": readCount
                }
            },
            "step": {
                "id": "{{.StepIDRead}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Read phase completed");

// Cleanup phase
pause(pauseTime, "Pausing before cleanup phase...");
print("[" + new Date().toISOString() + "] Starting cleanup phase");
DeleteLoad
    .config(sharedConfig)
    .config({
        "item": {
            "input": {
                "file": itemsFile
            }
        },
        "load": {
            "op": {
                "type": "delete"
            },
            "step": {
                "id": "{{.StepIDDelete}}"
            }
        }
    })
    .run();
print("[" + new Date().toISOString() + "] Cleanup phase completed");

// Post-test pause
pause(pauseTime, "Allowing final operations to settle...");
print("[" + new Date().toISOString() + "] Test completed and cleaned up");
`
