package scenario

// tablesTPSTemplate generates a two-phase TPS scenario:
// Phase 1: provision (skipped if NoProvision)
// Phase 2: tableWrite (duration-based concurrent Iceberg commits)
const tablesTPSTemplate = `// Generated by spt — S3 Tables TPS test vector
var bucket = "{{.TablesBucket}}";
var namespace = "{{.TablesNamespace}}";
var tableName = "{{.TablesTableName}}";
var concurrency = {{.TablesConcurrency}};

var sharedStorage = {
  "storage": {
    "driver": {
      "type": "s3-tables",
      "limit": {
        "concurrency": concurrency
      }
    },
    "auth": {
      "uid": "{{.TablesAccessKey}}",
      "secret": "{{.TablesSecretKey}}",
      "version": 4
    },
    "s3tables": {
      "bucket": bucket,
      "namespace": namespace,
      "tableName": tableName,
      "commitFreqMs": {{.TablesCommitFreqMs}},
      "targetFileSizeBytes": {{.TablesTargetFileSizeBytes}}
    }
  }
};
{{if not .NoProvision}}
var provisionConfig = JSON.parse(JSON.stringify(sharedStorage));
provisionConfig.storage.s3tables.opMode = "{{.OpModeProvision}}";
provisionConfig.load = {
  "op": {
    "type": "noop",
    "limit": {
      "count": 1
    }
  },
  "step": {
    "id": "{{.TablesStepIDProvision}}"
  }
};

Load.config(provisionConfig).run();
{{end}}
var writeConfig = JSON.parse(JSON.stringify(sharedStorage));
writeConfig.storage.s3tables.opMode = "{{.OpModeTableWrite}}";
writeConfig.load = {
  "op": {
    "type": "create"
  },
  "step": {
    "id": "{{.TablesStepIDWrite}}",
    "limit": {
      "time": "{{.TablesDuration}}"
    }
  }
};

Load.config(writeConfig).run();
`

// tablesCompactionTemplate generates a three-phase compaction scenario:
// Phase 1: provision (skipped if NoProvision)
// Phase 2: tableWrite (seed small files until totalIngestBytes reached)
// Phase 3: tableCompactionPoll (concurrency=1, polls until file count converges)
const tablesCompactionTemplate = `// Generated by spt — S3 Tables compaction test vector
var bucket = "{{.TablesBucket}}";
var namespace = "{{.TablesNamespace}}";
var tableName = "{{.TablesTableName}}";

var sharedStorage = {
  "storage": {
    "driver": {
      "type": "s3-tables",
      "limit": {
        "concurrency": {{.TablesConcurrency}}
      }
    },
    "auth": {
      "uid": "{{.TablesAccessKey}}",
      "secret": "{{.TablesSecretKey}}",
      "version": 4
    },
    "s3tables": {
      "bucket": bucket,
      "namespace": namespace,
      "tableName": tableName,
      "targetFileSizeBytes": {{.TablesTargetFileSizeBytes}},
      "ingestFileSizeBytes": {{.TablesIngestFileSizeBytes}},
      "totalIngestBytes": {{.TablesTotalIngestBytes}}
    }
  }
};
{{if not .NoProvision}}
var provisionConfig = JSON.parse(JSON.stringify(sharedStorage));
provisionConfig.storage.s3tables.opMode = "{{.OpModeProvision}}";
provisionConfig.load = {
  "op": {
    "type": "noop",
    "limit": {
      "count": 1
    }
  },
  "step": {
    "id": "{{.TablesStepIDProvision}}"
  }
};

Load.config(provisionConfig).run();
{{end}}
var writeConfig = JSON.parse(JSON.stringify(sharedStorage));
writeConfig.storage.s3tables.opMode = "{{.OpModeTableWrite}}";
writeConfig.storage.driver = {
  "type": "s3-tables",
  "limit": {
    "concurrency": {{.TablesConcurrency}}
  }
};
writeConfig.load = {
  "op": {
    "type": "create",
    "limit": {
      "count": {{.TablesIngestFileCount}}
    }
  },
  "step": {
    "id": "{{.TablesStepIDWrite}}"
  }
};

Load.config(writeConfig).run();

var compactionConfig = JSON.parse(JSON.stringify(sharedStorage));
compactionConfig.storage.s3tables.opMode = "{{.OpModeCompactionPoll}}";
compactionConfig.storage.s3tables.compactionPollTimeoutMs = {{.TablesCompactionTimeoutMs}};
compactionConfig.storage.driver = {
  "type": "s3-tables",
  "limit": {
    "concurrency": 1
  }
};
compactionConfig.load = {
  "op": {
    "type": "noop",
    "limit": {
      "count": 1
    }
  },
  "step": {
    "id": "{{.TablesStepIDCompaction}}"
  }
};

Load.config(compactionConfig).run();
`

// tablesCatalogTemplate generates a three-phase catalog latency scenario:
// Phase 1: provision (skipped if NoProvision)
// Phase 2: catalogSeed (bulk create namespaceCount × tablesPerNs tables)
// Phase 3: tableCatalog (concurrent GetTable/ListTables, duration-based)
const tablesCatalogTemplate = `// Generated by spt — S3 Tables catalog test vector
var bucket = "{{.TablesBucket}}";
var namespace = "{{.TablesNamespace}}";

var sharedStorage = {
  "storage": {
    "driver": {
      "type": "s3-tables",
      "limit": {
        "concurrency": {{.TablesConcurrency}}
      }
    },
    "auth": {
      "uid": "{{.TablesAccessKey}}",
      "secret": "{{.TablesSecretKey}}",
      "version": 4
    },
    "s3tables": {
      "bucket": bucket,
      "namespace": namespace,
      "namespaceCount": {{.TablesNamespaceCount}},
      "tablesPerNamespace": {{.TablesTablesPerNs}}
    }
  }
};
{{if not .NoProvision}}
var provisionConfig = JSON.parse(JSON.stringify(sharedStorage));
provisionConfig.storage.s3tables.opMode = "{{.OpModeProvision}}";
provisionConfig.load = {
  "op": {
    "type": "noop",
    "limit": {
      "count": 1
    }
  },
  "step": {
    "id": "{{.TablesStepIDProvision}}"
  }
};

Load.config(provisionConfig).run();
{{end}}
var seedConfig = JSON.parse(JSON.stringify(sharedStorage));
seedConfig.storage.s3tables.opMode = "{{.OpModeCatalogSeed}}";
seedConfig.load = {
  "op": {
    "type": "create",
    "limit": {
      "count": {{.TablesSeedCount}}
    }
  },
  "step": {
    "id": "{{.TablesStepIDSeed}}"
  }
};

Load.config(seedConfig).run();

var catalogConfig = JSON.parse(JSON.stringify(sharedStorage));
catalogConfig.storage.s3tables.opMode = "{{.OpModeTableCatalog}}";
catalogConfig.storage.driver = {
  "type": "s3-tables",
  "limit": {
    "concurrency": {{.TablesReadConcurrency}}
  }
};
catalogConfig.load = {
  "op": {
    "type": "create"
  },
  "step": {
    "id": "{{.TablesStepIDCatalog}}",
    "limit": {
      "time": "{{.TablesDuration}}"
    }
  }
};

Load.config(catalogConfig).run();
`
