plugins {
	id 'spt.java-extension'
	alias(libs.plugins.shadow)
}

version = "4.2.21"

ext {
	rootPkg = "com.dell.spt.storage.driver.coop"
}

dependencies {
	// Coop driver dependencies
	// API dependencies that must come from parent classloader
	compileOnly(
		libs.confuse,
		libs.confuse.io.yaml,
		libs.java.commons,
		libs.log4j.api,
		libs.log4j.core,
	)

	// External dependencies that will be bundled (none for coop)

	// Test-only dependencies
	testImplementation libs.mockito.core
}
