package com.dell.spt.load.step.mixed;

import com.dell.spt.base.env.Extension;
import com.dell.spt.base.item.op.OpType;
import com.dell.spt.base.load.step.client.LoadStepClientBase;
import com.dell.spt.base.logging.LogUtil;
import com.dell.spt.base.metrics.MetricsManager;
import com.dell.spt.base.util.BinarySizeFormat;
import com.github.akurilov.commons.reflection.TypeUtil;
import com.github.akurilov.commons.system.SizeInBytes;
import com.github.akurilov.confuse.Config;

import java.util.List;

/**
 * Client-side counterpart of {@link MixedLoadStepLocal}. Responsible for registering one metrics
 * context per enabled operation type (GET, PUT, DELETE) in distributed mode.
 */
@SuppressWarnings({"unchecked", "rawtypes"
})
public final class MixedLoadStepClient extends LoadStepClientBase<MixedLoadStepClient> {

	public MixedLoadStepClient(
					final Config config,
					final List<Extension> extensions,
					final List<Config> ctxConfigs,
					final MetricsManager metricsManager) {
		super(config, extensions, ctxConfigs, metricsManager);
	}

	@Override
	public String getTypeName() {
		return MixedLoadStepExtension.TYPE;
	}

	@Override
	protected MixedLoadStepClient copyInstance(final Config config, final List<Config> ctxConfigs) {
		return new MixedLoadStepClient(config, extensions, ctxConfigs, metricsMgr);
	}

	@Override
	protected void init() throws IllegalStateException {

		final String autoStepId = "mixed_" + LogUtil.getDateTimeStamp();
		final Config stepConfig = config.configVal("load-step");
		if (stepConfig.boolVal("idAutoGenerated")) {
			stepConfig.val("id", autoStepId);
		}

		final int getWeight = config.intVal("load-op-weights-get");
		final int putWeight = config.intVal("load-op-weights-put");
		final int deleteWeight = config.intVal("load-op-weights-delete");
		final int statWeight = config.intVal("load-op-weights-stat");

		final int concurrencyLimit = config.intVal("storage-driver-limit-concurrency");
		final Config outputConfig = config.configVal("output");
		final Config metricsConfig = outputConfig.configVal("metrics");
		final boolean colorFlag = outputConfig.boolVal("color");

		final SizeInBytes itemDataSize;
		final Object itemDataSizeRaw = config.val("item-data-size");
		if (itemDataSizeRaw instanceof String) {
			itemDataSize = BinarySizeFormat.parseSize((String) itemDataSizeRaw);
		} else {
			itemDataSize = new SizeInBytes(TypeUtil.typeConvert(itemDataSizeRaw, long.class));
		}

		int originIndex = 0;
		if (getWeight > 0) {
			initMetrics(originIndex++, OpType.READ, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
		}
		if (putWeight > 0) {
			initMetrics(originIndex++, OpType.CREATE, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
		}
		if (deleteWeight > 0) {
			initMetrics(originIndex++, OpType.DELETE, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
		}
		if (statWeight > 0) {
			initMetrics(originIndex++, OpType.STAT, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
		}
	}
}
