package com.dell.spt.load.step.mixed;

import com.dell.spt.base.concurrent.ServiceTaskExecutor;
import com.dell.spt.base.config.ConstantValueInputImpl;
import com.dell.spt.base.config.IllegalConfigurationException;
import com.dell.spt.base.data.DataInput;
import com.dell.spt.base.env.Extension;
import com.dell.spt.base.item.Item;
import com.dell.spt.base.item.ItemFactory;
import com.dell.spt.base.item.ItemType;
import com.dell.spt.base.item.io.ItemInfoFileOutput;
import com.dell.spt.base.item.io.ItemInputFactory;
import com.dell.spt.base.item.io.ItemTimingMetricsFileOutput;
import com.dell.spt.base.item.io.NewDataItemInput;
import com.dell.spt.base.item.naming.ItemNameInput;
import com.dell.spt.base.item.op.OpType;
import com.dell.spt.base.item.op.Operation;
import com.dell.spt.base.item.op.OperationsBuilder;
import com.dell.spt.base.item.op.data.DataOperationsBuilderImpl;
import com.dell.spt.base.load.step.local.LoadStepLocalBase;
import com.dell.spt.base.load.step.local.context.LoadStepContextImpl;
import com.dell.spt.base.logging.LogUtil;
import com.dell.spt.base.logging.Loggers;
import com.dell.spt.base.metrics.MetricsManager;
import com.dell.spt.base.metrics.context.MetricsContext;
import com.dell.spt.base.storage.Credential;
import com.dell.spt.base.storage.driver.StorageDriver;
import com.github.akurilov.commons.io.Input;
import com.github.akurilov.commons.io.Output;
import com.github.akurilov.commons.reflection.TypeUtil;
import com.github.akurilov.commons.system.SizeInBytes;
import com.github.akurilov.confuse.Config;
import com.github.akurilov.confuse.exceptions.InvalidValuePathException;
import com.github.akurilov.confuse.exceptions.InvalidValueTypeException;
import com.github.akurilov.confuse.impl.BasicConfig;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.ThreadContext;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import static com.github.akurilov.commons.collection.TreeUtil.reduceForest;
import static com.github.akurilov.commons.lang.Exceptions.throwUnchecked;
import static com.github.akurilov.confuse.Config.deepToMap;

/**
 * Local (single-node) implementation of the mixed workload load step.
 *
 * <p>Uses a single {@link MixedLoadGenerator} with a pre-shuffled {@link OpSchedule}
 * to drive all operation types through one {@link StorageDriver}. This eliminates the
 * concurrency waste and distribution skew of the multi-generator model.
 *
 * <p>PUT-created items are:
 * <ol>
 *   <li>Written to {@code put-remaining.csv} so the cleanup phase can delete them.
 *   <li>Pushed into the {@link PoolItemInput} delete queue so freshly-written objects
 *       are eligible for deletion in the same run.
 * </ol>
 */
@SuppressWarnings({"unchecked", "rawtypes"
})
public final class MixedLoadStepLocal extends LoadStepLocalBase {

	public MixedLoadStepLocal(
					final Config baseConfig,
					final List<Extension> extensions,
					final List<Config> contextConfigs,
					final MetricsManager metricsManager) {
		super(baseConfig, extensions, contextConfigs, metricsManager);
	}

	@Override
	public String getTypeName() {
		return MixedLoadStepExtension.TYPE;
	}

	@Override
	protected void init() {

		// ── 1. Merge base config with all context configs ──────────────────
		final List<Map<String, Object>> trees = new ArrayList<>(1 + ctxConfigs.size());
		trees.add(deepToMap(config));
		for (final Config ctx : ctxConfigs) {
			trees.add(deepToMap(ctx));
		}
		final Map<String, Object> mergedTree = reduceForest(trees);

		Config mergedConfig;
		try {
			mergedConfig = new BasicConfig(config.pathSep(), config.schema(), mergedTree);
		} catch (final InvalidValuePathException | InvalidValueTypeException e) {
			LogUtil.exception(Level.FATAL, e, "Mixed workload scenario syntax error");
			throwUnchecked(e);
			return;
		}

		// ── 2. Resolve step ID ─────────────────────────────────────────────
		final Config loadStepCfg = mergedConfig.configVal("load-step");
		final String autoStepId = "mixed_" + LogUtil.getDateTimeStamp();
		if (loadStepCfg.boolVal("idAutoGenerated")) {
			loadStepCfg.val("id", autoStepId);
		}
		final String stepId = loadStepCfg.stringVal("id");
		ThreadContext.put("step_id", stepId);

		// ── 3. Common config values ────────────────────────────────────────
		final Config storageConfig = mergedConfig.configVal("storage");
		final Config outputConfig = mergedConfig.configVal("output");
		final Config metricsConfig = outputConfig.configVal("metrics");
		final boolean colorFlag = outputConfig.boolVal("color");
		final Config loadConfig = mergedConfig.configVal("load");
		final int batchSize = loadConfig.intVal("batch-size");
		final boolean tracePersist = outputConfig.boolVal("metrics-trace-persist");
		final Config itemConfig = mergedConfig.configVal("item");
		final Config dataConfig = itemConfig.configVal("data");
		final Config dataInputConfig = dataConfig.configVal("input");
		final Config dataLayerConfig = dataInputConfig.configVal("layer");
		final int concurrencyLimit = storageConfig.intVal("driver-limit-concurrency");

		final Object itemDataSizeRaw = mergedConfig.val("item-data-size");
		final SizeInBytes itemDataSize = itemDataSizeRaw instanceof String
						? new SizeInBytes((String) itemDataSizeRaw)
						: new SizeInBytes(TypeUtil.typeConvert(itemDataSizeRaw, long.class));

		final ItemType itemType = ItemType.valueOf(itemConfig.stringVal("type").toUpperCase(Locale.ROOT));
		final ItemFactory itemFactory = ItemType.getItemFactory(itemType);

		// ── 4. Read weights → build OpSchedule ─────────────────────────────
		final int getWeight = mergedConfig.intVal("load-op-weight-get");
		final int putWeight = mergedConfig.intVal("load-op-weight-put");
		final int deleteWeight = mergedConfig.intVal("load-op-weight-delete");
		final int statWeight = mergedConfig.intVal("load-op-weight-stat");

		final int nonZero = (getWeight > 0 ? 1 : 0) + (putWeight > 0 ? 1 : 0)
						+ (deleteWeight > 0 ? 1 : 0) + (statWeight > 0 ? 1 : 0);
		if (nonZero < 2) {
			throw new IllegalStateException("MixedLoad requires at least 2 non-zero op weights");
		}

		final Map<OpType, Integer> weightMap = new EnumMap<>(OpType.class);
		if (getWeight > 0)
			weightMap.put(OpType.READ, getWeight);
		if (putWeight > 0)
			weightMap.put(OpType.CREATE, putWeight);
		if (deleteWeight > 0)
			weightMap.put(OpType.DELETE, deleteWeight);
		if (statWeight > 0)
			weightMap.put(OpType.STAT, statWeight);
		final OpSchedule schedule = new OpSchedule(weightMap);

		Loggers.MSG.info("MixedLoad: {} active ops, concurrency {}, schedule {}",
						nonZero, concurrencyLimit, weightMap);

		// ── 5. Load seed items → build PoolItemInput ───────────────────────
		final String itemInputFile = resolveItemInputFile(mergedConfig);
		final List seedItems = new ArrayList();
		if (itemInputFile != null && !itemInputFile.isEmpty()) {
			loadSeedItems(itemInputFile, seedItems, itemFactory);
		}
		if (seedItems.isEmpty() && (getWeight > 0 || statWeight > 0)) {
			throw new IllegalStateException(
							"MixedLoad: GET/STAT weights are non-zero but no seed items loaded from item.input.file");
		}
		final PoolItemInput pool = new PoolItemInput(seedItems);

		// Pre-populate delete queue from explicit file if provided
		final String deleteItemsFile = resolveDeleteItemsFile(mergedConfig);
		if (deleteItemsFile != null && !deleteItemsFile.isEmpty()) {
			loadDeleteItems(deleteItemsFile, pool, itemFactory);
		}

		// ── 6. Initialise DataInput ────────────────────────────────────────
		final DataInput dataInput;
		try {
			final Object dataLayerSizeRaw = dataLayerConfig.val("size");
			final SizeInBytes dataLayerSize = dataLayerSizeRaw instanceof String
							? new SizeInBytes((String) dataLayerSizeRaw)
							: new SizeInBytes(TypeUtil.typeConvert(dataLayerSizeRaw, int.class));
			dataInput = DataInput.instance(
							dataInputConfig.stringVal("file"),
							dataInputConfig.stringVal("seed"),
							dataLayerSize,
							dataLayerConfig.intVal("cache"),
							dataLayerConfig.boolVal("heap"));
		} catch (final IOException e) {
			throw new IllegalStateException("Failed to initialize the data input", e);
		}

		// ── 7. put-remaining.csv path ──────────────────────────────────────
		final String homeDir = ThreadContext.get("home_dir");
		final Path putRemainingFilePath;
		if (homeDir != null && !homeDir.isEmpty()) {
			putRemainingFilePath = Paths.get(homeDir, "log", stepId, "put-remaining.csv");
		} else {
			putRemainingFilePath = Paths.get(System.getProperty("user.dir"), "put-remaining-" + stepId + ".csv");
		}

		// ── 8. Create single StorageDriver ─────────────────────────────────
		final StorageDriver driver;
		try {
			driver = StorageDriver.instance(
							extensions, storageConfig, dataInput,
							dataConfig.boolVal("verify"), batchSize, stepId);
		} catch (final IllegalConfigurationException | InterruptedException e) {
			throw new IllegalStateException("Failed to initialize storage driver", e);
		}

		// ── 9. Create per-op-type OperationsBuilders ───────────────────────
		final Config authConfig = storageConfig.configVal("auth");
		final var uid = authConfig.stringVal("uid");
		final var secret = authConfig.stringVal("secret");
		final Credential cred = (uid == null && secret == null)
						? Credential.NONE
						: Credential.getInstance(uid, secret);
		final Input credInput = new ConstantValueInputImpl(cred);

		final var inputConfig = itemConfig.configVal("input");
		var itemInputPath = inputConfig.stringVal("path");
		if (itemInputPath != null && itemInputPath.indexOf('/') != 0) {
			itemInputPath = '/' + itemInputPath;
		}

		// Output path for CREATE ops (bucket prefix)
		final String outputPath = itemConfig.stringVal("output-path");
		final Input<String> outputPathInput = outputPath != null
						? new ConstantValueInputImpl<>(outputPath)
						: null;

		// Multipart threshold — same logic as LoadGeneratorBuilderImpl
		final Config rangesConfig = itemConfig.configVal("data-ranges");
		final long sizeThreshold;
		final var sizeThresholdRaw = rangesConfig.val("threshold");
		if (sizeThresholdRaw instanceof String) {
			sizeThreshold = SizeInBytes.toFixedSize((String) sizeThresholdRaw);
		} else {
			sizeThreshold = TypeUtil.typeConvert(sizeThresholdRaw, long.class);
		}

		final Map<OpType, OperationsBuilder> builders = new EnumMap<>(OpType.class);
		int originIdx = 0;
		if (getWeight > 0)
			builders.put(OpType.READ, makeOpsBuilder(originIdx++, OpType.READ, itemInputPath, null, credInput, sizeThreshold));
		if (putWeight > 0)
			builders.put(OpType.CREATE, makeOpsBuilder(originIdx++, OpType.CREATE, itemInputPath, outputPathInput, credInput, sizeThreshold));
		if (deleteWeight > 0)
			builders.put(OpType.DELETE, makeOpsBuilder(originIdx++, OpType.DELETE, itemInputPath, null, credInput, sizeThreshold));
		if (statWeight > 0)
			builders.put(OpType.STAT, makeOpsBuilder(originIdx++, OpType.STAT, itemInputPath, null, credInput, sizeThreshold));

		// ── 10. Create new-item input for CREATE ───────────────────────────
		final Input newItemInput;
		if (putWeight > 0) {
			newItemInput = createNewItemInput(itemConfig, itemFactory);
		} else {
			newItemInput = null;
		}

		// ── 11. Register metrics ───────────────────────────────────────────
		originIdx = 0;
		if (getWeight > 0)
			initMetrics(originIdx++, OpType.READ, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
		if (putWeight > 0)
			initMetrics(originIdx++, OpType.CREATE, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
		if (deleteWeight > 0)
			initMetrics(originIdx++, OpType.DELETE, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
		if (statWeight > 0)
			initMetrics(originIdx++, OpType.STAT, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);

		// Build the per-op MetricsContext map for result routing
		final Map<OpType, MetricsContext> metricsCtxByOpType = new EnumMap<>(OpType.class);
		originIdx = 0;
		if (getWeight > 0)
			metricsCtxByOpType.put(OpType.READ, metricsContexts.get(originIdx++));
		if (putWeight > 0)
			metricsCtxByOpType.put(OpType.CREATE, metricsContexts.get(originIdx++));
		if (deleteWeight > 0)
			metricsCtxByOpType.put(OpType.DELETE, metricsContexts.get(originIdx++));
		if (statWeight > 0)
			metricsCtxByOpType.put(OpType.STAT, metricsContexts.get(originIdx++));

		// ── 12. Wire put-remaining.csv output for PUT completions ──────────
		final ItemInfoFileOutput putRemainingFileOut;
		if (putWeight > 0) {
			try {
				putRemainingFileOut = new ItemInfoFileOutput<>(putRemainingFilePath);
			} catch (final IOException e) {
				throw new IllegalStateException("Failed to open put-remaining.csv: " + putRemainingFilePath, e);
			}
		} else {
			putRemainingFileOut = null;
		}

		// PUT results output: feeds delete queue + writes to put-remaining.csv
		final Output putResultsOutput;
		if (putWeight > 0) {
			putResultsOutput = new Output() {
				@Override
				public boolean put(final Object op) {
					if (op instanceof Operation) {
						final Operation o = (Operation) op;
						if (Operation.Status.SUCC.equals(o.status())) {
							// Feed the delete queue
							pool.addDeleteItem((Item) o.item());
							// Write to put-remaining.csv — pass the Operation, not the Item,
							// because ItemInfoFileOutput<O extends Operation> expects an Operation
							if (putRemainingFileOut != null) {
								putRemainingFileOut.put(o);
							}
						}
					}
					return true;
				}

				@Override
				public int put(final List ops, final int from, final int to) {
					for (int i = from; i < to; i++)
						put(ops.get(i));
					return to - from;
				}

				@Override
				public int put(final List ops) {
					for (final Object op : ops)
						put(op);
					return ops.size();
				}

				@Override
				public Input getInput() {
					return null;
				}

				@Override
				public void close() throws Exception {
					if (putRemainingFileOut != null)
						putRemainingFileOut.close();
				}
			};
		} else {
			putResultsOutput = null;
		}

		// ── 13. Create MixedLoadGenerator ──────────────────────────────────
		final MixedLoadGenerator generator = new MixedLoadGenerator(
						ServiceTaskExecutor.VT_EXECUTOR, schedule, pool, builders,
						driver, concurrencyLimit, newItemInput, putResultsOutput, null);

		// ── 14. Create single LoadStepContextImpl with per-op metrics map ──
		// Use the first MetricsContext as the primary (for isDone checks).
		// The metricsCtxByOpType map handles per-op routing in put().
		final var stepCtx = new LoadStepContextImpl(
						stepId, generator, driver,
						metricsContexts.get(0),
						metricsCtxByOpType,
						loadConfig, tracePersist, null);

		// ── 14b. Wrap the driver result output to release generator permits ──
		// The LoadStepContextImpl constructor sets itself as the driver's
		// operationResultOutput.  We replace it with a thin wrapper that
		// releases one MixedLoadGenerator concurrency permit for every
		// completed operation (regardless of status), then delegates to the
		// original step context.  This prevents the generator from flooding
		// the driver's input queue.
		driver.operationResultOutput(new Output() {
			@Override
			public boolean put(final Object op) {
				generator.releasePermit();
				return stepCtx.put((Operation) op);
			}

			@Override
			public int put(final List ops, final int from, final int to) {
				for (int i = from; i < to; i++) {
					generator.releasePermit();
				}
				return stepCtx.put((List) ops, from, to);
			}

			@Override
			public int put(final List ops) {
				return put(ops, 0, ops.size());
			}

			@Override
			public Input getInput() {
				return stepCtx.getInput();
			}

			@Override
			public void close() throws Exception { /* stepCtx lifecycle managed by LoadStepLocalBase */ }
		});

		stepContexts.add(stepCtx);
		// Pad stepContexts so all metrics context indices resolve to the same context.
		// initMetrics() captures stepContexts.get(i) in a closure for the concurrency gauge;
		// without padding, indices 1+ throw IndexOutOfBoundsException.
		for (int i = 1; i < nonZero; i++) {
			stepContexts.add(stepCtx);
		}

		// ── 15. Wire operation results output (for put-remaining routing) ──
		stepCtx.operationsResultsOutput(new Output() {
			@Override
			public boolean put(final Object op) {
				if (op == null) {
					// null sentinel → close the file
					if (putRemainingFileOut != null) {
						try {
							putRemainingFileOut.close();
						} catch (final Exception e) {
							LogUtil.exception(Level.WARN, e, "Failed to close put-remaining output");
						}
					}
					return true;
				}
				if (op instanceof Operation) {
					final Operation o = (Operation) op;
					if (Operation.Status.SUCC.equals(o.status()) && OpType.CREATE.equals(o.type())) {
						// Feed delete queue
						pool.addDeleteItem((Item) o.item());
						// Write to put-remaining.csv — pass the Operation, not the Item,
						// because ItemInfoFileOutput<O extends Operation> expects an Operation
						if (putRemainingFileOut != null) {
							putRemainingFileOut.put(o);
						}
					}
				}
				return true;
			}

			@Override
			public int put(final List ops, final int from, final int to) {
				for (int i = from; i < to; i++)
					put(ops.get(i));
				return to - from;
			}

			@Override
			public int put(final List ops) {
				for (final Object op : ops)
					put(op);
				return ops.size();
			}

			@Override
			public Input getInput() {
				return null;
			}

			@Override
			public void close() throws Exception {
				if (putRemainingFileOut != null)
					putRemainingFileOut.close();
			}
		});

		// ── 16. Timing metrics output ──────────────────────────────────────
		final Path timingPath = Paths.get(
						System.getProperty("java.io.tmpdir"),
						"spt", "timingMetrics_" + stepId + "_mixed");
		try {
			final Output timingOut = new ItemTimingMetricsFileOutput<>(timingPath);
			stepCtx.operationsMetricsOutput(timingOut);
		} catch (final IOException e) {
			LogUtil.exception(Level.ERROR, e, "Failed to initialize timing metrics for mixed generator");
		}
	}

	// ── Helpers ────────────────────────────────────────────────────────────────

	/** Creates an {@link OperationsBuilder} for the given op type. */
	private static OperationsBuilder makeOpsBuilder(
					final int originIndex,
					final OpType opType,
					final String inputPath,
					final Input<String> outputPathInput,
					final Input credInput,
					final long sizeThreshold) {
		final var builder = new DataOperationsBuilderImpl(originIndex);
		builder.opType(opType);
		builder.inputPath(inputPath);
		builder.outputPathInput(outputPathInput);
		builder.credentialInput(credInput);
		builder.sizeThreshold(sizeThreshold);
		return builder;
	}

	/** Creates a new-item input for CREATE operations. */
	private static Input createNewItemInput(final Config itemConfig, final ItemFactory itemFactory) {
		final var namingConfig = itemConfig.configVal("naming");
		final int length = namingConfig.intVal("length");
		final var seedRaw = namingConfig.val("seed");
		long seed = 0;
		try {
			seed = TypeUtil.typeConvert(seedRaw, long.class);
		} catch (final ClassCastException | NumberFormatException e) {
			LogUtil.exception(Level.WARN, e, "Item naming seed conversion failed, using 0");
		}
		final var prefix = namingConfig.stringVal("prefix");
		final var radix = namingConfig.intVal("radix");
		final var step = namingConfig.intVal("step");
		final var type = ItemNameInput.ItemNamingType.valueOf(namingConfig.stringVal("type").toUpperCase(Locale.ROOT));
		final var itemNameInput = ItemNameInput.Builder.newInstance()
						.length(length)
						.seed(seed)
						.prefix(prefix)
						.radix(radix)
						.step(step)
						.type(type)
						.build();

		final Object itemDataSizeRaw = itemConfig.val("data-size");
		final SizeInBytes dataSize;
		if (itemDataSizeRaw instanceof String) {
			dataSize = new SizeInBytes((String) itemDataSizeRaw);
		} else {
			dataSize = new SizeInBytes(TypeUtil.typeConvert(itemDataSizeRaw, long.class));
		}
		return new NewDataItemInput(itemFactory, itemNameInput, dataSize);
	}

	/** Resolves the seed items file path from config. */
	private static String resolveItemInputFile(final Config cfg) {
		try {
			return cfg.stringVal("item-input-file");
		} catch (final Exception e) {
			return null;
		}
	}

	/** Loads seed items from a file into the given list. Uses {@link ItemInputFactory} to handle
	 *  both CSV (.csv) and binary (temp slicer) formats automatically. */
	private static void loadSeedItems(
					final String filePath,
					final List items,
					final ItemFactory factory) {
		final Path path = Paths.get(filePath);
		if (!Files.exists(path)) {
			Loggers.ERR.warn("MixedLoad: seed items file not found: {}", filePath);
			return;
		}
		try (final Input fileInput = ItemInputFactory.createFileItemInput(factory, filePath)) {
			if (fileInput == null) {
				Loggers.ERR.warn("MixedLoad: failed to open seed items file: {}", filePath);
				return;
			}
			Object item;
			while ((item = fileInput.get()) != null) {
				items.add(item);
			}
		} catch (final java.io.EOFException eof) {
			// BinFileInput throws EOFException at end of stream — normal termination
		} catch (final Exception e) {
			LogUtil.exception(Level.WARN, e, "MixedLoad: failed to load seed items from {}", filePath);
		}
		Loggers.MSG.info("MixedLoad: loaded {} seed items from {}", items.size(), filePath);
	}

	/** Loads items from a file into the PoolItemInput's delete queue. */
	private static void loadDeleteItems(
					final String filePath,
					final PoolItemInput pool,
					final ItemFactory factory) {
		final Path path = Paths.get(filePath);
		if (!Files.exists(path)) {
			Loggers.ERR.warn("MixedLoad: delete-items-file not found: {}", filePath);
			return;
		}
		try (final Input fileInput = ItemInputFactory.createFileItemInput(factory, filePath)) {
			if (fileInput == null) {
				Loggers.ERR.warn("MixedLoad: failed to open delete-items-file: {}", filePath);
				return;
			}
			Object item;
			int count = 0;
			while ((item = fileInput.get()) != null) {
				pool.addDeleteItem((Item) item);
				count++;
			}
			Loggers.MSG.info("MixedLoad: pre-populated DELETE queue with {} items from {}", count, filePath);
		} catch (final java.io.EOFException eof) {
			// BinFileInput throws EOFException at end of stream — normal termination
		} catch (final Exception e) {
			LogUtil.exception(Level.WARN, e, "MixedLoad: failed to populate DELETE queue from {}", filePath);
		}
	}

	/** Reads {@code load.op.delete.input.file} from the merged config. */
	private static String resolveDeleteItemsFile(final Config cfg) {
		try {
			return cfg.stringVal("load-op-delete-input-file");
		} catch (final Exception e) {
			return null;
		}
	}
}
