package com.dell.spt.load.step.mixed;

import com.dell.spt.base.config.IllegalConfigurationException;
import com.dell.spt.base.data.DataInput;
import com.dell.spt.base.env.Extension;
import com.dell.spt.base.item.ItemFactory;
import com.dell.spt.base.item.ItemType;
import com.dell.spt.base.item.io.ItemInfoFileOutput;
import com.dell.spt.base.item.io.ItemTimingMetricsFileOutput;
import com.dell.spt.base.item.op.Operation;
import com.dell.spt.base.item.op.OpType;
import com.dell.spt.base.load.generator.LoadGenerator;
import com.dell.spt.base.load.generator.LoadGeneratorBuilder;
import com.dell.spt.base.load.generator.LoadGeneratorBuilderImpl;
import com.dell.spt.base.load.step.local.LoadStepLocalBase;
import com.dell.spt.base.load.step.local.context.LoadStepContext;
import com.dell.spt.base.load.step.local.context.LoadStepContextImpl;
import com.dell.spt.base.logging.LogUtil;
import com.dell.spt.base.metrics.MetricsManager;
import com.dell.spt.base.storage.driver.StorageDriver;
import com.github.akurilov.commons.concurrent.throttle.IndexThrottle;
import com.github.akurilov.commons.concurrent.throttle.SequentialWeightsThrottle;
import com.github.akurilov.commons.io.Input;
import com.github.akurilov.commons.io.Output;
import com.github.akurilov.commons.reflection.TypeUtil;
import com.github.akurilov.commons.system.SizeInBytes;
import com.github.akurilov.confuse.Config;
import com.github.akurilov.confuse.exceptions.InvalidValuePathException;
import com.github.akurilov.confuse.exceptions.InvalidValueTypeException;
import com.github.akurilov.confuse.impl.BasicConfig;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.ThreadContext;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import static com.github.akurilov.commons.collection.TreeUtil.reduceForest;
import static com.github.akurilov.commons.lang.Exceptions.throwUnchecked;
import static com.github.akurilov.confuse.Config.deepToMap;

/**
 * Local (single-node) implementation of the mixed workload load step.
 *
 * <p>Creates one {@link LoadGenerator} per enabled operation type (GET/PUT/DELETE), weighted by
 * a {@link SequentialWeightsThrottle}. PUT-created items are written to {@code put-remaining.csv}
 * so the cleanup phase can delete them. GET and DELETE both read from the scattered seed items
 * file; DELETE exhausts the seed once (no recycle) while GET recycles continuously.
 */
@SuppressWarnings({"unchecked", "rawtypes"
})
public final class MixedLoadStepLocal extends LoadStepLocalBase {

	public MixedLoadStepLocal(
					final Config baseConfig,
					final List<Extension> extensions,
					final List<Config> contextConfigs,
					final MetricsManager metricsManager) {
		super(baseConfig, extensions, contextConfigs, metricsManager);
	}

	@Override
	public String getTypeName() {
		return MixedLoadStepExtension.TYPE;
	}

	@Override
	protected void init() {

		// ── 1. Merge base config with all context configs ──────────────────
		// Each JS .config({}) call appends one entry to ctxConfigs.
		final List<Map<String, Object>> trees = new ArrayList<>(1 + ctxConfigs.size());
		trees.add(deepToMap(config));
		for (final Config ctx : ctxConfigs) {
			trees.add(deepToMap(ctx));
		}
		final Map<String, Object> mergedTree = reduceForest(trees);

		Config mergedConfig;
		try {
			mergedConfig = new BasicConfig(config.pathSep(), config.schema(), mergedTree);
		} catch (final InvalidValuePathException | InvalidValueTypeException e) {
			LogUtil.exception(Level.FATAL, e, "Mixed workload scenario syntax error");
			throwUnchecked(e);
			return; // unreachable
		}

		// ── 2. Resolve step ID ─────────────────────────────────────────────
		final Config loadStepCfg = mergedConfig.configVal("load-step"); // load → step (dash split)
		final String autoStepId = "mixed_" + LogUtil.getDateTimeStamp();
		if (loadStepCfg.boolVal("idAutoGenerated")) {
			loadStepCfg.val("id", autoStepId);
		}
		final String stepId = loadStepCfg.stringVal("id");
		ThreadContext.put("step_id", stepId);

		// ── 3. Common config values ────────────────────────────────────────
		final Config storageConfig = mergedConfig.configVal("storage");
		final Config outputConfig = mergedConfig.configVal("output");
		final Config metricsConfig = outputConfig.configVal("metrics");
		final boolean colorFlag = outputConfig.boolVal("color");
		final Config loadConfig = mergedConfig.configVal("load");
		final int batchSize = loadConfig.intVal("batch-size");
		final boolean tracePersist = outputConfig.boolVal("metrics-trace-persist");
		final Config itemConfig = mergedConfig.configVal("item");
		final Config dataConfig = itemConfig.configVal("data");
		final Config dataInputConfig = dataConfig.configVal("input");
		final Config dataLayerConfig = dataInputConfig.configVal("layer");
		final int concurrencyLimit = storageConfig.intVal("driver-limit-concurrency");

		final Object itemDataSizeRaw = mergedConfig.val("item-data-size");
		final SizeInBytes itemDataSize = itemDataSizeRaw instanceof String
						? new SizeInBytes((String) itemDataSizeRaw)
						: new SizeInBytes(TypeUtil.typeConvert(itemDataSizeRaw, long.class));

		final ItemType itemType = ItemType.valueOf(itemConfig.stringVal("type").toUpperCase(Locale.ROOT));
		final ItemFactory itemFactory = ItemType.getItemFactory(itemType);

		// ── 4. Read weights ────────────────────────────────────────────────
		final int getWeight = mergedConfig.intVal("load-op-weight-get");
		final int putWeight = mergedConfig.intVal("load-op-weight-put");
		final int deleteWeight = mergedConfig.intVal("load-op-weight-delete");

		if ((getWeight > 0 ? 1 : 0) + (putWeight > 0 ? 1 : 0) + (deleteWeight > 0 ? 1 : 0) < 2) {
			throw new IllegalStateException("MixedLoad requires at least 2 non-zero op weights");
		}

		// Build the weights array in the same order we create generators (GET → PUT → DELETE)
		final List<Integer> weightList = new ArrayList<>(3);
		if (getWeight > 0)
			weightList.add(getWeight);
		if (putWeight > 0)
			weightList.add(putWeight);
		if (deleteWeight > 0)
			weightList.add(deleteWeight);
		final int[] weights = weightList.stream().mapToInt(Integer::intValue).toArray();
		final IndexThrottle weightThrottle = new SequentialWeightsThrottle(weights);

		// ── 5. Initialise DataInput ────────────────────────────────────────
		final DataInput dataInput;
		try {
			final Object dataLayerSizeRaw = dataLayerConfig.val("size");
			final SizeInBytes dataLayerSize = dataLayerSizeRaw instanceof String
							? new SizeInBytes((String) dataLayerSizeRaw)
							: new SizeInBytes(TypeUtil.typeConvert(dataLayerSizeRaw, int.class));
			dataInput = DataInput.instance(
							dataInputConfig.stringVal("file"),
							dataInputConfig.stringVal("seed"),
							dataLayerSize,
							dataLayerConfig.intVal("cache"),
							dataLayerConfig.boolVal("heap"));
		} catch (final IOException e) {
			throw new IllegalStateException("Failed to initialize the data input", e);
		}

		// ── 6. put-remaining.csv path ──────────────────────────────────────
		final String homeDir = ThreadContext.get("home_dir");
		final Path putRemainingFilePath;
		if (homeDir != null && !homeDir.isEmpty()) {
			putRemainingFilePath = Paths.get(homeDir, "log", stepId, "put-remaining.csv");
		} else {
			putRemainingFilePath = Paths.get(System.getProperty("user.dir"), "put-remaining-" + stepId + ".csv");
		}

		// ── 7. Register metrics (must precede generator creation) ──────────
		int originIdx = 0;
		if (getWeight > 0)
			initMetrics(originIdx++, OpType.READ, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
		if (putWeight > 0)
			initMetrics(originIdx++, OpType.CREATE, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);
		if (deleteWeight > 0)
			initMetrics(originIdx++, OpType.DELETE, concurrencyLimit, metricsConfig, itemDataSize, colorFlag);

		// ── 8. Create generators ───────────────────────────────────────────
		originIdx = 0;

		// GET: reads seed items continuously (recycle enabled)
		if (getWeight > 0) {
			final Config getSubConfig = makeSub(mergedConfig, "read");
			getSubConfig.val("load-op-recycle-mode", true);
			buildContext(originIdx++, stepId, OpType.READ, getSubConfig, itemType, itemFactory,
							dataInput, batchSize, tracePersist, weightThrottle, null);
		}

		// PUT: creates new objects; writes results to put-remaining.csv for cleanup
		if (putWeight > 0) {
			final Config putSubConfig = makeSub(mergedConfig, "create");
			putSubConfig.val("item-input-file", ""); // generate new items, don't read existing
			buildContext(originIdx++, stepId, OpType.CREATE, putSubConfig, itemType, itemFactory,
							dataInput, batchSize, tracePersist, weightThrottle, putRemainingFilePath);
		}

		// DELETE: reads from the scattered seed items file (no recycle); exhausts seed items once
		if (deleteWeight > 0) {
			final Config delSubConfig = makeSub(mergedConfig, "delete");
			buildContext(originIdx++, stepId, OpType.DELETE, delSubConfig, itemType, itemFactory,
							dataInput, batchSize, tracePersist, weightThrottle, null);
		}
	}

	// ── Helpers ────────────────────────────────────────────────────────────────

	/** Returns a deep copy of {@code base} with {@code load.op.type} set to {@code opType}. */
	private static Config makeSub(final Config base, final String opType) {
		final Config sub;
		try {
			sub = new BasicConfig(base);
		} catch (final InvalidValuePathException | InvalidValueTypeException e) {
			throwUnchecked(e);
			return null; // unreachable
		}
		sub.val("load-op-type", opType);
		return sub;
	}

	/**
	 * Builds a {@link LoadGenerator} + {@link LoadStepContext}, adds the context to
	 * {@link #stepContexts}, and wires any optional item output.
	 *
	 * @param putRemPath when non-null, successful PUT items are written to this CSV for cleanup
	 */
	private void buildContext(
					final int originIndex,
					final String stepId,
					final OpType opType,
					final Config subConfig,
					final ItemType itemType,
					final ItemFactory itemFactory,
					final DataInput dataInput,
					final int batchSize,
					final boolean tracePersist,
					final IndexThrottle weightThrottle,
					final Path putRemPath) {

		final Config storageConfig = subConfig.configVal("storage");
		final Config loadConfig = subConfig.configVal("load");
		final Config outputConfig = subConfig.configVal("output");
		final Config dataConfig = subConfig.configVal("item").configVal("data");

		try {
			final StorageDriver driver = StorageDriver.instance(
							extensions, storageConfig, dataInput,
							dataConfig.boolVal("verify"), batchSize, stepId);

			final LoadGeneratorBuilder generatorBuilder = new LoadGeneratorBuilderImpl<>()
							.itemConfig(subConfig.configVal("item"))
							.loadConfig(loadConfig)
							.itemType(itemType)
							.itemFactory(itemFactory)
							.loadOperationsOutput(driver)
							.authConfig(storageConfig.configVal("auth"))
							.originIndex(originIndex)
							.addThrottle(weightThrottle);

			final LoadGenerator generator = generatorBuilder.build();
			final var shardMetrics = generatorBuilder.listShardMetricsRecorder();

			final LoadStepContext stepCtx = new LoadStepContextImpl<>(
							stepId, generator, driver,
							metricsContexts.get(originIndex),
							loadConfig,
							outputConfig.boolVal("metrics-trace-persist"),
							shardMetrics);
			stepContexts.add(stepCtx);

			// ── Wire PUT tee output (put-remaining.csv) ─────────────────────
			if (putRemPath != null) {
				final ItemInfoFileOutput fileOut;
				try {
					fileOut = new ItemInfoFileOutput<>(putRemPath);
				} catch (final IOException e) {
					throw new IllegalStateException("Failed to open put-remaining.csv: " + putRemPath, e);
				}

				stepCtx.operationsResultsOutput(new Output() {
					@Override
					public boolean put(final Object op) {
						if (op == null) {
							// null sentinel → close the file
							try {
								fileOut.close();
							} catch (final Exception e) {
								LogUtil.exception(Level.WARN, e, "Failed to close put-remaining output");
							}
							return true;
						}
						if (op instanceof Operation) {
							final Operation o = (Operation) op;
							if (Operation.Status.SUCC.equals(o.status())) {
								fileOut.put(op);
							}
						}
						return true;
					}

					@Override
					public int put(final List ops, final int from, final int to) {
						for (int i = from; i < to; i++) {
							put(ops.get(i));
						}
						return to - from;
					}

					@Override
					public int put(final List ops) {
						for (final Object op : ops) {
							put(op);
						}
						return ops.size();
					}

					@Override
					public Input getInput() {
						return null;
					}

					@Override
					public void close() throws Exception {
						if (fileOut != null) {
							fileOut.close();
						}
					}
				});
			}

			// ── Timing metrics output ──────────────────────────────────────
			final Path timingPath = Paths.get(
							System.getProperty("java.io.tmpdir"),
							"spt", "timingMetrics_" + stepId + "_" + opType.name().toLowerCase(Locale.ROOT));
			try {
				final Output timingOut = new ItemTimingMetricsFileOutput<>(timingPath);
				stepCtx.operationsMetricsOutput(timingOut);
			} catch (final IOException e) {
				LogUtil.exception(Level.ERROR, e,
								"Failed to initialize timing metrics for {} generator", opType);
			}

		} catch (final IllegalConfigurationException e) {
			throw new IllegalStateException("Failed to initialize storage driver for " + opType, e);
		} catch (final IOException e) {
			throw new IllegalStateException("I/O error initializing generator for " + opType, e);
		} catch (final InterruptedException e) {
			throwUnchecked(e);
		}
	}

}
