plugins {
	id 'spt.java-extension'
	alias(libs.plugins.shadow)
}

version = "4.2.13"

ext {
	rootPkg = "com.dell.spt.load.step.pipeline"
}

dependencies {
	// Extension-specific dependencies
	implementation(
		libs.confuse,
		libs.confuse.io.yaml,
		libs.java.commons,
		libs.log4j.api,
		libs.log4j.core,
	)

	testRuntimeOnly(
		libs.commons.codec,
		libs.confuse.io.yaml,
		libs.disruptor,
		libs.netty.transport.native.epoll,
	)
}
