FROM docker:dind

RUN apk add --no-cache --update python py-pip \
    && pip install -U virtualenv \
    && pip install -U requests \
    && pip install -U robotframework \
    && pip install -U robotframework-requests \
    && pip install -U robotframework-csvlibrary

ENV PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/site-packages:/root/spt/src/test/robot/lib

ADD build /root/spt/build
ADD ci/docker/entrypoint_robotest.sh /root/spt/ci/docker/entrypoint_robotest.sh
ADD src/test/robot /root/spt/src/test/robot

RUN chmod ugo+x /root/spt/ci/docker/entrypoint_robotest.sh

WORKDIR /root/spt

ENTRYPOINT ["/root/spt/ci/docker/entrypoint_robotest.sh"]
