package replay

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

type legacyScenario struct {
	Type   string         `json:"type"`
	Config map[string]any `json:"config"`
	Steps  []legacyStep   `json:"steps"`
	Jobs   []legacyStep   `json:"jobs"`
}

type legacyStep struct {
	Type     string         `json:"type"`
	Config   map[string]any `json:"config"`
	Value    string         `json:"value"`
	Blocking bool           `json:"blocking"`
	Steps    []legacyStep   `json:"steps"`
	Jobs     []legacyStep   `json:"jobs"`
}

type itemFileExpr struct {
	VarName      string
	ArchiveID    string
	StepID       string
	FileName     string
	HomeRelative string
	From         string
	To           string
}

var itemFileRe = regexp.MustCompile(`\$\{MONGOOSE_DIR\}/log/([^/]+)/([^"'\s]+)`)
var mongoosePathRe = regexp.MustCompile(`\$\{MONGOOSE_DIR\}/([^"'\s]+)`)
var (
	expandVarRe          = regexp.MustCompile(`\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?`)
	exprPlaceholderRe    = regexp.MustCompile(`"__SPT_EXPR_([A-Za-z0-9_]+)__"`)
	unsafeExprSentinelRe = regexp.MustCompile(`__SPT_EXPR_[A-Za-z0-9_]+__`)
)

// ConvertJSON converts a supported legacy JSON scenario into SPT JavaScript.
func ConvertJSON(raw []byte, runScript RunScript, opts Options) (*Generated, error) {
	var legacy legacyScenario
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	if err := dec.Decode(&legacy); err != nil {
		return nil, fmt.Errorf("parse legacy JSON scenario: %w", err)
	}

	var diagnostics []Diagnostic
	var pathRewrites []PathRewrite
	var stepsOut []StepSummary
	effectiveVars := effectiveVariables(runScript.Exports, opts)
	if len(endpointHosts(opts.Endpoints)) == 0 {
		diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "local endpoints are required for replay"})
	}
	bucket := effectiveBucket(opts.Bucket, runScript)
	if bucket == "" {
		diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "bucket is required; set --bucket, S3_BUCKET, or archived BUCKET"})
	} else {
		effectiveVars["BUCKET"] = bucket
	}

	diagnostics = append(diagnostics, detectUnsupportedProtocols(legacy)...)
	if strings.EqualFold(legacy.Type, "parallel") {
		diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "parallel scenarios are not implemented for replay"})
	}

	legacySteps := legacy.Steps
	if len(legacySteps) == 0 {
		legacySteps = legacy.Jobs
	}
	if len(legacySteps) == 0 {
		diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "scenario contains no steps or jobs"})
	}

	if hasErrors(diagnostics) {
		return &Generated{Diagnostics: diagnostics}, diagnosticsError(diagnostics)
	}

	label := sanitizeLabel(opts.Label)
	if label == "" {
		label = defaultLabel
	}
	baseTS := strings.TrimSpace(opts.BaseTimestamp)
	if baseTS == "" {
		baseTS = baseTimestamp()
	}

	archiveToStepID := map[string]string{}
	itemVars := map[string]itemFileExpr{}
	var itemVarOrder []string
	var body strings.Builder
	body.WriteString("// Generated by spt replay\n")
	body.WriteString("var sptHomeDir = org.apache.logging.log4j.ThreadContext.get(\"home_dir\");\n")
	body.WriteString("if (!sptHomeDir) { sptHomeDir = java.lang.System.getProperty(\"user.dir\"); }\n")
	body.WriteString("var MONGOOSE_DIR = sptHomeDir;\n")
	writePreludeVars(&body, effectiveVars)
	body.WriteString("\n")
	body.WriteString("function pauseSeconds(seconds, message) {\n")
	body.WriteString("  if (message) { print(\"[\" + new Date().toISOString() + \"] \" + message); }\n")
	body.WriteString("  java.lang.Thread.sleep(Number(seconds) * 1000);\n")
	body.WriteString("}\n\n")

	loadStepNumber := 0
	waitNumber := 0
	for i, step := range legacySteps {
		stepType := strings.ToLower(strings.TrimSpace(step.Type))
		switch stepType {
		case "load", "precondition":
			loadStepNumber++
			converted, err := convertLoadStep(step, i, loadStepNumber, label, baseTS, bucket, opts, effectiveVars, archiveToStepID, itemVars, &itemVarOrder)
			if err != nil {
				diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: err.Error()})
				continue
			}
			stepsOut = append(stepsOut, converted.summary)
			pathRewrites = append(pathRewrites, converted.rewrites...)
			body.WriteString(converted.js)
			body.WriteString("\n")
		case "command":
			seconds, ok := parseSleepCommand(step.Value, effectiveVars)
			if !ok {
				diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: fmt.Sprintf("unsupported command step: %s", step.Value)})
				body.WriteString(fmt.Sprintf("// Unsupported archived command skipped: %s\n\n", jsLineComment(step.Value)))
				continue
			}
			waitNumber++
			body.WriteString(fmt.Sprintf("pauseSeconds(%d, %s);\n\n", seconds, jsQuote(fmt.Sprintf("Archived wait %d", waitNumber))))
		case "parallel":
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "parallel scenarios are not implemented for replay"})
		default:
			diagnostics = append(diagnostics, Diagnostic{Severity: severityWarning, Message: fmt.Sprintf("unsupported step type %q skipped", step.Type)})
		}
	}
	if hasErrors(diagnostics) {
		return &Generated{Diagnostics: diagnostics}, diagnosticsError(diagnostics)
	}
	pathRewrites = uniquePathRewrites(pathRewrites)

	var prelude strings.Builder
	prelude.WriteString(body.String())
	js := prelude.String()
	if len(itemVarOrder) > 0 {
		var defs strings.Builder
		defs.WriteString("// Canonical item-file paths rewritten from archived step labels.\n")
		for _, key := range itemVarOrder {
			item := itemVars[key]
			if item.StepID != "" && item.FileName != "" {
				defs.WriteString(fmt.Sprintf("var %s = sptHomeDir + \"/log/\" + %s + \"/%s\";\n", item.VarName, jsQuote(item.StepID), jsEscape(item.FileName)))
			} else {
				defs.WriteString(fmt.Sprintf("var %s = sptHomeDir + \"/%s\";\n", item.VarName, jsEscape(item.HomeRelative)))
			}
		}
		defs.WriteString("\n")
		insertAt := strings.Index(js, "\nfunction pauseSeconds")
		if insertAt >= 0 {
			js = js[:insertAt+1] + defs.String() + js[insertAt+1:]
		}
	}

	return &Generated{
		ScenarioJS:      []byte(js),
		Diagnostics:     diagnostics,
		Steps:           stepsOut,
		PathRewrites:    pathRewrites,
		EffectiveBucket: bucket,
	}, nil
}

type convertedStep struct {
	js       string
	summary  StepSummary
	rewrites []PathRewrite
}

func convertLoadStep(step legacyStep, index, stepNumber int, label, baseTS, bucket string, opts Options, vars map[string]string, archiveToStepID map[string]string, itemVars map[string]itemFileExpr, itemVarOrder *[]string) (convertedStep, error) {
	archiveID := resolveString(getPath(step.Config, "test", "step", "id"), vars)
	if archiveID == "" {
		archiveID = fmt.Sprintf("archive-step-%03d", index+1)
	}
	opType := strings.ToLower(resolveString(firstPath(step.Config,
		[]string{"load", "op", "type"},
		[]string{"load", "type"},
	), vars))
	opSuffix := opType
	loadFactory := "Load"
	if strings.EqualFold(step.Type, "precondition") {
		opType = "create"
		opSuffix = "seed"
		loadFactory = "PreconditionLoad"
	} else {
		switch opType {
		case "", "create", "write":
			opType = "create"
			opSuffix = "create"
			loadFactory = "Load"
		case "read":
			loadFactory = "ReadLoad"
		case "delete":
			loadFactory = "DeleteLoad"
		default:
			return convertedStep{}, fmt.Errorf("unsupported load operation %q in step %s", opType, archiveID)
		}
	}

	stepID := formatStepID(label, stepNumber, baseTS, opSuffix)
	archiveToStepID[archiveID] = stepID

	concurrency := intValue(firstPath(step.Config,
		[]string{"load", "limit", "concurrency"},
		[]string{"storage", "driver", "limit", "concurrency"},
		[]string{"storage", "driver", "concurrency"},
	), vars)
	itemSize := resolveString(getPath(step.Config, "item", "data", "size"), vars)
	limitTimeRaw := getPath(step.Config, "test", "step", "limit", "time")
	limitCountRaw := firstPath(step.Config,
		[]string{"test", "step", "limit", "count"},
		[]string{"load", "op", "limit", "count"},
		[]string{"load", "limit", "count"},
	)
	if missing := unresolvedVars(limitTimeRaw, vars); len(missing) > 0 {
		return convertedStep{}, fmt.Errorf("step %s has unresolved variable %s in time limit", archiveID, missing[0])
	}
	if missing := unresolvedVars(limitCountRaw, vars); len(missing) > 0 {
		return convertedStep{}, fmt.Errorf("step %s has unresolved variable %s in count limit", archiveID, missing[0])
	}
	duration := durationValue(limitTimeRaw, vars)
	count := int64Value(limitCountRaw, vars)
	if requiresExplicitLimit(opType) && duration == "" && count == 0 {
		return convertedStep{}, fmt.Errorf("step %s has no time or count limit", archiveID)
	}

	config := map[string]any{
		"storage": map[string]any{
			"driver": map[string]any{
				"type": s3DriverType(opts.S3Driver),
			},
		},
		"item": map[string]any{
			"output": map[string]any{
				"path": "/" + strings.TrimPrefix(bucket, "/"),
			},
		},
		"load": map[string]any{
			"op": map[string]any{
				"type": opType,
			},
			"step": map[string]any{
				"id": stepID,
			},
		},
	}
	if concurrency > 0 {
		setPath(config, concurrency, "storage", "driver", "limit", "concurrency")
	}
	if itemSize != "" {
		setPath(config, itemSize, "item", "data", "size")
	}
	if verify, ok := boolValue(getPath(step.Config, "item", "data", "verify"), vars); ok {
		setPath(config, verify, "item", "data", "verify")
	}
	if queueInput := int64Value(getPath(step.Config, "storage", "driver", "queue", "input"), vars); queueInput > 0 {
		setPath(config, queueInput, "storage", "driver", "queue", "input")
	}
	if duration != "" {
		setPath(config, duration, "load", "step", "limit", "time")
	}
	if count > 0 {
		setPath(config, count, "load", "op", "limit", "count")
	}
	if recycle, ok := boolValue(getPath(step.Config, "load", "generator", "recycle", "enabled"), vars); ok {
		setPath(config, recycle, "load", "op", "recycle", "mode")
	}
	if shuffle, ok := boolValue(getPath(step.Config, "load", "generator", "shuffle"), vars); ok {
		setPath(config, shuffle, "load", "op", "shuffle")
	}

	var rewrites []PathRewrite
	if rawOutput := itemPathString(getPath(step.Config, "item", "output", "file"), vars); rawOutput != "" {
		item := itemFileVariable(rawOutput, archiveToStepID, itemVars, itemVarOrder)
		if item.VarName != "" {
			setPath(config, exprPlaceholder(item.VarName), "item", "output", "file")
			rewrites = append(rewrites, PathRewrite{ArchiveID: item.ArchiveID, StepID: item.StepID, From: item.From, To: item.To})
		} else if pathLabel, _, ok := parseItemFile(rawOutput); ok {
			return convertedStep{}, fmt.Errorf("step %s references unknown item-file path label %s", archiveID, pathLabel)
		} else if item := mongoosePathVariable(rawOutput, itemVars, itemVarOrder); item.VarName != "" {
			setPath(config, exprPlaceholder(item.VarName), "item", "output", "file")
		} else if strings.Contains(rawOutput, "${") {
			return convertedStep{}, fmt.Errorf("step %s has unresolved item output file path %q", archiveID, rawOutput)
		} else {
			setPath(config, rawOutput, "item", "output", "file")
		}
	}
	if rawInput := itemPathString(getPath(step.Config, "item", "input", "file"), vars); rawInput != "" {
		item := itemFileVariable(rawInput, archiveToStepID, itemVars, itemVarOrder)
		if item.VarName != "" {
			setPath(config, exprPlaceholder(item.VarName), "item", "input", "file")
			rewrites = append(rewrites, PathRewrite{ArchiveID: item.ArchiveID, StepID: item.StepID, From: item.From, To: item.To})
		} else if pathLabel, _, ok := parseItemFile(rawInput); ok {
			return convertedStep{}, fmt.Errorf("step %s references unknown item-file path label %s", archiveID, pathLabel)
		} else if item := mongoosePathVariable(rawInput, itemVars, itemVarOrder); item.VarName != "" {
			setPath(config, exprPlaceholder(item.VarName), "item", "input", "file")
		} else if strings.Contains(rawInput, "${") {
			return convertedStep{}, fmt.Errorf("step %s has unresolved item input file path %q", archiveID, rawInput)
		} else {
			setPath(config, rawInput, "item", "input", "file")
		}
	}

	configJS, err := marshalJSConfig(config)
	if err != nil {
		return convertedStep{}, err
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("print(\"[\" + new Date().toISOString() + \"] Starting replay step %s (%s)\");\n", stepID, opType))
	b.WriteString(loadFactory)
	b.WriteString("\n  .config(")
	b.WriteString(configJS)
	b.WriteString(")\n  .run();\n")

	return convertedStep{
		js: b.String(),
		summary: StepSummary{
			ArchiveID:   archiveID,
			StepID:      stepID,
			Operation:   opSuffix,
			Size:        itemSize,
			Concurrency: concurrency,
			Duration:    duration,
			Count:       count,
		},
		rewrites: rewrites,
	}, nil
}

func effectiveVariables(exports map[string]string, opts Options) map[string]string {
	vars := make(map[string]string, len(exports)+16)
	for k, v := range exports {
		vars[k] = v
	}
	hosts := endpointHosts(opts.Endpoints)
	if len(hosts) > 0 {
		rebindIndexedVars(vars, "DATA_NODE", hosts)
		vars["DATA_NODES"] = strings.Join(hosts, ",")
		vars["ALL_NODES"] = strings.Join(hosts, ",")
	}
	clients := splitCSV(opts.TestHosts)
	if len(clients) > 0 {
		rebindIndexedVars(vars, "CLIENT", clients)
		vars["CLIENTS"] = strings.Join(clients, ",")
	}
	return vars
}

func rebindIndexedVars(vars map[string]string, base string, localValues []string) {
	maxIndex := len(localValues)
	for k := range vars {
		if k == base {
			continue
		}
		prefix := base + "_"
		if !strings.HasPrefix(k, prefix) {
			continue
		}
		idx, err := strconv.Atoi(strings.TrimPrefix(k, prefix))
		if err != nil {
			continue
		}
		if idx > maxIndex {
			maxIndex = idx
		}
	}
	vars[base] = localValues[0]
	for i := 2; i <= maxIndex; i++ {
		vars[fmt.Sprintf("%s_%d", base, i)] = localValues[(i-1)%len(localValues)]
	}
}

func endpointHosts(endpoints []string) []string {
	out := make([]string, 0, len(endpoints))
	for _, endpoint := range endpoints {
		endpoint = strings.TrimSpace(endpoint)
		if endpoint == "" {
			continue
		}
		u, err := url.Parse(endpoint)
		if err == nil && u.Hostname() != "" {
			out = append(out, u.Hostname())
			continue
		}
		host := endpoint
		if strings.Contains(host, ":") {
			if h, _, ok := strings.Cut(host, ":"); ok {
				host = h
			}
		}
		out = append(out, host)
	}
	return out
}

func splitCSV(value string) []string {
	parts := strings.Split(value, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		if s := strings.TrimSpace(part); s != "" {
			out = append(out, s)
		}
	}
	return out
}

func writePreludeVars(b *strings.Builder, vars map[string]string) {
	keys := make([]string, 0, len(vars))
	for k := range vars {
		if isSensitiveName(k) || k == "MONGOOSE_DIR" {
			continue
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString("var ")
		b.WriteString(k)
		b.WriteString(" = ")
		b.WriteString(jsQuote(vars[k]))
		b.WriteString(";\n")
	}
}

func isSensitiveName(name string) bool {
	lower := strings.ToLower(name)
	if lower == "key" || lower == "user_id" {
		return true
	}
	return strings.Contains(lower, "secret") ||
		strings.Contains(lower, "password") ||
		strings.Contains(lower, "token") ||
		strings.Contains(lower, "auth") ||
		strings.Contains(lower, "access") ||
		strings.Contains(lower, "key")
}

func itemFileVariable(raw string, archiveToStepID map[string]string, itemVars map[string]itemFileExpr, order *[]string) itemFileExpr {
	archiveID, fileName, ok := parseItemFile(raw)
	if !ok {
		return itemFileExpr{}
	}
	stepID := archiveToStepID[archiveID]
	if stepID == "" {
		return itemFileExpr{}
	}
	key := stepID + "/" + fileName
	if item, ok := itemVars[key]; ok {
		return item
	}
	varName := fmt.Sprintf("itemsFile%03d", len(itemVars)+1)
	item := itemFileExpr{
		VarName:      varName,
		ArchiveID:    archiveID,
		StepID:       stepID,
		FileName:     fileName,
		HomeRelative: "log/" + stepID + "/" + fileName,
		From:         raw,
		To:           "${MONGOOSE_DIR}/log/" + stepID + "/" + fileName,
	}
	itemVars[key] = item
	*order = append(*order, key)
	return item
}

func mongoosePathVariable(raw string, itemVars map[string]itemFileExpr, order *[]string) itemFileExpr {
	homeRelative, ok := parseMongoosePath(raw)
	if !ok {
		return itemFileExpr{}
	}
	key := "mongoose/" + homeRelative
	if item, ok := itemVars[key]; ok {
		return item
	}
	varName := fmt.Sprintf("itemsFile%03d", len(itemVars)+1)
	item := itemFileExpr{
		VarName:      varName,
		HomeRelative: homeRelative,
		From:         raw,
		To:           "${MONGOOSE_DIR}/" + homeRelative,
	}
	itemVars[key] = item
	*order = append(*order, key)
	return item
}

func parseItemFile(raw string) (string, string, bool) {
	m := itemFileRe.FindStringSubmatch(raw)
	if len(m) != 3 {
		return "", "", false
	}
	return m[1], strings.Trim(m[2], `"'`), true
}

func parseMongoosePath(raw string) (string, bool) {
	m := mongoosePathRe.FindStringSubmatch(raw)
	if len(m) != 2 {
		return "", false
	}
	homeRelative := strings.Trim(m[1], `"'`)
	if homeRelative == "" || strings.Contains(homeRelative, "${") {
		return "", false
	}
	return homeRelative, true
}

func parseSleepCommand(value string, vars map[string]string) (int, bool) {
	expanded := strings.TrimSpace(expandWithExports(value, vars))
	fields := strings.Fields(expanded)
	if len(fields) != 2 || fields[0] != "sleep" {
		return 0, false
	}
	seconds, err := strconv.Atoi(fields[1])
	if err != nil || seconds < 0 {
		return 0, false
	}
	return seconds, true
}

func detectUnsupportedProtocols(legacy legacyScenario) []Diagnostic {
	var diagnostics []Diagnostic
	check := func(v any) {
		driver := strings.ToLower(resolveString(v, nil))
		switch driver {
		case "", "s3", "emcs3", "s3-aws", "s3-rdma":
		case "fs":
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "NFS/FS replay is not implemented for storage.driver.type fs"})
		case "atmos", "cas", "swift":
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: fmt.Sprintf("%s replay is not implemented", strings.ToUpper(driver))})
		default:
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: fmt.Sprintf("unsupported storage.driver.type %q", driver)})
		}
	}
	check(getPath(legacy.Config, "storage", "driver", "type"))
	for _, step := range append(append([]legacyStep{}, legacy.Steps...), legacy.Jobs...) {
		if strings.EqualFold(step.Type, "parallel") {
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "parallel scenarios are not implemented for replay"})
		}
		check(getPath(step.Config, "storage", "driver", "type"))
	}
	return diagnostics
}

func effectiveBucket(localBucket string, runScript RunScript) string {
	if strings.TrimSpace(localBucket) != "" {
		return strings.TrimSpace(localBucket)
	}
	if strings.TrimSpace(runScript.ItemOutputPath) != "" {
		return strings.TrimSpace(runScript.ItemOutputPath)
	}
	return strings.TrimSpace(runScript.Exports["BUCKET"])
}

func getPath(m map[string]any, path ...string) any {
	var cur any = m
	for _, p := range path {
		asMap, ok := cur.(map[string]any)
		if !ok {
			return nil
		}
		cur = asMap[p]
	}
	return cur
}

func firstPath(m map[string]any, paths ...[]string) any {
	for _, p := range paths {
		if v := getPath(m, p...); v != nil {
			return v
		}
	}
	return nil
}

func setPath(m map[string]any, value any, path ...string) {
	cur := m
	for _, p := range path[:len(path)-1] {
		next, ok := cur[p].(map[string]any)
		if !ok {
			next = map[string]any{}
			cur[p] = next
		}
		cur = next
	}
	cur[path[len(path)-1]] = value
}

func resolveString(v any, vars map[string]string) string {
	switch t := v.(type) {
	case nil:
		return ""
	case string:
		return expandWithExports(t, vars)
	case json.Number:
		return t.String()
	case float64:
		return strconv.FormatFloat(t, 'f', -1, 64)
	case bool:
		return strconv.FormatBool(t)
	default:
		return fmt.Sprint(t)
	}
}

func intValue(v any, vars map[string]string) int {
	n := int64Value(v, vars)
	if n > int64(^uint(0)>>1) {
		return 0
	}
	return int(n)
}

func int64Value(v any, vars map[string]string) int64 {
	switch t := v.(type) {
	case json.Number:
		n, _ := t.Int64()
		return n
	case float64:
		return int64(t)
	case int:
		return int64(t)
	case int64:
		return t
	case string:
		n, _ := strconv.ParseInt(strings.TrimSpace(expandWithExports(t, vars)), 10, 64)
		return n
	default:
		return 0
	}
}

func boolValue(v any, vars map[string]string) (bool, bool) {
	switch t := v.(type) {
	case bool:
		return t, true
	case string:
		b, err := strconv.ParseBool(strings.TrimSpace(expandWithExports(t, vars)))
		return b, err == nil
	default:
		return false, false
	}
}

func durationValue(v any, vars map[string]string) string {
	s := strings.TrimSpace(resolveString(v, vars))
	if s == "" {
		return ""
	}
	if _, err := strconv.Atoi(s); err == nil {
		return s + "s"
	}
	return s
}

func unresolvedVars(v any, vars map[string]string) []string {
	s, ok := v.(string)
	if !ok || s == "" {
		return nil
	}
	var missing []string
	matches := expandVarRe.FindAllStringSubmatch(s, -1)
	for _, match := range matches {
		if len(match) != 2 {
			continue
		}
		value, ok := vars[match[1]]
		if !ok || strings.TrimSpace(value) == "" {
			missing = append(missing, match[1])
		}
	}
	return missing
}

func requiresExplicitLimit(opType string) bool {
	switch opType {
	case "create", "read":
		return true
	default:
		return false
	}
}

func itemPathString(v any, vars map[string]string) string {
	s, ok := v.(string)
	if !ok {
		return resolveString(v, vars)
	}
	return osExpandPreservingMongooseDir(s, vars)
}

func osExpandPreservingMongooseDir(s string, vars map[string]string) string {
	return osExpand(s, func(key string) string {
		if key == "MONGOOSE_DIR" {
			return "${MONGOOSE_DIR}"
		}
		if vars != nil {
			if v, ok := vars[key]; ok {
				return v
			}
		}
		return ""
	})
}

func osExpand(s string, mapping func(string) string) string {
	return expandVarRe.ReplaceAllStringFunc(s, func(match string) string {
		name := strings.TrimPrefix(match, "$")
		name = strings.Trim(name, "{}")
		return mapping(name)
	})
}

func exprPlaceholder(name string) string {
	return "__SPT_EXPR_" + name + "__"
}

func marshalJSConfig(config map[string]any) (string, error) {
	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return "", err
	}
	out := string(data)
	if unsafeExprSentinelRe.MatchString(out) && !exprPlaceholderRe.MatchString(out) {
		return "", fmt.Errorf("config contains reserved replay expression sentinel")
	}
	out = exprPlaceholderRe.ReplaceAllString(out, `$1`)
	return out, nil
}

func jsQuote(s string) string {
	data, _ := json.Marshal(s)
	return string(data)
}

func jsEscape(s string) string {
	data, _ := json.Marshal(s)
	quoted := string(data)
	return quoted[1 : len(quoted)-1]
}

func jsLineComment(s string) string {
	return strings.ReplaceAll(s, "\n", " ")
}

func s3DriverType(userValue string) string {
	switch strings.ToLower(strings.TrimSpace(userValue)) {
	case "aws":
		return "s3-aws"
	case "rdma":
		return "s3-rdma"
	default:
		return "s3"
	}
}

func sanitizeLabel(label string) string {
	label = strings.TrimSpace(label)
	if label == "" {
		return ""
	}
	var b strings.Builder
	for _, r := range label {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '.' || r == '_' || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

func formatStepID(label string, stepNumber int, baseTS string, op string) string {
	return fmt.Sprintf("%s-%03d-%s-%s", label, stepNumber, baseTS, strings.ToLower(op))
}

func baseTimestamp() string {
	return time.Now().UTC().Format("20060102.150405.000")
}

func hasErrors(diagnostics []Diagnostic) bool {
	for _, d := range diagnostics {
		if d.Severity == severityError {
			return true
		}
	}
	return false
}

func diagnosticsError(diagnostics []Diagnostic) error {
	var messages []string
	for _, d := range diagnostics {
		if d.Severity == severityError {
			messages = append(messages, d.Message)
		}
	}
	if len(messages) == 0 {
		return nil
	}
	return errors.New(strings.Join(messages, "; "))
}

func uniquePathRewrites(rewrites []PathRewrite) []PathRewrite {
	out := make([]PathRewrite, 0, len(rewrites))
	seen := map[string]struct{}{}
	for _, rewrite := range rewrites {
		key := rewrite.From + "\x00" + rewrite.To
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, rewrite)
	}
	return out
}
