// Package replay imports archived benchmark artifacts and converts them into SPT replay workloads.
package replay

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/dell/storage-performance-tool/cli/internal/hostparse"
)

type legacyScenario struct {
	Type   string         `json:"type"`
	Config map[string]any `json:"config"`
	Steps  []legacyStep   `json:"steps"`
	Jobs   []legacyStep   `json:"jobs"`
}

type legacyStep struct {
	Type     string         `json:"type"`
	Config   map[string]any `json:"config"`
	Value    string         `json:"value"`
	Blocking bool           `json:"blocking"`
	Steps    []legacyStep   `json:"steps"`
	Jobs     []legacyStep   `json:"jobs"`
}

type itemFileExpr struct {
	VarName      string
	ArchiveID    string
	StepID       string
	FileName     string
	HomeRelative string
	From         string
	To           string
}

const (
	legacyStepTypeLoad         = "load"
	legacyStepTypeParallel     = "parallel"
	legacyStepTypePrecondition = "precondition"

	legacyMongooseDirVar = "MONGOOSE_DIR"

	legacyKeyConcurrency = "concurrency"
	legacyKeyCount       = "count"
	legacyKeyDriver      = "driver"
	legacyKeyLimit       = "limit"
	legacyKeyStorage     = "storage"
	legacyKeyType        = "type"

	opTypeCreate = "create"
	opTypeDelete = "delete"
	opTypeRead   = "read"
	opTypeSeed   = "seed"
	opTypeUpdate = "update"

	commandActionConverted = "converted"
	commandActionRejected  = "rejected"

	storageDriverTypeS3     = "s3"
	storageDriverTypeEMCS3  = "emcs3"
	storageDriverTypeS3AWS  = "s3-aws"
	storageDriverTypeS3RDMA = "s3-rdma"

	loadFactoryLoad         = "Load"
	loadFactoryPrecondition = "PreconditionLoad"
	loadFactoryRead         = "ReadLoad"
	loadFactoryDelete       = "DeleteLoad"
	loadFactoryUpdate       = "UpdateLoad"

	errParallelReplayUnimplemented = "parallel scenarios are not implemented for replay"
)

var (
	expandVarRe          = regexp.MustCompile(`\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?`)
	exprPlaceholderRe    = regexp.MustCompile(`"__SPT_EXPR_([A-Za-z0-9_]+)__"`)
	catLoopCommandRe     = regexp.MustCompile(`^for\s+[A-Za-z_][A-Za-z0-9_]*\s+in\s+\{1\.\.([0-9]+)\}\s*;\s*do\s+cat\s+(.+?)\s*>>\s*(\S+)\s*;\s*done$`)
	safeCommandArgRe     = regexp.MustCompile(`^[A-Za-z0-9._:-]+$`)
	unsafeExprSentinelRe = regexp.MustCompile(`__SPT_EXPR_[A-Za-z0-9_]+__`)
)

// ConvertJSON converts a supported legacy JSON scenario into SPT JavaScript.
func ConvertJSON(raw []byte, runScript RunScript, opts Options) (*Generated, error) {
	var legacy legacyScenario
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	if err := dec.Decode(&legacy); err != nil {
		return nil, fmt.Errorf("parse legacy JSON scenario: %w", err)
	}

	var diagnostics []Diagnostic
	var pathRewrites []PathRewrite
	var stepsOut []StepSummary
	var commandOps []CommandOperation
	effectiveVars := effectiveVariables(runScript.Exports, opts)
	if len(endpointHosts(opts.Endpoints)) == 0 {
		diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "local endpoints are required for replay"})
	}
	bucket := effectiveBucket(opts.Bucket, runScript)
	if bucket == "" {
		diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "bucket is required; set --bucket, S3_BUCKET, or archived BUCKET"})
	} else {
		effectiveVars["BUCKET"] = bucket
	}

	diagnostics = append(diagnostics, detectUnsupportedProtocols(legacy)...)
	if strings.EqualFold(legacy.Type, legacyStepTypeParallel) {
		diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: errParallelReplayUnimplemented})
	}

	legacySteps := legacy.Steps
	if len(legacySteps) == 0 {
		legacySteps = legacy.Jobs
	}
	if len(legacySteps) == 0 {
		diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "scenario contains no steps or jobs"})
	}

	diagnostics = normalizeDiagnostics(diagnostics)
	if hasErrors(diagnostics) {
		return &Generated{
			Diagnostics:     diagnostics,
			EffectiveBucket: bucket,
		}, diagnosticsError(diagnostics)
	}

	label := sanitizeLabel(opts.Label)
	if label == "" {
		label = defaultLabel
	}
	baseTS := strings.TrimSpace(opts.BaseTimestamp)
	if baseTS == "" {
		baseTS = baseTimestamp()
	}

	archiveToStepID := precomputeArchiveStepIDs(legacySteps, legacy.Config, label, baseTS, effectiveVars)
	itemVars := map[string]itemFileExpr{}
	var itemVarOrder []string
	var body strings.Builder
	body.WriteString("// Generated by spt replay\n")
	body.WriteString("var sptHomeDir = org.apache.logging.log4j.ThreadContext.get(\"home_dir\");\n")
	body.WriteString("if (!sptHomeDir) { sptHomeDir = java.lang.System.getProperty(\"user.dir\"); }\n")
	body.WriteString("var MONGOOSE_DIR = sptHomeDir;\n")
	writePreludeVars(&body, effectiveVars)
	body.WriteString("\n")
	body.WriteString("function pauseSeconds(seconds, message) {\n")
	body.WriteString("  if (message) { print(\"[\" + new Date().toISOString() + \"] \" + message); }\n")
	body.WriteString("  java.lang.Thread.sleep(Number(seconds) * 1000);\n")
	body.WriteString("}\n\n")
	writeReplayProcessHelpers(&body)

	loadStepNumber := 0
	waitNumber := 0
	for i, step := range legacySteps {
		stepType := strings.ToLower(strings.TrimSpace(step.Type))
		switch stepType {
		case legacyStepTypeLoad, legacyStepTypePrecondition:
			loadStepNumber++
			step.Config = mergeConfig(legacy.Config, step.Config)
			converted, err := convertLoadStep(step, i, loadStepNumber, label, baseTS, bucket, opts, effectiveVars, archiveToStepID, itemVars, &itemVarOrder)
			if err != nil {
				diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: err.Error()})
				continue
			}
			diagnostics = append(diagnostics, converted.diagnostics...)
			stepsOut = append(stepsOut, converted.summary)
			pathRewrites = append(pathRewrites, converted.rewrites...)
			body.WriteString(converted.js)
			body.WriteString("\n")
		case "command":
			seconds, ok := parseSleepCommand(step.Value, effectiveVars)
			if ok {
				commandOps = append(commandOps, CommandOperation{
					Action:  commandActionConverted,
					Command: step.Value,
					Detail:  "sleep converted to pauseSeconds",
				})
				waitNumber++
				fmt.Fprintf(&body, "pauseSeconds(%d, %s);\n\n", seconds, jsQuote(fmt.Sprintf("Archived wait %d", waitNumber)))
				continue
			}
			converted, supported, err := convertCommandStep(step.Value, effectiveVars, archiveToStepID)
			if err != nil {
				commandOps = append(commandOps, CommandOperation{
					Action:  commandActionRejected,
					Command: step.Value,
					Detail:  err.Error(),
				})
				diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: err.Error()})
				continue
			}
			if supported {
				commandOps = append(commandOps, CommandOperation{
					Action:  commandActionConverted,
					Command: step.Value,
					Detail:  "safe file command(s) run without a shell",
				})
				pathRewrites = append(pathRewrites, converted.rewrites...)
				body.WriteString(converted.js)
				body.WriteString("\n")
				continue
			}
			commandOps = append(commandOps, CommandOperation{
				Action:  commandActionRejected,
				Command: step.Value,
				Detail:  "not recognized by replay command whitelist",
			})
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: fmt.Sprintf("unsupported command step: %s", step.Value)})
			fmt.Fprintf(&body, "// Unsupported archived command skipped: %s\n\n", jsLineComment(step.Value))
		case legacyStepTypeParallel:
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: errParallelReplayUnimplemented})
		default:
			diagnostics = append(diagnostics, Diagnostic{Severity: severityWarning, Message: fmt.Sprintf("unsupported step type %q skipped", step.Type)})
		}
	}
	if len(stepsOut) == 0 {
		diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "scenario contains no load steps"})
	}
	pathRewrites = uniquePathRewrites(pathRewrites)
	diagnostics = normalizeDiagnostics(diagnostics)
	if hasErrors(diagnostics) {
		return &Generated{
			Diagnostics:     diagnostics,
			Steps:           stepsOut,
			PathRewrites:    pathRewrites,
			CommandOps:      commandOps,
			EffectiveBucket: bucket,
		}, diagnosticsError(diagnostics)
	}

	var prelude strings.Builder
	prelude.WriteString(body.String())
	js := prelude.String()
	if len(itemVarOrder) > 0 {
		var defs strings.Builder
		defs.WriteString("// Canonical item-file paths rewritten from archived step labels.\n")
		for _, key := range itemVarOrder {
			item := itemVars[key]
			if item.StepID != "" && item.FileName != "" {
				fmt.Fprintf(&defs, "var %s = sptHomeDir + \"/log/\" + %s + \"/%s\";\n", item.VarName, jsQuote(item.StepID), jsEscape(item.FileName))
			} else {
				fmt.Fprintf(&defs, "var %s = sptHomeDir + \"/%s\";\n", item.VarName, jsEscape(item.HomeRelative))
			}
		}
		defs.WriteString("\n")
		insertAt := strings.Index(js, "\nfunction pauseSeconds")
		if insertAt >= 0 {
			js = js[:insertAt+1] + defs.String() + js[insertAt+1:]
		}
	}

	return &Generated{
		ScenarioJS:      []byte(js),
		Diagnostics:     diagnostics,
		Steps:           stepsOut,
		PathRewrites:    pathRewrites,
		CommandOps:      commandOps,
		EffectiveBucket: bucket,
	}, nil
}

type convertedStep struct {
	js          string
	summary     StepSummary
	rewrites    []PathRewrite
	diagnostics []Diagnostic
}

type convertedCommand struct {
	js       string
	rewrites []PathRewrite
}

func convertLoadStep(step legacyStep, index, stepNumber int, label, baseTS, bucket string, opts Options, vars map[string]string, archiveToStepID map[string]string, itemVars map[string]itemFileExpr, itemVarOrder *[]string) (convertedStep, error) {
	archiveID, opType, opSuffix, loadFactory, err := loadStepIdentity(step, index, vars)
	if err != nil {
		return convertedStep{}, err
	}
	stepID := archiveToStepID[archiveID]
	if stepID == "" {
		stepID = formatStepID(label, stepNumber, baseTS, opSuffix)
	}
	archiveToStepID[archiveID] = stepID
	diagnostics := ignoredJSONConfigDiagnostics(archiveID, step.Config)

	concurrency := intValue(firstPath(step.Config,
		[]string{legacyStepTypeLoad, legacyKeyLimit, legacyKeyConcurrency},
		[]string{legacyKeyStorage, legacyKeyDriver, legacyKeyLimit, legacyKeyConcurrency},
		[]string{legacyKeyStorage, legacyKeyDriver, legacyKeyConcurrency},
	), vars)
	itemSize := resolveString(getPath(step.Config, "item", "data", "size"), vars)
	limitTimeRaw := getPath(step.Config, "test", "step", legacyKeyLimit, "time")
	limitCountRaw := firstPath(step.Config,
		[]string{"test", "step", legacyKeyLimit, legacyKeyCount},
		[]string{legacyStepTypeLoad, "op", legacyKeyLimit, legacyKeyCount},
		[]string{legacyStepTypeLoad, legacyKeyLimit, legacyKeyCount},
	)
	if missing := unresolvedVars(limitTimeRaw, vars); len(missing) > 0 {
		return convertedStep{}, fmt.Errorf("step %s has unresolved variable %s in time limit", archiveID, missing[0])
	}
	if missing := unresolvedVars(limitCountRaw, vars); len(missing) > 0 {
		return convertedStep{}, fmt.Errorf("step %s has unresolved variable %s in count limit", archiveID, missing[0])
	}
	duration := durationValue(limitTimeRaw, vars)
	count := int64Value(limitCountRaw, vars)
	if requiresExplicitLimit(opType) && duration == "" && count == 0 {
		return convertedStep{}, fmt.Errorf("step %s has no time or count limit", archiveID)
	}

	config := map[string]any{
		legacyKeyStorage: map[string]any{
			legacyKeyDriver: map[string]any{
				legacyKeyType: s3DriverType(opts.S3Driver),
			},
		},
		"item": map[string]any{
			"output": map[string]any{
				"path": "/" + strings.TrimPrefix(bucket, "/"),
			},
		},
		legacyStepTypeLoad: map[string]any{
			"op": map[string]any{
				legacyKeyType: opType,
			},
			"step": map[string]any{
				"id": stepID,
			},
		},
	}
	if concurrency > 0 {
		setPath(config, concurrency, legacyKeyStorage, legacyKeyDriver, legacyKeyLimit, legacyKeyConcurrency)
	}
	if itemSize != "" {
		setPath(config, itemSize, "item", "data", "size")
	}
	if verify, ok := boolValue(getPath(step.Config, "item", "data", "verify"), vars); ok {
		setPath(config, verify, "item", "data", "verify")
	}
	if randomRanges := int64Value(getPath(step.Config, "item", "data", "ranges", "random"), vars); randomRanges > 0 {
		setPath(config, randomRanges, "item", "data", "ranges", "random")
	}
	if queueInput := int64Value(getPath(step.Config, legacyKeyStorage, legacyKeyDriver, "queue", "input"), vars); queueInput > 0 {
		setPath(config, queueInput, legacyKeyStorage, legacyKeyDriver, "queue", "input")
	}
	if failCount := int64Value(firstPath(step.Config,
		[]string{legacyStepTypeLoad, "op", legacyKeyLimit, "fail", legacyKeyCount},
		[]string{"test", "step", legacyKeyLimit, "fail", legacyKeyCount},
	), vars); failCount > 0 {
		setPath(config, failCount, legacyStepTypeLoad, "op", legacyKeyLimit, "fail", legacyKeyCount)
	}
	if duration != "" {
		setPath(config, duration, legacyStepTypeLoad, "step", legacyKeyLimit, "time")
	}
	if count > 0 {
		setPath(config, count, legacyStepTypeLoad, "op", legacyKeyLimit, legacyKeyCount)
	}
	if recycle, ok := boolValue(getPath(step.Config, legacyStepTypeLoad, "generator", "recycle", "enabled"), vars); ok {
		setPath(config, recycle, legacyStepTypeLoad, "op", "recycle", "mode")
	}
	if shuffle, ok := boolValue(getPath(step.Config, legacyStepTypeLoad, "generator", "shuffle"), vars); ok {
		setPath(config, shuffle, legacyStepTypeLoad, "op", "shuffle")
	}
	if threshold, ok := floatValue(firstPath(step.Config,
		[]string{"output", "metrics", "threshold"},
		[]string{"test", "step", "metrics", "threshold"},
	), vars); ok {
		setPath(config, threshold, "output", "metrics", "threshold")
	}
	if enabled, ok := boolValue(firstPath(step.Config,
		[]string{legacyKeyStorage, "net", "ssl", "enabled"},
		[]string{legacyKeyStorage, "net", "ssl"},
	), vars); ok {
		setPath(config, enabled, legacyKeyStorage, "net", "ssl", "enabled")
	}
	if ciphers, ok := stringListValue(getPath(step.Config, legacyKeyStorage, "net", "ssl", "ciphers"), vars); ok {
		setPath(config, ciphers, legacyKeyStorage, "net", "ssl", "ciphers")
	}
	if protocols, ok := stringListValue(getPath(step.Config, legacyKeyStorage, "net", "ssl", "protocols"), vars); ok {
		setPath(config, protocols, legacyKeyStorage, "net", "ssl", "protocols")
	}
	if namedGroups, ok := stringListValue(getPath(step.Config, legacyKeyStorage, "net", "ssl", "namedGroups"), vars); ok {
		setPath(config, namedGroups, legacyKeyStorage, "net", "ssl", "namedGroups")
	}
	if provider := resolveString(getPath(step.Config, legacyKeyStorage, "net", "ssl", "provider"), vars); provider != "" {
		setPath(config, provider, legacyKeyStorage, "net", "ssl", "provider")
	}
	if jsseProvider := resolveString(getPath(step.Config, legacyKeyStorage, "net", "ssl", "jsseProvider"), vars); jsseProvider != "" {
		setPath(config, jsseProvider, legacyKeyStorage, "net", "ssl", "jsseProvider")
	}
	if pqcMode := resolveString(getPath(step.Config, legacyKeyStorage, "net", "ssl", "pqcMode"), vars); pqcMode != "" {
		setPath(config, pqcMode, legacyKeyStorage, "net", "ssl", "pqcMode")
	}

	var rewrites []PathRewrite
	if rawOutput := itemPathString(getPath(step.Config, "item", "output", "file"), vars); rawOutput != "" {
		item := itemFileVariable(rawOutput, archiveToStepID, itemVars, itemVarOrder)
		if item.VarName != "" {
			setPath(config, exprPlaceholder(item.VarName), "item", "output", "file")
			rewrites = append(rewrites, PathRewrite{ArchiveID: item.ArchiveID, StepID: item.StepID, From: item.From, To: item.To})
		} else if pathLabel, _, ok := parseItemFile(rawOutput); ok {
			return convertedStep{}, fmt.Errorf("step %s references unknown item-file path label %s", archiveID, pathLabel)
		} else if item := mongoosePathVariable(rawOutput, itemVars, itemVarOrder); item.VarName != "" {
			setPath(config, exprPlaceholder(item.VarName), "item", "output", "file")
		} else if strings.Contains(rawOutput, "${") {
			return convertedStep{}, fmt.Errorf("step %s has unresolved item output file path %q", archiveID, rawOutput)
		} else {
			setPath(config, rawOutput, "item", "output", "file")
		}
	}
	if rawInput := itemPathString(getPath(step.Config, "item", "input", "file"), vars); rawInput != "" {
		item := itemFileVariable(rawInput, archiveToStepID, itemVars, itemVarOrder)
		if item.VarName != "" {
			setPath(config, exprPlaceholder(item.VarName), "item", "input", "file")
			rewrites = append(rewrites, PathRewrite{ArchiveID: item.ArchiveID, StepID: item.StepID, From: item.From, To: item.To})
		} else if pathLabel, _, ok := parseItemFile(rawInput); ok {
			return convertedStep{}, fmt.Errorf("step %s references unknown item-file path label %s", archiveID, pathLabel)
		} else if item := mongoosePathVariable(rawInput, itemVars, itemVarOrder); item.VarName != "" {
			setPath(config, exprPlaceholder(item.VarName), "item", "input", "file")
		} else if strings.Contains(rawInput, "${") {
			return convertedStep{}, fmt.Errorf("step %s has unresolved item input file path %q", archiveID, rawInput)
		} else {
			setPath(config, rawInput, "item", "input", "file")
		}
	}

	configJS, err := marshalJSConfig(config)
	if err != nil {
		return convertedStep{}, err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "print(\"[\" + new Date().toISOString() + \"] Starting replay step %s (%s)\");\n", stepID, opType)
	b.WriteString(loadFactory)
	b.WriteString("\n  .config(")
	b.WriteString(configJS)
	b.WriteString(")\n  .run();\n")

	return convertedStep{
		js: b.String(),
		summary: StepSummary{
			ArchiveID:   archiveID,
			StepID:      stepID,
			Operation:   opSuffix,
			Size:        itemSize,
			Concurrency: concurrency,
			Duration:    duration,
			Count:       count,
		},
		rewrites:    rewrites,
		diagnostics: diagnostics,
	}, nil
}

func precomputeArchiveStepIDs(steps []legacyStep, baseConfig map[string]any, label, baseTS string, vars map[string]string) map[string]string {
	archiveToStepID := map[string]string{}
	loadStepNumber := 0
	for i, step := range steps {
		stepType := strings.ToLower(strings.TrimSpace(step.Type))
		if stepType != legacyStepTypeLoad && stepType != legacyStepTypePrecondition {
			continue
		}
		loadStepNumber++
		step.Config = mergeConfig(baseConfig, step.Config)
		archiveID, _, opSuffix, _, err := loadStepIdentity(step, i, vars)
		if err != nil {
			continue
		}
		archiveToStepID[archiveID] = formatStepID(label, loadStepNumber, baseTS, opSuffix)
	}
	return archiveToStepID
}

func loadStepIdentity(step legacyStep, index int, vars map[string]string) (string, string, string, string, error) {
	archiveID := resolveString(getPath(step.Config, "test", "step", "id"), vars)
	if archiveID == "" {
		archiveID = fmt.Sprintf("archive-step-%03d", index+1)
	}
	opType := strings.ToLower(resolveString(firstPath(step.Config,
		[]string{legacyStepTypeLoad, "op", legacyKeyType},
		[]string{legacyStepTypeLoad, legacyKeyType},
	), vars))
	if strings.EqualFold(step.Type, legacyStepTypePrecondition) {
		return archiveID, opTypeCreate, opTypeSeed, loadFactoryPrecondition, nil
	}
	switch opType {
	case "", opTypeCreate, "write":
		return archiveID, opTypeCreate, opTypeCreate, loadFactoryLoad, nil
	case opTypeRead:
		return archiveID, opTypeRead, opTypeRead, loadFactoryRead, nil
	case opTypeUpdate:
		return archiveID, opTypeUpdate, opTypeUpdate, loadFactoryUpdate, nil
	case opTypeDelete:
		return archiveID, opTypeDelete, opTypeDelete, loadFactoryDelete, nil
	default:
		return archiveID, "", "", "", fmt.Errorf("unsupported load operation %q in step %s", opType, archiveID)
	}
}

func mergeConfig(base, override map[string]any) map[string]any {
	out := cloneConfigMap(base)
	for k, v := range override {
		if baseMap, ok := out[k].(map[string]any); ok {
			if overrideMap, ok := v.(map[string]any); ok {
				out[k] = mergeConfig(baseMap, overrideMap)
				continue
			}
		}
		out[k] = cloneConfigValue(v)
	}
	return out
}

func cloneConfigMap(src map[string]any) map[string]any {
	out := make(map[string]any, len(src))
	for k, v := range src {
		out[k] = cloneConfigValue(v)
	}
	return out
}

func cloneConfigValue(value any) any {
	switch t := value.(type) {
	case map[string]any:
		return cloneConfigMap(t)
	case []any:
		out := make([]any, len(t))
		for i, v := range t {
			out[i] = cloneConfigValue(v)
		}
		return out
	default:
		return value
	}
}

func ignoredJSONConfigDiagnostics(archiveID string, config map[string]any) []Diagnostic {
	paths := ignoredJSONConfigPaths(config)
	if len(paths) == 0 {
		return nil
	}
	diagnostics := make([]Diagnostic, 0, len(paths))
	for _, path := range paths {
		diagnostics = append(diagnostics, Diagnostic{
			Severity: severityWarning,
			Message:  fmt.Sprintf("step %s ignores unmodeled JSON config path %s", archiveID, path),
		})
	}
	return diagnostics
}

func ignoredJSONConfigPaths(config map[string]any) []string {
	var leaves []string
	collectConfigLeafPaths(config, nil, &leaves)
	ignored := map[string]struct{}{}
	for _, path := range leaves {
		switch {
		case isModeledJSONConfigPath(path):
			continue
		case hasJSONConfigPathPrefix(path, "item.naming"):
			ignored["item.naming"] = struct{}{}
		case hasJSONConfigPathPrefix(path, "storage.net.http"):
			ignored["storage.net.http"] = struct{}{}
		default:
			ignored[path] = struct{}{}
		}
	}
	out := make([]string, 0, len(ignored))
	for path := range ignored {
		out = append(out, path)
	}
	sort.Strings(out)
	return out
}

func collectConfigLeafPaths(value any, path []string, out *[]string) {
	switch t := value.(type) {
	case map[string]any:
		if len(t) == 0 && len(path) > 0 {
			*out = append(*out, strings.Join(path, "."))
			return
		}
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			collectConfigLeafPaths(t[k], append(path, k), out)
		}
	case []any:
		if len(path) > 0 {
			*out = append(*out, strings.Join(path, "."))
		}
	default:
		if len(path) > 0 {
			*out = append(*out, strings.Join(path, "."))
		}
	}
}

func isModeledJSONConfigPath(path string) bool {
	switch path {
	case "item.data.size",
		"item.data.ranges.random",
		"item.data.verify",
		"item.input.file",
		"item.input.path",
		"item.output.file",
		"item.output.path",
		"load.generator.recycle.enabled",
		"load.generator.shuffle",
		"load.limit.concurrency",
		"load.op.limit.fail.count",
		"load.op.limit.count",
		"load.op.type",
		"load.type",
		"output.metrics.threshold",
		"storage.driver.concurrency",
		"storage.driver.limit.concurrency",
		"storage.driver.queue.input",
		"storage.driver.type",
		"storage.net.ssl",
		"storage.net.ssl.ciphers",
		"storage.net.ssl.enabled",
		"storage.net.ssl.jsseProvider",
		"storage.net.ssl.namedGroups",
		"storage.net.ssl.pqcMode",
		"storage.net.ssl.protocols",
		"storage.net.ssl.provider",
		"storage.net.node.addrs",
		"storage.net.node.port",
		"test.step.id",
		"test.step.limit.fail.count",
		"test.step.limit.count",
		"test.step.metrics.threshold",
		"test.step.limit.time":
		return true
	default:
		return false
	}
}

func hasJSONConfigPathPrefix(path, prefix string) bool {
	return path == prefix || strings.HasPrefix(path, prefix+".")
}

func effectiveVariables(exports map[string]string, opts Options) map[string]string {
	vars := make(map[string]string, len(exports)+16)
	for k, v := range exports {
		vars[k] = v
	}
	hosts := endpointHosts(opts.Endpoints)
	if len(hosts) > 0 {
		rebindIndexedVars(vars, "DATA_NODE", hosts)
		vars["DATA_NODES"] = strings.Join(hosts, ",")
		vars["ALL_NODES"] = strings.Join(hosts, ",")
	}
	clients := testHostnames(opts.TestHosts)
	if len(clients) > 0 {
		rebindIndexedVars(vars, "CLIENT", clients)
		vars["CLIENTS"] = strings.Join(clients, ",")
	}
	return vars
}

func testHostnames(testHosts string) []string {
	hostInfos, err := hostparse.ParseTestHosts(testHosts)
	if err == nil && len(hostInfos) > 0 {
		hosts := make([]string, 0, len(hostInfos))
		for _, info := range hostInfos {
			if info != nil && strings.TrimSpace(info.Host) != "" {
				hosts = append(hosts, info.Host)
			}
		}
		if len(hosts) > 0 {
			return hosts
		}
	}

	rawHosts := splitCSV(testHosts)
	hosts := make([]string, 0, len(rawHosts))
	for _, raw := range rawHosts {
		host := raw
		if _, after, ok := strings.Cut(raw, "@"); ok {
			host = after
		}
		if strings.TrimSpace(host) != "" {
			hosts = append(hosts, strings.TrimSpace(host))
		}
	}
	return hosts
}

func rebindIndexedVars(vars map[string]string, base string, localValues []string) {
	maxIndex := len(localValues)
	for k := range vars {
		if k == base {
			continue
		}
		prefix := base + "_"
		if !strings.HasPrefix(k, prefix) {
			continue
		}
		idx, err := strconv.Atoi(strings.TrimPrefix(k, prefix))
		if err != nil {
			continue
		}
		if idx > maxIndex {
			maxIndex = idx
		}
	}
	vars[base] = localValues[0]
	for i := 2; i <= maxIndex; i++ {
		vars[fmt.Sprintf("%s_%d", base, i)] = localValues[(i-1)%len(localValues)]
	}
}

func endpointHosts(endpoints []string) []string {
	out := make([]string, 0, len(endpoints))
	for _, endpoint := range endpoints {
		endpoint = strings.TrimSpace(endpoint)
		if endpoint == "" {
			continue
		}
		u, err := url.Parse(endpoint)
		if err == nil && u.Hostname() != "" {
			out = append(out, u.Hostname())
			continue
		}
		host := endpoint
		if strings.Contains(host, ":") {
			if h, _, ok := strings.Cut(host, ":"); ok {
				host = h
			}
		}
		out = append(out, host)
	}
	return out
}

func splitCSV(value string) []string {
	parts := strings.Split(value, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		if s := strings.TrimSpace(part); s != "" {
			out = append(out, s)
		}
	}
	return out
}

func writePreludeVars(b *strings.Builder, vars map[string]string) {
	keys := make([]string, 0, len(vars))
	for k := range vars {
		if isSensitiveName(k) || k == legacyMongooseDirVar {
			continue
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString("var ")
		b.WriteString(k)
		b.WriteString(" = ")
		b.WriteString(jsQuote(vars[k]))
		b.WriteString(";\n")
	}
}

func writeReplayProcessHelpers(b *strings.Builder) {
	b.WriteString("function runReplayProcess(command, args, cwd) {\n")
	b.WriteString("  var commandLine = new java.util.ArrayList();\n")
	b.WriteString("  commandLine.add(String(command));\n")
	b.WriteString("  for (var i = 0; i < args.length; i++) { commandLine.add(String(args[i])); }\n")
	b.WriteString("  var processBuilder = new java.lang.ProcessBuilder(commandLine);\n")
	b.WriteString("  if (cwd) { processBuilder.directory(new java.io.File(String(cwd))); }\n")
	b.WriteString("  processBuilder.redirectErrorStream(true);\n")
	b.WriteString("  var process = processBuilder.start();\n")
	b.WriteString("  var reader = new java.io.BufferedReader(new java.io.InputStreamReader(process.getInputStream()));\n")
	b.WriteString("  var line;\n")
	b.WriteString("  while ((line = reader.readLine()) !== null) { if (line.length() > 0) { print(line); } }\n")
	b.WriteString("  var exitCode = process.waitFor();\n")
	b.WriteString("  if (exitCode !== 0) { throw \"Replay command failed (\" + exitCode + \"): \" + command + \" \" + args.join(\" \"); }\n")
	b.WriteString("}\n\n")
	b.WriteString("function runReplayProcessToFile(command, args, cwd, outputPath, append) {\n")
	b.WriteString("  var commandLine = new java.util.ArrayList();\n")
	b.WriteString("  commandLine.add(String(command));\n")
	b.WriteString("  for (var i = 0; i < args.length; i++) { commandLine.add(String(args[i])); }\n")
	b.WriteString("  var processBuilder = new java.lang.ProcessBuilder(commandLine);\n")
	b.WriteString("  if (cwd) { processBuilder.directory(new java.io.File(String(cwd))); }\n")
	b.WriteString("  var outputFile = new java.io.File(String(outputPath));\n")
	b.WriteString("  var parentDir = outputFile.getParentFile();\n")
	b.WriteString("  if (parentDir) { parentDir.mkdirs(); }\n")
	b.WriteString("  var redirect = append ? java.lang.ProcessBuilder.Redirect.appendTo(outputFile) : java.lang.ProcessBuilder.Redirect.to(outputFile);\n")
	b.WriteString("  processBuilder.redirectOutput(redirect);\n")
	b.WriteString("  processBuilder.redirectError(java.lang.ProcessBuilder.Redirect.INHERIT);\n")
	b.WriteString("  var exitCode = processBuilder.start().waitFor();\n")
	b.WriteString("  if (exitCode !== 0) { throw \"Replay command failed (\" + exitCode + \"): \" + command + \" \" + args.join(\" \"); }\n")
	b.WriteString("}\n\n")
}

func isSensitiveName(name string) bool {
	lower := strings.ToLower(name)
	if lower == "key" || lower == "user_id" {
		return true
	}
	return strings.Contains(lower, "secret") ||
		strings.Contains(lower, "password") ||
		strings.Contains(lower, "token") ||
		strings.Contains(lower, "auth") ||
		strings.Contains(lower, "access") ||
		strings.Contains(lower, "key")
}

func itemFileVariable(raw string, archiveToStepID map[string]string, itemVars map[string]itemFileExpr, order *[]string) itemFileExpr {
	archiveID, fileName, ok := parseItemFile(raw)
	if !ok {
		return itemFileExpr{}
	}
	stepID := archiveToStepID[archiveID]
	if stepID == "" {
		return itemFileExpr{}
	}
	key := stepID + "/" + fileName
	if item, ok := itemVars[key]; ok {
		return item
	}
	varName := fmt.Sprintf("itemsFile%03d", len(itemVars)+1)
	item := itemFileExpr{
		VarName:      varName,
		ArchiveID:    archiveID,
		StepID:       stepID,
		FileName:     fileName,
		HomeRelative: "log/" + stepID + "/" + fileName,
		From:         raw,
		To:           "${MONGOOSE_DIR}/log/" + stepID + "/" + fileName,
	}
	itemVars[key] = item
	*order = append(*order, key)
	return item
}

func mongoosePathVariable(raw string, itemVars map[string]itemFileExpr, order *[]string) itemFileExpr {
	homeRelative, ok := parseMongoosePath(raw)
	if !ok {
		return itemFileExpr{}
	}
	key := "mongoose/" + homeRelative
	if item, ok := itemVars[key]; ok {
		return item
	}
	varName := fmt.Sprintf("itemsFile%03d", len(itemVars)+1)
	item := itemFileExpr{
		VarName:      varName,
		HomeRelative: homeRelative,
		From:         raw,
		To:           "${MONGOOSE_DIR}/" + homeRelative,
	}
	itemVars[key] = item
	*order = append(*order, key)
	return item
}

func parseItemFile(raw string) (string, string, bool) {
	homeRelative, ok := normalizeArchivedMongoosePath(raw)
	if !ok || !strings.HasPrefix(homeRelative, "log/") {
		return "", "", false
	}
	archiveID, fileName, ok := strings.Cut(strings.TrimPrefix(homeRelative, "log/"), "/")
	if !ok || archiveID == "" || fileName == "" || strings.Contains(archiveID, "/") || strings.Contains(fileName, "/") {
		return "", "", false
	}
	return archiveID, fileName, true
}

func parseItemDir(raw string) (string, bool) {
	homeRelative, ok := normalizeArchivedMongoosePath(raw)
	if !ok || !strings.HasPrefix(homeRelative, "log/") {
		return "", false
	}
	archiveID := strings.TrimPrefix(homeRelative, "log/")
	if archiveID == "" || strings.Contains(archiveID, "/") {
		return "", false
	}
	return archiveID, true
}

func parseMongoosePath(raw string) (string, bool) {
	homeRelative, ok := normalizeArchivedMongoosePath(raw)
	return homeRelative, ok
}

func normalizeArchivedMongoosePath(raw string) (string, bool) {
	pathValue := strings.Trim(strings.TrimSpace(raw), `"'`)
	if pathValue == "" {
		return "", false
	}
	var homeRelative string
	switch {
	case strings.HasPrefix(pathValue, "${"+legacyMongooseDirVar+"}/"):
		homeRelative = strings.TrimPrefix(pathValue, "${"+legacyMongooseDirVar+"}/")
	case strings.HasPrefix(pathValue, "/opt/mongoose/current/"):
		homeRelative = strings.TrimPrefix(pathValue, "/opt/mongoose/current/")
	case strings.HasPrefix(pathValue, "/opt/mongoose/"):
		homeRelative = strings.TrimPrefix(pathValue, "/opt/mongoose/")
	default:
		return "", false
	}
	if homeRelative == "" || strings.Contains(homeRelative, "${") || strings.Contains(homeRelative, "..") {
		return "", false
	}
	return homeRelative, true
}

func parseSleepCommand(value string, vars map[string]string) (int, bool) {
	expanded := strings.TrimSpace(expandWithExports(value, vars))
	fields := strings.Fields(expanded)
	if len(fields) != 2 || fields[0] != "sleep" {
		return 0, false
	}
	duration := strings.TrimSuffix(fields[1], "s")
	seconds, err := strconv.Atoi(duration)
	if err != nil || seconds < 0 {
		return 0, false
	}
	return seconds, true
}

func convertCommandStep(value string, vars map[string]string, archiveToStepID map[string]string) (convertedCommand, bool, error) {
	if missing := unresolvedCommandVars(value, vars); len(missing) > 0 {
		return convertedCommand{}, true, fmt.Errorf("command step has unresolved variable %s", missing[0])
	}
	expanded := strings.TrimSpace(osExpandPreservingMongooseDir(value, vars))
	if expanded == "" {
		return convertedCommand{}, false, nil
	}
	if missing := unresolvedCommandVars(expanded, vars); len(missing) > 0 {
		return convertedCommand{}, true, fmt.Errorf("command step has unresolved variable %s", missing[0])
	}
	segments := splitCommandSegments(expanded)
	if len(segments) == 0 {
		return convertedCommand{}, false, nil
	}

	cwdExpr := "sptHomeDir"
	var rewrites []PathRewrite
	firstFields := strings.Fields(segments[0])
	if len(firstFields) > 0 && firstFields[0] == "cd" {
		if len(firstFields) != 2 {
			return convertedCommand{}, true, fmt.Errorf("unsupported command working directory: %s", segments[0])
		}
		expr, rewrite, hasRewrite, err := commandWorkDirExpr(firstFields[1], archiveToStepID)
		if err != nil {
			return convertedCommand{}, true, err
		}
		cwdExpr = expr
		if hasRewrite {
			rewrites = append(rewrites, rewrite)
		}
		segments = segments[1:]
	}
	if len(segments) == 0 {
		return convertedCommand{}, false, nil
	}
	if js, loopRewrites, ok, err := maybeConvertCatLoopCommand(strings.Join(segments, "; "), value, cwdExpr, archiveToStepID); ok || err != nil {
		if err != nil {
			return convertedCommand{}, true, err
		}
		rewrites = append(rewrites, loopRewrites...)
		return convertedCommand{js: js, rewrites: rewrites}, true, nil
	}

	var b strings.Builder
	for _, segment := range segments {
		js, segmentRewrites, supported, err := convertCommandSegment(segment, value, cwdExpr, archiveToStepID)
		if err != nil {
			return convertedCommand{}, true, err
		}
		if !supported {
			return convertedCommand{}, false, nil
		}
		rewrites = append(rewrites, segmentRewrites...)
		b.WriteString(js)
	}
	if b.Len() == 0 {
		return convertedCommand{}, false, nil
	}
	return convertedCommand{js: b.String(), rewrites: rewrites}, true, nil
}

func convertCommandSegment(segment, stepValue, cwdExpr string, archiveToStepID map[string]string) (string, []PathRewrite, bool, error) {
	fields := strings.Fields(segment)
	if len(fields) == 0 {
		return "", nil, false, nil
	}
	if js, rewrites, ok, err := maybeConvertSedRedirectCommand(fields, stepValue, cwdExpr, archiveToStepID); ok || err != nil {
		return js, rewrites, true, err
	}
	if js, rewrites, ok, err := maybeConvertShufRedirectCommand(fields, stepValue, cwdExpr, archiveToStepID); ok || err != nil {
		return js, rewrites, true, err
	}
	if js, rewrites, ok, err := maybeConvertCatRedirectCommand(fields, stepValue, cwdExpr, archiveToStepID); ok || err != nil {
		return js, rewrites, true, err
	}
	if js, ok := maybeConvertRMCommand(fields, cwdExpr); ok {
		return js, nil, true, nil
	}
	if !isAllowedReplayCommand(fields[0]) {
		return "", nil, false, nil
	}
	argExprs, rewrites, err := commandArgExprs(fields[1:], stepValue, archiveToStepID)
	if err != nil {
		return "", rewrites, true, err
	}
	return fmt.Sprintf("runReplayProcess(%s, [%s], %s);\n", jsQuote(fields[0]), strings.Join(argExprs, ", "), cwdExpr), rewrites, true, nil
}

func maybeConvertSedRedirectCommand(fields []string, stepValue, cwdExpr string, archiveToStepID map[string]string) (string, []PathRewrite, bool, error) {
	if len(fields) == 0 || fields[0] != "sed" {
		return "", nil, false, nil
	}
	if len(fields) < 5 || fields[len(fields)-2] != ">" {
		return "", nil, false, nil
	}
	sedArgs := fields[1 : len(fields)-3]
	if len(sedArgs) == 0 {
		return "", nil, false, nil
	}
	argExprs := make([]string, 0, len(sedArgs)+1)
	for _, raw := range sedArgs {
		arg := unquoteCommandToken(raw)
		if arg == "" {
			return "", nil, true, fmt.Errorf("unsupported command argument %q in step: %s", raw, stepValue)
		}
		argExprs = append(argExprs, jsQuote(arg))
	}
	inputExprs, rewrites, err := commandArgExprs([]string{fields[len(fields)-3]}, stepValue, archiveToStepID)
	if err != nil {
		return "", rewrites, true, err
	}
	outputExpr, rewrite, hasRewrite, supported, err := commandOutputExpr(fields[len(fields)-1], cwdExpr, archiveToStepID)
	if err != nil {
		return "", rewrites, true, err
	}
	if !supported {
		return "", rewrites, true, fmt.Errorf("unsupported command argument %q in step: %s", fields[len(fields)-1], stepValue)
	}
	if hasRewrite {
		rewrites = append(rewrites, rewrite)
	}
	args := append(argExprs, inputExprs...)
	return fmt.Sprintf("runReplayProcessToFile(%s, [%s], %s, %s, false);\n", jsQuote("sed"), strings.Join(args, ", "), cwdExpr, outputExpr), rewrites, true, nil
}

func maybeConvertShufRedirectCommand(fields []string, stepValue, cwdExpr string, archiveToStepID map[string]string) (string, []PathRewrite, bool, error) {
	if len(fields) != 4 || fields[0] != "shuf" || fields[2] != ">" {
		return "", nil, false, nil
	}
	inputExprs, rewrites, err := commandArgExprs([]string{fields[1]}, stepValue, archiveToStepID)
	if err != nil {
		return "", rewrites, true, err
	}
	outputExpr, rewrite, hasRewrite, supported, err := commandOutputExpr(fields[3], cwdExpr, archiveToStepID)
	if err != nil {
		return "", rewrites, true, err
	}
	if !supported {
		return "", rewrites, true, fmt.Errorf("unsupported command argument %q in step: %s", fields[3], stepValue)
	}
	if hasRewrite {
		rewrites = append(rewrites, rewrite)
	}
	return fmt.Sprintf("runReplayProcessToFile(%s, [%s], %s, %s, false);\n", jsQuote("shuf"), strings.Join(inputExprs, ", "), cwdExpr, outputExpr), rewrites, true, nil
}

func maybeConvertCatRedirectCommand(fields []string, stepValue, cwdExpr string, archiveToStepID map[string]string) (string, []PathRewrite, bool, error) {
	if len(fields) == 0 || fields[0] != "cat" {
		return "", nil, false, nil
	}
	redirectIndex := -1
	appendMode := false
	for i := 1; i < len(fields)-1; i++ {
		switch fields[i] {
		case ">":
			redirectIndex = i
		case ">>":
			redirectIndex = i
			appendMode = true
		}
		if redirectIndex >= 0 {
			break
		}
	}
	if redirectIndex < 0 || redirectIndex == 1 || redirectIndex != len(fields)-2 {
		return "", nil, false, nil
	}
	inputExprs, rewrites, err := commandArgExprs(fields[1:redirectIndex], stepValue, archiveToStepID)
	if err != nil {
		return "", rewrites, true, err
	}
	outputExpr, rewrite, hasRewrite, supported, err := commandOutputExpr(fields[len(fields)-1], cwdExpr, archiveToStepID)
	if err != nil {
		return "", rewrites, true, err
	}
	if !supported {
		return "", rewrites, true, fmt.Errorf("unsupported command argument %q in step: %s", fields[len(fields)-1], stepValue)
	}
	if hasRewrite {
		rewrites = append(rewrites, rewrite)
	}
	return fmt.Sprintf("runReplayProcessToFile(%s, [%s], %s, %s, %t);\n", jsQuote("cat"), strings.Join(inputExprs, ", "), cwdExpr, outputExpr, appendMode), rewrites, true, nil
}

func maybeConvertCatLoopCommand(command, stepValue, cwdExpr string, archiveToStepID map[string]string) (string, []PathRewrite, bool, error) {
	match := catLoopCommandRe.FindStringSubmatch(strings.TrimSpace(command))
	if len(match) != 4 {
		return "", nil, false, nil
	}
	count, err := strconv.Atoi(match[1])
	if err != nil || count <= 0 {
		return "", nil, true, fmt.Errorf("unsupported cat loop count %q in step: %s", match[1], stepValue)
	}
	inputExprs, rewrites, err := commandArgExprs([]string{match[2]}, stepValue, archiveToStepID)
	if err != nil {
		return "", rewrites, true, err
	}
	outputExpr, rewrite, hasRewrite, supported, err := commandOutputExpr(match[3], cwdExpr, archiveToStepID)
	if err != nil {
		return "", rewrites, true, err
	}
	if !supported {
		return "", rewrites, true, fmt.Errorf("unsupported command argument %q in step: %s", match[3], stepValue)
	}
	if hasRewrite {
		rewrites = append(rewrites, rewrite)
	}
	return fmt.Sprintf("for (var replayCatLoop = 0; replayCatLoop < %d; replayCatLoop++) {\n  runReplayProcessToFile(%s, [%s], %s, %s, true);\n}\n", count, jsQuote("cat"), strings.Join(inputExprs, ", "), cwdExpr, outputExpr), rewrites, true, nil
}

func maybeConvertRMCommand(fields []string, cwdExpr string) (string, bool) {
	if len(fields) == 0 || fields[0] != "rm" {
		return "", false
	}
	if len(fields) < 2 {
		return "", false
	}
	args := make([]string, 0, len(fields)-1)
	for _, raw := range fields[1:] {
		arg := unquoteCommandToken(raw)
		if arg == "" || strings.HasPrefix(arg, "-") || strings.Contains(arg, "/") || strings.Contains(arg, "..") || !safeCommandArgRe.MatchString(arg) {
			return "", false
		}
		args = append(args, jsQuote(arg))
	}
	return fmt.Sprintf("runReplayProcess(%s, [%s], %s);\n", jsQuote("rm"), strings.Join(args, ", "), cwdExpr), true
}

func splitCommandSegments(value string) []string {
	raw := strings.Split(value, ";")
	segments := make([]string, 0, len(raw))
	for _, segment := range raw {
		segment = strings.TrimSpace(segment)
		if segment != "" {
			segments = append(segments, segment)
		}
	}
	return segments
}

func unresolvedCommandVars(value string, vars map[string]string) []string {
	var missing []string
	seen := map[string]struct{}{}
	matches := expandVarRe.FindAllStringSubmatch(value, -1)
	for _, match := range matches {
		if len(match) != 2 || match[1] == legacyMongooseDirVar {
			continue
		}
		name := match[1]
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		value, ok := vars[name]
		if !ok || strings.TrimSpace(value) == "" {
			missing = append(missing, name)
		}
	}
	return missing
}

func commandArgExprs(args []string, stepValue string, archiveToStepID map[string]string) ([]string, []PathRewrite, error) {
	exprs := make([]string, 0, len(args))
	var rewrites []PathRewrite
	for _, raw := range args {
		expr, rewrite, hasRewrite, supported, err := commandArgExpr(raw, archiveToStepID)
		if err != nil {
			return nil, rewrites, err
		}
		if !supported {
			return nil, rewrites, fmt.Errorf("unsupported command argument %q in step: %s", raw, stepValue)
		}
		exprs = append(exprs, expr)
		if hasRewrite {
			rewrites = append(rewrites, rewrite)
		}
	}
	return exprs, rewrites, nil
}

func commandArgExpr(raw string, archiveToStepID map[string]string) (string, PathRewrite, bool, bool, error) {
	value := unquoteCommandToken(raw)
	if value == "" {
		return "", PathRewrite{}, false, false, nil
	}
	if archiveID, fileName, ok := parseItemFile(value); ok {
		stepID := archiveToStepID[archiveID]
		if stepID == "" {
			return "", PathRewrite{}, false, false, fmt.Errorf("command step references unknown path label %s", archiveID)
		}
		return `sptHomeDir + "/log/" + ` + jsQuote(stepID) + ` + "/` + jsEscape(fileName) + `"`, PathRewrite{
			ArchiveID: archiveID,
			StepID:    stepID,
			From:      value,
			To:        "${MONGOOSE_DIR}/log/" + stepID + "/" + fileName,
		}, true, true, nil
	}
	if homeRelative, ok := parseMongoosePath(value); ok {
		return `sptHomeDir + "/` + jsEscape(homeRelative) + `"`, PathRewrite{}, false, true, nil
	}
	if !isSafeReplayCommandArg(value) {
		return "", PathRewrite{}, false, false, nil
	}
	return jsQuote(value), PathRewrite{}, false, true, nil
}

func commandOutputExpr(raw, cwdExpr string, archiveToStepID map[string]string) (string, PathRewrite, bool, bool, error) {
	expr, rewrite, hasRewrite, supported, err := commandArgExpr(raw, archiveToStepID)
	if err != nil || !supported {
		return expr, rewrite, hasRewrite, supported, err
	}
	value := unquoteCommandToken(raw)
	if value == "" || strings.HasPrefix(value, "/") || strings.Contains(value, "..") || !safeCommandArgRe.MatchString(value) {
		return expr, rewrite, hasRewrite, supported, nil
	}
	return cwdExpr + ` + "/` + jsEscape(value) + `"`, rewrite, hasRewrite, true, nil
}

func unquoteCommandToken(raw string) string {
	raw = strings.TrimSpace(raw)
	if len(raw) >= 2 {
		if (raw[0] == '\'' && raw[len(raw)-1] == '\'') || (raw[0] == '"' && raw[len(raw)-1] == '"') {
			return raw[1 : len(raw)-1]
		}
	}
	return raw
}

func commandWorkDirExpr(raw string, archiveToStepID map[string]string) (string, PathRewrite, bool, error) {
	pathValue := strings.Trim(strings.TrimSpace(raw), `"'`)
	if pathValue == "" {
		return "", PathRewrite{}, false, fmt.Errorf("unsupported empty command working directory")
	}
	if archiveID, ok := parseItemDir(pathValue); ok {
		stepID := archiveToStepID[archiveID]
		if stepID == "" {
			return "", PathRewrite{}, false, fmt.Errorf("command step references unknown path label %s", archiveID)
		}
		return `sptHomeDir + "/log/" + ` + jsQuote(stepID), PathRewrite{
			ArchiveID: archiveID,
			StepID:    stepID,
			From:      pathValue,
			To:        "${MONGOOSE_DIR}/log/" + stepID,
		}, true, nil
	}
	if homeRelative, ok := parseMongoosePath(pathValue); ok {
		return `sptHomeDir + "/` + jsEscape(homeRelative) + `"`, PathRewrite{}, false, nil
	}
	return "", PathRewrite{}, false, fmt.Errorf("unsupported command working directory: %s", raw)
}

func isAllowedReplayCommand(command string) bool {
	switch command {
	case "cat", "cp", "mv", "split":
		return true
	default:
		return false
	}
}

func isSafeReplayCommandArg(arg string) bool {
	if arg == "" || strings.HasPrefix(arg, "/") || strings.Contains(arg, "..") {
		return false
	}
	return safeCommandArgRe.MatchString(arg)
}

func detectUnsupportedProtocols(legacy legacyScenario) []Diagnostic {
	var diagnostics []Diagnostic
	check := func(v any) {
		driver := strings.ToLower(resolveString(v, nil))
		switch driver {
		case "", storageDriverTypeS3, storageDriverTypeEMCS3, storageDriverTypeS3AWS, storageDriverTypeS3RDMA:
		case "fs":
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: "NFS/FS replay is not implemented for storage.driver.type fs"})
		case "atmos", "cas", "swift":
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: fmt.Sprintf("%s replay is not implemented", strings.ToUpper(driver))})
		default:
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: fmt.Sprintf("unsupported storage.driver.type %q", driver)})
		}
	}
	check(getPath(legacy.Config, legacyKeyStorage, legacyKeyDriver, legacyKeyType))
	for _, step := range append(append([]legacyStep{}, legacy.Steps...), legacy.Jobs...) {
		if strings.EqualFold(step.Type, legacyStepTypeParallel) {
			diagnostics = append(diagnostics, Diagnostic{Severity: severityError, Message: errParallelReplayUnimplemented})
		}
		check(getPath(step.Config, legacyKeyStorage, legacyKeyDriver, legacyKeyType))
	}
	return diagnostics
}

func effectiveBucket(localBucket string, runScript RunScript) string {
	if strings.TrimSpace(localBucket) != "" {
		return strings.TrimSpace(localBucket)
	}
	if strings.TrimSpace(runScript.ItemOutputPath) != "" {
		return strings.TrimSpace(runScript.ItemOutputPath)
	}
	return strings.TrimSpace(runScript.Exports["BUCKET"])
}

func getPath(m map[string]any, path ...string) any {
	var cur any = m
	for _, p := range path {
		asMap, ok := cur.(map[string]any)
		if !ok {
			return nil
		}
		cur = asMap[p]
	}
	return cur
}

func firstPath(m map[string]any, paths ...[]string) any {
	for _, p := range paths {
		if v := getPath(m, p...); v != nil {
			return v
		}
	}
	return nil
}

func setPath(m map[string]any, value any, path ...string) {
	cur := m
	for _, p := range path[:len(path)-1] {
		next, ok := cur[p].(map[string]any)
		if !ok {
			next = map[string]any{}
			cur[p] = next
		}
		cur = next
	}
	cur[path[len(path)-1]] = value
}

func resolveString(v any, vars map[string]string) string {
	switch t := v.(type) {
	case nil:
		return ""
	case string:
		return expandWithExports(t, vars)
	case json.Number:
		return t.String()
	case float64:
		return strconv.FormatFloat(t, 'f', -1, 64)
	case bool:
		return strconv.FormatBool(t)
	default:
		return fmt.Sprint(t)
	}
}

func intValue(v any, vars map[string]string) int {
	n := int64Value(v, vars)
	if n > int64(^uint(0)>>1) {
		return 0
	}
	return int(n)
}

func int64Value(v any, vars map[string]string) int64 {
	switch t := v.(type) {
	case json.Number:
		n, _ := t.Int64()
		return n
	case float64:
		return int64(t)
	case int:
		return int64(t)
	case int64:
		return t
	case string:
		n, _ := strconv.ParseInt(strings.TrimSpace(expandWithExports(t, vars)), 10, 64)
		return n
	default:
		return 0
	}
}

func boolValue(v any, vars map[string]string) (bool, bool) {
	switch t := v.(type) {
	case bool:
		return t, true
	case string:
		b, err := strconv.ParseBool(strings.TrimSpace(expandWithExports(t, vars)))
		return b, err == nil
	default:
		return false, false
	}
}

func floatValue(v any, vars map[string]string) (float64, bool) {
	switch t := v.(type) {
	case json.Number:
		n, err := t.Float64()
		return n, err == nil
	case float64:
		return t, true
	case float32:
		return float64(t), true
	case int:
		return float64(t), true
	case int64:
		return float64(t), true
	case string:
		n, err := strconv.ParseFloat(strings.TrimSpace(expandWithExports(t, vars)), 64)
		return n, err == nil
	default:
		return 0, false
	}
}

func stringListValue(v any, vars map[string]string) ([]string, bool) {
	switch t := v.(type) {
	case []any:
		values := make([]string, 0, len(t))
		for _, raw := range t {
			value := strings.TrimSpace(resolveString(raw, vars))
			if value == "" {
				continue
			}
			values = append(values, value)
		}
		return values, len(values) > 0
	case []string:
		values := make([]string, 0, len(t))
		for _, raw := range t {
			value := strings.TrimSpace(expandWithExports(raw, vars))
			if value == "" {
				continue
			}
			values = append(values, value)
		}
		return values, len(values) > 0
	case string:
		values := splitCSV(expandWithExports(t, vars))
		return values, len(values) > 0
	default:
		return nil, false
	}
}

func durationValue(v any, vars map[string]string) string {
	s := strings.TrimSpace(resolveString(v, vars))
	if s == "" {
		return ""
	}
	if _, err := strconv.Atoi(s); err == nil {
		return s + "s"
	}
	return s
}

func unresolvedVars(v any, vars map[string]string) []string {
	s, ok := v.(string)
	if !ok || s == "" {
		return nil
	}
	var missing []string
	matches := expandVarRe.FindAllStringSubmatch(s, -1)
	for _, match := range matches {
		if len(match) != 2 {
			continue
		}
		value, ok := vars[match[1]]
		if !ok || strings.TrimSpace(value) == "" {
			missing = append(missing, match[1])
		}
	}
	return missing
}

func requiresExplicitLimit(opType string) bool {
	switch opType {
	case opTypeCreate, opTypeRead:
		return true
	default:
		return false
	}
}

func itemPathString(v any, vars map[string]string) string {
	s, ok := v.(string)
	if !ok {
		return resolveString(v, vars)
	}
	return osExpandPreservingMongooseDir(s, vars)
}

func osExpandPreservingMongooseDir(s string, vars map[string]string) string {
	return osExpand(s, func(key string) string {
		if key == legacyMongooseDirVar {
			return "${MONGOOSE_DIR}"
		}
		if vars != nil {
			if v, ok := vars[key]; ok {
				return v
			}
		}
		return ""
	})
}

func osExpand(s string, mapping func(string) string) string {
	return expandVarRe.ReplaceAllStringFunc(s, func(match string) string {
		name := strings.TrimPrefix(match, "$")
		name = strings.Trim(name, "{}")
		return mapping(name)
	})
}

func exprPlaceholder(name string) string {
	return "__SPT_EXPR_" + name + "__"
}

func marshalJSConfig(config map[string]any) (string, error) {
	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return "", err
	}
	out := string(data)
	if unsafeExprSentinelRe.MatchString(out) && !exprPlaceholderRe.MatchString(out) {
		return "", fmt.Errorf("config contains reserved replay expression sentinel")
	}
	out = exprPlaceholderRe.ReplaceAllString(out, `$1`)
	return out, nil
}

func jsQuote(s string) string {
	data, _ := json.Marshal(s)
	return string(data)
}

func jsEscape(s string) string {
	data, _ := json.Marshal(s)
	quoted := string(data)
	return quoted[1 : len(quoted)-1]
}

func jsLineComment(s string) string {
	return strings.ReplaceAll(s, "\n", " ")
}

func s3DriverType(userValue string) string {
	switch strings.ToLower(strings.TrimSpace(userValue)) {
	case "aws":
		return storageDriverTypeS3AWS
	case "rdma":
		return storageDriverTypeS3RDMA
	default:
		return storageDriverTypeS3
	}
}

func sanitizeLabel(label string) string {
	label = strings.TrimSpace(label)
	if label == "" {
		return ""
	}
	var b strings.Builder
	for _, r := range label {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '.' || r == '_' || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

func formatStepID(label string, stepNumber int, baseTS string, op string) string {
	return fmt.Sprintf("%s-%03d-%s-%s", label, stepNumber, baseTS, strings.ToLower(op))
}

func baseTimestamp() string {
	return time.Now().UTC().Format("20060102.150405.000")
}

func hasErrors(diagnostics []Diagnostic) bool {
	for _, d := range diagnostics {
		if d.Severity == severityError {
			return true
		}
	}
	return false
}

func diagnosticsError(diagnostics []Diagnostic) error {
	diagnostics = normalizeDiagnostics(diagnostics)
	var messages []string
	for _, d := range diagnostics {
		if d.Severity == severityError {
			messages = append(messages, d.Message)
		}
	}
	if len(messages) == 0 {
		return nil
	}
	return newClassifiedError(firstErrorClass(diagnostics), strings.Join(messages, "; "), errors.New(strings.Join(messages, "; ")))
}

func uniquePathRewrites(rewrites []PathRewrite) []PathRewrite {
	out := make([]PathRewrite, 0, len(rewrites))
	seen := map[string]struct{}{}
	for _, rewrite := range rewrites {
		key := rewrite.From + "\x00" + rewrite.To
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, rewrite)
	}
	return out
}
